### ISSUE TITLE
Can't drag a window in floating mode unless you have moved the cursor since the last drag

### ISSUE THREAD

**Issue by hojjatabdollahi** [pop-os/cosmic-comp#100]
To replicated:

- Enable floating mode.
- Grab a window and move the window to a new position, this works
- Do not move the cursor and try to grab the window again to move it.
- You can't move the window unless you have moved the cursor since the last drag

**Comment by Drakulix** [comment]
Should be fixed by https://github.com/pop-os/cosmic-comp/commit/33eedb0b582096d82c2359a5b4fffef0a65115b6.

Thanks for the clear instructions on reproducing this bug! :)

**Comment by hojjatabdollahi** [comment]
It did not fix it. I can still recreate this error. 

```
> apt info cosmic-comp               
Package: cosmic-comp
Version: 0.1~1681897366~22.04~33eedb0
```

**Comment by hojjatabdollahi** [comment]
It's fixed. Thank you.
