### ISSUE TITLE
Context menu on desktop cannot be closed using a left click

### ISSUE THREAD

**Issue by Elias-Graf** [pop-os/cosmic-comp#1067]
# Description
Context menu on desktop cannot be closed using a left click.

https://github.com/user-attachments/assets/a04a71ec-b6cf-464d-bd0c-51bd75a5660d

# Expected
The context menu can be closed using a left click.

# Actual
The only way to close the context menu, seems to be a right click.

**Comment by git-f0x** [comment]
It can, but only when there's something on the desktop.
Duplicate of pop-os/cosmic-epoch#1158 (this isn't a `cosmic-comp` issue).

**Comment by Elias-Graf** [comment]
Sorry for incorrectly reporting this. To be honest, I sometimes struggle what to report where, when it isn't an obvious program like cosmic-term or files. Closing as won't fix in favor of https://github.com/pop-os/cosmic-epoch/issues/1158

**Comment by git-f0x** [comment]
If you're not sure, it would be best to report issues on the `cosmic-epoch` repo, since that's a catch-all repo.
