### ISSUE TITLE
`Super` + `F` does nothing if there is already a window open

### ISSUE THREAD

**Issue by n3m0-22** [pop-os/cosmic-comp#107]
In Pop!_OS GNOME if a File (Nautilus) window is open on a workspace, and from another workspace `Super` + `F` it will take you back to the workspace where it is open. This does not work in COSMIC DE.

**Comment by n3m0-22** [comment]
I missed that. You're correct. Thanks for clarifying.

**Comment by WatchMkr** [comment]
That's fascinating and weird behavior.

I think that no matter where you are, the shortcut should lunch a new instance. Super + B seems to work this way and feels appropriate. I don't think app launching shortcuts should switch window focus or workspaces.

**Comment by XV-02** [comment]
Right now, we open a new instance of Nautilus (still the default file manager while Cosmic-Files development continues) every time `Super + F` is used. This appears to be the desired behaviour, and represents a consistent action when compared with `Super + T` or `Super + B` - both of which launch a new instance when evoked. 

As such, this no longer seems to be a relevant issue. I'm closing it.
