### ISSUE TITLE
[Bug] When connecting my external monitor, my cursor duplicated

### ISSUE THREAD

**Issue by feikedonia** [pop-os/cosmic-comp#1075]
It took me a while to upload a video to github, but we are there.

I connected an external monitor to my laptop running EndeavourOS. One window desided to go to the external monitor, the others didn't, which was fine. Except I got an extra cursor, acting like a fake mirror of my real cursor. The fake cursor went to the external monitor (Right on the video); the real one is on the left. Because of this, I couldn't manipulate the external monitor, because I also set focus follows cursor, read: the *real* cursor.

_(In the video, which I filmed from my phone, send to my computer via signal messenger because Cosmic files doesn't seem to support external android defices. And rendered on kdenlive (terible user interface) .... (i am proud of the hole excepade) -- thank you to @BrodieRobertson for showing how to use kdenlive!)_

Where was I, In the video I show manipulating a window. 
I eventually recovered from the bug by going to settings -> displays and there my external monitor nr 0 was drawn into / onderneath my laptop screen nr 1. When I dragged nr 0 to the side, the situation got better.

[hardware]
11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
Intel internal GPU
external monitor: HDMI to VGA dongle -> 1280x1024 @ 60 Hz monitor

[software]
EndeavourOS
Linux 6.12.4-arch1-1
Cosmic Alpha 4 ...

With kind regards,
Feike Donia

[gedubliceerde-cursor.webm](https://github.com/user-attachments/assets/8eae6db2-bba8-449b-8372-5d796eeba4d9)

**Comment by Drakulix** [comment]
Your outputs are likely overlapping in the configuration. Check the display tab in cosmic settings.

**Comment by feikedonia** [comment]
Sounds plausible. I also descripbte that in my issue

![screenshot-2024-12-17-16-39-35](https://github.com/user-attachments/assets/426adc9e-7cb2-44b0-ba07-6cbcd070a651)
