### ISSUE TITLE
[Bug] When selecting screen mirroring, COSMIC crashes and relaunches itself, with a memory leak

### ISSUE THREAD

**Issue by feikedonia** [pop-os/cosmic-comp#1076]
**Description**
When I tested out the screen mirroring option in `Settings` -> `Displays`, selecting `Project to [monitor]` or `Mirror [monitor]`, the desktop crashed and relaunched itself. _(evidenced by the EndeavourOS welcome app re-appearing)_ Then some program slurps op all memory, then your system is frozen.

**Steps to reproduce**
1. have a external monitor
2. go to `Settings` -> `Displays`, selecting `Project to [monitor]` or `Mirror [monitor]`
3. Cosmic restarts
4. Open an system monitor app and watch the memory get eaten! 

**Hardware**
8 × 11th Gen Intel® Core™ i7-1165G7 @ 2.80GHz
Mesa Intel® Iris® Xe Graphics

**Software**
cosmic-session 1.0.0.alpha.4-1
kernel: 6.12.4-arch1-1 (64-bits)
EndeavourOS

_Watch the eating of memory_
![Memory Leak](https://github.com/user-attachments/assets/88a28642-2312-4f7c-86db-469d30506402)

Tell me if you want a video, It is difficult but I can make it

**Comment by feikedonia** [comment]
Possible duplicate of #871

**Comment by git-f0x** [comment]
This should be fixed with the latest commits. See #1047.

**Comment by feikedonia** [comment]
So... I should tryout the latest commit then, Which I find a nice idea, because it is not as if the main releases are more stable. Might aswell compile to the latest git commit... Therefore I can use the AUR, can't I?

**Comment by git-f0x** [comment]
You could also use the Chaotic AUR, which has precompiled binaries of git versions (since compilation can take a while).

**Comment by feikedonia** [comment]
Cool, I'm now on cosmic-session-git 1.0.0.alpha.4.r2.g0a3b9f5-1
