### ISSUE TITLE
More consistent cursor warping (cursor follows focus)

### ISSUE THREAD

**Issue by ymcx** [pop-os/cosmic-comp#1081]
The current behaviour is rather lenient, as it seems to only warp the cursor when focusing on a different window within the same workspace or when moving a window to a different workspace. Ideally I think it should also warp in the following situations:
1. Workspace change without moving a window
2. Moving a window within the current workspace
3. Moving a window to a different monitor (currently it warps to the middle of the screen)

Having the cursor be on a non-focused window can be disorienting, as you'd assume that the window under the cursor is the active one. If it isn't, you'll have to focus it by either moving the focus to a different window and back or alternatively by using the mouse.

**Comment by feikedonia** [comment]
I think this issue is a replicate of  #963.
