### ISSUE TITLE
Xwalyand apps lose mouse interactions

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-comp#109]
From our internal conversation

>  There are a couple annoyances that don't bother me but might bother others. Biggest one I see is loosing mouse interactions in xwalyand apps and needing to restart them.

> This most likely is the result of a mismatch in state of where Xwayland expects the window to be and were cosmic-comp is tracking the window. (Synchronizing the two is a major pain point.)
> So if  you even figure out any common patterns of how you end up with this desynchronization, PLEASE tell me. Reproducing these kinds of issues for debugging is quite difficult otherwise.

**Comment by n3m0-22** [comment]
The best way I have found so far to reproduce this, and it is intermittent, is as follows.

In tiling mode:
- open blender
- open terminal with `Super` + `T`

Sometime this will cause blender to no longer register mouse clicks.

This also creates an odd state that raises a couple other issues that I have so far only seen with blender, but are likely related. I will link them here once filed.
