### ISSUE TITLE
When moving a tiled window, it sometimes moves too far

### ISSUE THREAD

**Issue by isaac-8601** [pop-os/cosmic-comp#113]
It seems that there are two cases so far where a window jumps too far when moving it with the keyboard Shift+Super shortcuts: 

- If I put three windows in equal thirds in one row on the screen, and a window full-width in a second row below that, and move that bottom window up, it joins into a group with the middle window but will appear at the top of that group instead of the bottom. It should be in the bottom of that group.
- If I move a window from the second workspace (right of the first) to a first workspace, it will appear in the leftmost group if there are multiple windows, instead of just appearing on the right (no group).

**Comment by Drakulix** [comment]
> If I put three windows in equal thirds in one row on the screen, and a window full-width in a second row below that, and move that bottom window up, it joins into a group with the middle window but will appear at the top of that group instead of the bottom. It should be in the bottom of that group.

Should be fixed by https://github.com/pop-os/cosmic-comp/commit/bf0eb97bea5d46cd0de53057ceb093040bef85aa

> If I move a window from the second workspace (right of the first) to a first workspace, it will appear in the leftmost group if there are multiple windows, instead of just appearing on the right (no group).

Should be fixed by https://github.com/pop-os/cosmic-comp/commit/2f6d4da7124b8a6d176aa9fd806b2c85dd7e0dd9
