### ISSUE TITLE
Aspect ratio issues while moving tiled windows

### ISSUE THREAD

**Issue by isaac-8601** [pop-os/cosmic-comp#117]
In the current implementation of [tiling with a keyboard](https://github.com/pop-os/cosmic-epoch/issues/36), some windows that are much longer on one dimension than the other dimension are noticeably awkwardly spaced in the zoomed-out view.

In our guidance for moving tiled windows, we suggested scaling instead of resizing, but it's clear that scaling alone will give us weird results that aren't present on our limited prototypes. It's probably on us on the design team to figure this out--although we'll need some help on what's technically feasible.

**Comment by Drakulix** [comment]
Fixed in new design (mostly implemented by https://github.com/pop-os/cosmic-comp/commit/24d3b794fe3b1dee46dc0944781d9a924ea03534)
