### ISSUE TITLE
Focus is broken when using more then one workspace

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/cosmic-comp#120]
Steps to recreate:

1. Open a browser on workspace 1, clicking things works as expected
2. Open another application in workspace 2 that has links
3. You can click on the links in that application in workspace 2 though the application in workspace 1. The other buttons/elements in the browser no longer work just the links in the application on workspace 2.

**Comment by Drakulix** [comment]
Note: Likely an Xwayland stacking order bug.
