### ISSUE TITLE
Unmaximized windows are not resized when tiled

### ISSUE THREAD

**Issue by mmstick** [pop-os/cosmic-comp#125]
With tiling enabled, unmaximizing a window moves it into the position of its node and is clipped to fit, but the clipped regions are still clickable. It's most noticeable if you toggle maximization of the left-most window and then try to click on the contents of any window to the right of it. It's fixable by triggering a resize by moving the window around.

**Comment by Drakulix** [comment]
Input regions extending beyond tiles has been addressed in https://github.com/pop-os/cosmic-comp/commit/8dd8ac0492bcea102ba7b543f9bb9df21c438f07.
Missing resize has been added in https://github.com/pop-os/cosmic-comp/commit/e95bfeab53d83c40e9d244ba53419358cffe0e47.

**Comment by Drakulix** [comment]
Firefox sometimes resets it's size when restoring a session, but that is likely not, what  you are seeing, if gedit and alacritty are also misbehaving. I'll investigate.
