### ISSUE TITLE
Windows sometimes move laterally instead of in the intended direction

### ISSUE THREAD

**Issue by isaac-8601** [pop-os/cosmic-comp#129]
![lateral example (1)](https://github.com/pop-os/cosmic-comp/assets/106764128/70f680d9-d204-4d78-9d58-d2d3ea34efe0)

If we have a layout similar to the example above, moving Window C should cause Window C to become a row above all of the other windows. Currently it is jumping laterally above Window A.

**Comment by Drakulix** [comment]
Fixed by 90e1eab7a856a180aaef7c95fc1a8ff52055ee3b
