### ISSUE TITLE
X Axis Block Artifacts

### ISSUE THREAD

**Issue by Vixea** [pop-os/cosmic-comp#130]
(will update with screenshots later)

When running cosmic with mismatched resolution monitors the higher resolution monitor has artifacts on it that can be described as blocks of multiple pixels that seem to be rotated or repeating causing the most noticeable artifact on high contrast curves. It looks like serrated teeth flipped horizontally running down the curve or it may actually be shifted?

**Comment by Vixea** [comment]
![PXL_20230606_154100807.jpg](https://github.com/pop-os/cosmic-comp/assets/112600048/591a1def-1614-4bc4-a8d7-74f4d655fdc2)

Lower resolution(1080p) looks fine

**Comment by Vixea** [comment]
![PXL_20230606_154053393.jpg](https://github.com/pop-os/cosmic-comp/assets/112600048/4032885c-3d12-46cc-87b8-203c535cbee7)

Higher resolution(1440p) doesn't look fine

**Comment by Drakulix** [comment]
I am honestly not sure, what exactly I am looking for on these screenshots. Can you try to highlight the problematic parts?

Also this is only happening for you on a multi-monitor setup? If you disable either monitor (e.g. by using `wdisplays`) the problem disappears?

**Comment by Vixea** [comment]
Good questions I'm not able to get on my system rn,  anyway look closely at the icons on the right hand side

**Comment by Vixea** [comment]
Well I tried two things both failed first was turning off my lower resolution monitor got something LIKE this when getting into sddm ![PXL_20230606_223003970.jpg](https://github.com/pop-os/cosmic-comp/assets/112600048/997bdbb1-9b0b-46dc-a319-085de6e6a640)


^ this is what I get when in cosmic and disabling the lower resolution monitor aka 1080p

Ah it happens with either monitor strange

**Comment by Vixea** [comment]
Possibly a kernel bug?

**Comment by Drakulix** [comment]
> Possibly a kernel bug?

I think say so. This looks like some sort of tiled/compressed representation of screen contents. I have never seen such artifacts on other systems with cosmic-comp, so I am inclined to call this a driver/kernel bug.

**Comment by Vixea** [comment]
Do you know how to remove wdisplays configuration?

**Comment by Drakulix** [comment]
> Do you know how to remove wdisplays configuration?

Output configuration is stored in `.local/state/cosmic-comp/outputs.ron`. Wiping that file gives a fresh setup, it can also be edited directly instead of using tools like `wdisplays`.
(But a broken configuration file can result in cosmic-comp resetting the whole thing, while invalid configuration via tools like wdisplays over the wlr-output-configuration protocol is just refused.)

**Comment by Vixea** [comment]
> > Possibly a kernel bug?
> 
> I think say so. This looks like some sort of tiled/compressed representation of screen contents. I have never seen such artifacts on other systems with cosmic-comp, so I am inclined to call this a driver/kernel bug.

Disabled tiling it still has the issue.

**Comment by Drakulix** [comment]
Honestly I am not sure what to do at this point. Does anvil show the same symptoms? https://github.com/Smithay/smithay/tree/master/anvil

**Comment by Vixea** [comment]
how would you like me to run it, would Firefox would be a good app to run it with?

**Comment by Vixea** [comment]
wait I KNOW It the bug in the matrix chat that as the screen pans right stuff gets more and more blurry it seems to only affect high dpi panels?

**Comment by Vixea** [comment]
[https](https://github.com/AsahiLinux/linux/issues/72#issuecomment-1549297726)

**Comment by Vixea** [comment]
Is it possible it's a drm bug to affect multiple compositors using completely different libraries?

**Comment by Drakulix** [comment]
If it is affecting multiple completely different compositors, it is actually more likely to be a drm/mesa bug, since that is the only common component in that case.
Though theoretically all compositors could be buggy in the same way.

**Comment by Vixea** [comment]
One in a million chance but it would be funny if that was it(kde works fine) I'll make a bug report for mesa and see where that goes

**Comment by Drakulix** [comment]
Is this still an issue or can this be closed?

**Comment by Vixea** [comment]
Still an issue

**Comment by Vixea** [comment]
Huh idk what changed but it looks fine since the fresh reinstall and this recent update the history of this issue has had no comments other than me I could safely it's been resolved. I'm getting closer to where I can say this will be my daily de all that needs to be done is pointer confinement and being able to resize Steam and few other apps and have them not resize when moving them around.

**Comment by Vixea** [comment]
It's happening again @Drakulix

**Comment by Vixea** [comment]
text rendering is definitely wrong

**Comment by Vixea** [comment]
For example look at ![PXL_20230908_230611813.jpg](https://github.com/pop-os/cosmic-comp/assets/112600048/da9f3a14-cb1c-4453-afe3-690762de6dcf)

I'm glad I installed Grammarly it showcases it really well

**Comment by Vixea** [comment]
With the eyes it appears to be jaggy and not like a circle as it should

**Comment by Vixea** [comment]
it seems to be something about subpixel layout though this monitor has a RGB layout I think so idk why that's its looks wrong

**Comment by Vixea** [comment]
but then again why would it happen on GUI image elements instead of just text

**Comment by mmstick** [comment]
@Vixea Try to keep your messages in a single comment to prevent GitHub from sending multiple emails.

**Comment by Vixea** [comment]
Ok

**Comment by Drakulix** [comment]
> it seems to be something about subpixel layout though this monitor has a RGB layout I think so idk why that's its looks wrong

I am pretty sure smithay currently doesn't expose the subpixel layout correctly (it will return `Unknown`). Work is underway to fix this: https://github.com/Smithay/drm-rs/pull/147. I am not sure, that this is what is causing your problem, but its not unlikely.

Once that is done, I'll give you a ping.
