### ISSUE TITLE
Tiling layout needs to be re-computed automatically on change LayerMap

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#134]
I haven't gotten around to trying to fix this,  so I may as well open an issue.

Changing monitor configuration, opening a new layer-shell surface with an exclusive zone, or removing a monitor and having workspaces move to a different one do not result in the tiling layout being adjusted to fit in the new space constraints. I believe this is based on LayerMap, so it will have to handle changes to the LayerMap in some way.

Tested in current `master_jammy` (b1985b0052c26576492b343076562ba318c680af).

**Comment by Drakulix** [comment]
Almost fixed, filled https://github.com/Smithay/smithay/pull/1076 additionally to be able to handle the layer-surface client disconnects case.
https://github.com/pop-os/cosmic-comp/commit/1868f6b0f76bbfd95c651f19df8f8bf3034d0ede should take care of the rest.

**Comment by XV-02** [comment]
This appears to be resolved. I'm closing this issue.
