### ISSUE TITLE
can't set refresh rate

### ISSUE THREAD

**Issue by RyzenDew** [pop-os/cosmic-comp#139]
so i found the display configs and was trying to set 165hz but could not here is my config 

[outputs.txt](https://github.com/pop-os/cosmic-comp/files/12156168/outputs.txt)

**Comment by Drakulix** [comment]
It is part of the mode. I am not sure which your monitors you want to set the refresh rate for, but lets say your want to change it for the `DP-2`/`L226WT`, you would need to change this line:
`mode: ((1680, 1050), Some(59883)),` to `mode: ((1680, 1050), Some(165000)),`. cosmic-comp will correct the refresh rate, if it is slightly off from the one advertised by your monitor, so don't be too concerned figuring out the perfect value.

However I don't recommend directly editing the output configuration file. Instead use a utility like https://github.com/luispabon/wdisplays
