### ISSUE TITLE
Mix Interface dual monitors(HDMI and DP) crashes Cosmic

### ISSUE THREAD

**Issue by Vixea** [pop-os/cosmic-comp#141]
When running one monitor with HDMI and one with DP this happens.
```
cosmic-comp[2051]: [EGL] 0x3004 (BAD_ATTRIBUTE) eglGetPlatformDisplay: eglGetPlatformDisplay
cosmic-comp[2051]: [EGL] 0x3004 (BAD_ATTRIBUTE) eglGetPlatformDisplayEXT: Could not create EGLDisplay
cosmic-comp[2051]: [EGL] 0x3004 (BAD_ATTRIBUTE) eglGetPlatformDisplay: eglGetPlatformDisplay
cosmic-comp[2051]: [EGL] 0x3004 (BAD_ATTRIBUTE) eglGetPlatformDisplayEXT: Could not create EGLDisplay
cosmic-comp[2051]: Unable to find suitable EGL platform
cosmic-comp[2051]: Failed to restore previous state. Error: invalid argument
```

**Comment by Vixea** [comment]
1. RX 6700XT
2. Sure thing
3. huh I did a search for this to make sure I had a fresh one, couldn't find it but it does exist so let me try it

**Comment by Vixea** [comment]
Bad news running a fast debug build guys me no new information

**Comment by Vixea** [comment]
Do I need to pull out some drm debugging?

**Comment by Drakulix** [comment]
> Bad news running a fast debug build gives me no new information

You can try setting this to debug: https://github.com/pop-os/cosmic-comp/blob/master_jammy/src/logger/mod.rs#L20

It might log a lot in that case though.

> Do I need to pull out some drm debugging?

Wouldn't hurt either.

**Comment by Vixea** [comment]
Cosmic with debug build:
https://pastebin.com/CdPUwv6A
DRM Debugging:
https://drive.google.com/file/d/13dZ0nU2hAx8rmJ8etFxkUf0856U1fBPj/view?usp=sharing

**Comment by Vixea** [comment]
Using my DP monitor I get the same thing, using the HDMI monitor I get the sddm issue a had in #130 keep in mind this is before I get into GDM(which I'm using now) so this is a kernel-level bug.

DRM INFO:
https://drive.google.com/file/d/1kA60ZHJUVbQQbDk3_uzVIQ6rqxMPTada/view?usp=sharing

**Comment by Vixea** [comment]
It turns out the weird graphical corruption could be because gigabyte first vbios for this card is bad just updated it and did a fresh install(basically completely rebuilt the PC - did a major upgrade of all the components except the gpu)

**Comment by Vixea** [comment]
Anyway I'm now unable to reproduce so I'm going to close it
