### ISSUE TITLE
baackend::x11 don't just assume DISPLAY if its unset

### ISSUE THREAD

**Issue by colemickens** [pop-os/cosmic-comp#149]
I find it very unsettling that I unset `DISPLAY` to try to force cosmic-comp to use ... (hopefully?) a Wayland backend. And yet, cosmic has launched itself on X11 and dies when I `pkill Xwayland`.

This seems odd to me, and seems like there was likely code somewhere to try and guess if DISPLAY is unset, which seems like a "feature" that will potentially wind up masking other distro/DE setup issues.

**Comment by colemickens** [comment]
I guess I (also) find it odd that x11 is preferred over winit: https://github.com/pop-os/cosmic-comp/blob/2729be8542560fe68c944e23b922b5be32174595/src/backend/mod.rs#L33

**Comment by Drakulix** [comment]
The x11-backend doesn't do this, it is the winit-backend that does (which we don't really have control over).

The state of the winit-backend in smithay is in rather bad shape, which is due to integration issues we used to have and have not yet cleaned up.

As a result the x11-backend is much more feature-complete, which is why cosmic-comp is preferring it. Winit also doesn't default to wayland, so even if you unset `DISPLAY`, the x11-backend will fail and winit will still end up using x11.

To get a native wayland backend use these environment variables: `COSMIC_BACKEND=winit WINIT_UNIX_BACKEND=wayland`.

**Comment by Drakulix** [comment]
Hmm, you are right, if setting `COSMIC_BACKEND=winit` selects wayland by default, then the X11-backend must somehow be responsible for making up some `DISPLAY` value.

But I am not sure, where that could be happening, given we use `x11rb` for our X11 code and its connection code (see [here](https://github.com/psychon/x11rb/blob/master/x11rb/src/rust_connection/mod.rs#L116C61-L116C74)), has a parse-method, that errors out, if the variable isn't set (see [here](https://github.com/psychon/x11rb/blob/master/x11rb-protocol/src/parse_display/mod.rs#L53)).

I don't have the time to investigate this further right now, but this should definitely not be happening.

**Comment by colemickens** [comment]
I swear I tested this, but maybe I wasn't handling environment correctly under `nushell`. I'm very sorry if this is a goose chase.

This indeed *does* look like it tries the X11 backend, fails "Display parsing error", and then falls into winit which uses Wayland. (The x11rb event there at the end is me killing Xwayland and checking that cosmic-comp kept running)

Given this is smelling more and more like maybe I hadn't actually cleared the DISPLAY variable, I'm going to go ahead and close this. (I think I might have also confused myself since the winit/wayland backend wasn't working until I added Wayland as a runtimeDep.)

```shell
~/code/cosmic/cosmic-comp master_jammy*
❯ unset DISPLAY

~/code/cosmic/cosmic-comp master_jammy*
❯ ./result/bin/cosmic-comp
2023-08-08T15:50:11.427006Z  WARN cosmic_comp::backend: Initializing X11 Backend failed. err=Failed to initilize X11 backend

Caused by:
    0: Connecting to the X server failed
    1: Display parsing error
[src/backend/winit.rs:128] config.mode.0 = (
    1280,
    800,
)
[src/backend/winit.rs:128] (size.physical_size.w as i32, size.physical_size.h as i32) = (
    1280,
    800,
)
interface 'wl_surface' has no event 2
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
2023-08-08T15:50:17.424653Z ERROR smithay::utils::x11rb: Event thread exiting due to connection error The X11 server closed the connection
```
