### ISSUE TITLE
Focus switching shortcuts do not traverse monitors

### ISSUE THREAD

**Issue by jackpot51** [pop-os/cosmic-comp#160]
In the OutputBound workspaces mode, with three monitors arranged horizontally, I cannot use super+hjkl to move focus to windows on other monitors. However, the move shortcuts (super+shift+hjkl) work correctly

**Comment by Drakulix** [comment]
Interesting, both the `Focus` action and the `Move` action essentially use the same fallback logic:

[Focus](https://github.com/pop-os/cosmic-comp/blob/master_jammy/src/input/mod.rs#L1231-L1294): If the focus function returns `FocusResult::None` it will translate the action into a `Next/PreviousOutput` or `Next/PreviousWorkspace` function.

[Move](https://github.com/pop-os/cosmic-comp/blob/master_jammy/src/input/mod.rs#L1295-L1356) does essentially the same, if the move function returns `MoveFurther`.

The only immediate problem I am seeing here, is that this operates exclusively on the tiling layer, so switching focus between floating windows will not happen and thus also not go to different workspaces/outputs at the moment.

**Comment by jackpot51** [comment]
Another thing that may be helpful, is that NextOutput and PreviousOutput are not working either with my current config and monitor setup.

`outputs.ron`:
```
(
    config: {
        [
            (
                connector: "DP-1",
                make: "Unknown",
                model: "Unknown",
            ),
            (
                connector: "DP-2",
                make: "Unknown",
                model: "Unknown",
            ),
            (
                connector: "DP-3",
                make: "Unknown",
                model: "Unknown",
            ),
        ]: [
            (
                mode: ((2560, 1440), Some(144000)),
                vrr: false,
                scale: 1.0,
                transform: Normal,
                position: (0, 0),
                enabled: true,
                max_bpc: Some(16),
            ),
            (
                mode: ((2560, 1440), Some(144000)),
                vrr: false,
                scale: 1.0,
                transform: Normal,
                position: (2560, 0),
                enabled: true,
                max_bpc: Some(16),
            ),
            (
                mode: ((2560, 1440), Some(144000)),
                vrr: false,
                scale: 1.0,
                transform: Normal,
                position: (5120, 0),
                enabled: true,
                max_bpc: Some(16),
            ),
        ],
    },
)
```
