### ISSUE TITLE
Mouse clicks not properly delivered when in Global workspace mode

### ISSUE THREAD

**Issue by jackpot51** [pop-os/cosmic-comp#161]
In Global workspaces mode, with three monitors arranged horizontally, I often cannot click on controls on windows that are on the second and third monitor.

**Comment by Drakulix** [comment]
Oh fun, I wonder what broke this, as this definitely used to work...

This [function](https://github.com/pop-os/cosmic-comp/blob/master_jammy/src/shell/mod.rs#L1173) should translate from global coordinates to workspace-relative coordinates. Which should be the same coordinate space, in global-workspace-mode, which makes the issue more perplexing. For output-local-workspaces the translating basically remaps the event to be relative to the output.

I guess somewhere we are missing this translation call..

**Comment by ids1024** [comment]
Took a while to track it down, but https://github.com/pop-os/cosmic-comp/pull/172 seems to fix this.

**Comment by jackpot51** [comment]
This is still an issue for the cosmic panel, if it is running on the middle display in a three display setup.

**Comment by jackpot51** [comment]
Re-opening, since the cosmic panel is not receiving mouse clicks when on the middle display in a three display setup, while using Global worskpace mode.
