### ISSUE TITLE
Resizing stacked windows in floating mode takes a long time.

### ISSUE THREAD

**Issue by hojjatabdollahi** [pop-os/cosmic-comp#163]
After disabling tiling mode the stacked windows stay stacked. I'm not sure if it is an intended behavior, but the tabs don't work properly in floating mode.

After disabling the tiling mode, changing the size of the stacked window messes with the tabs.  In one occasion the tabs started to resize on their own with a very slow animation.

![image](https://github.com/pop-os/cosmic-comp/assets/2222199/d2651676-3ceb-4be7-a665-c007877e311e)

**Comment by mmstick** [comment]
It is by design that the whole stack is detached, but the tabs should be interactable with the usual `Super`+ `Left`/`Right` shortcut, and clicking.

**Comment by hojjatabdollahi** [comment]
@mmstick I see. I changed the title since this is intended.  `super`+`Left`/`Right` doesn't work for me. Also if you resize the stacked window (increase the size) the tabs take a long time to fit the new size. While the tab size is adjusting, closing one window doesn't remove it's tab, and doesn't return keyboard focus to the other window.

**Comment by Drakulix** [comment]
>  super+Left/Right doesn't work for me.

Yes this is not implemented. In general stacks haven't been tested as much in floating mode.

Thanks for raising this issue and feel free to collect further problems with floating stacks. I'll refer this issue once I get around to address all of this (most likely right after finishing up the current work on the "swap-window" mode/shortcut).

**Comment by Drakulix** [comment]
Latest master should improve the resize performance, but the stack header itself might still take longer to settle into a new size. The latter is still being investigated, but currently blocked on a libcosmic update, which will change parts of the code anyhow. I'll keep this issue updated.

Other missing stack-features (like shortcuts not working on floating stacks) are independent from this change and are being worked on.
