### ISSUE TITLE
support screensavers and lock-screens

### ISSUE THREAD

**Issue by jokeyrhyme** [pop-os/cosmic-comp#166]
Howdie, thanks so much for sharing this project! It's astounding to me just how much is already working, great job! <3

I understand that this is pre-alpha , so this isn't a bug report, I just wanted to submit an issue here to track progress relating to screensavers and lock-screens

I assume this will probably involve implementing the [ext-session-lock-v1](https://wayland.app/protocols/ext-session-lock-v1) wayland protocol or perhaps some custom protocol

It looks like work was started on implementing this in upstream smithay, but the PR was abandoned: https://github.com/Smithay/smithay/pull/1019

**Comment by Drakulix** [comment]
This will turn on to be a two-part issue.

For our official lockscreen solution for the whole COSMIC DE, we are looking into doing it via some deeper integration with a custom display manager. This is by no means set in stone (so take this with a grain of salt), but we expect this to help with multiple things architecturally, e.g. integrating locking the users session via systemd-homed, user-switching and more.

That said, we want cosmic-comp to be compatible with the wider ecosystem and allow customization of this aspect of the desktop. So `ext-session-lock-v1`-support is on our radar, but it isn't clear yet at which point we will sink time into implementing it.

It might turn out, that `ext-session-lock` is a much easier solution short-term for our alpha/beta releases to support any lock-screen. It might also happen that our solution materializes much quicker than expected and `ext-session-lock` support will become a less prioritized feature.

That said, contributions regarding support of this protocol to smithay or (afterwards) cosmic-comp are always welcome and will be reviewed and (potentially) merged in a timely manner. I am also happy to mentor on how to best implement said parts, if anyone wants to turn this proposal into reality more quickly.

**Comment by ids1024** [comment]
ext-session-lock is a relatively simple protocol, so especially since a lot of the work has already been done in https://github.com/Smithay/smithay/pull/1019, it probably isn't that hard to add.
