### ISSUE TITLE
Stacks: closing an x11 app closes the entire stack

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-comp#169]
- Create a stack with two terminals (tested w/ alacritty) and one electron app (tested w/ Mattermost, Slack and Todoist).
- Use Super + Q to close the electron app
- All windows in the stack close

**Comment by ids1024** [comment]
Looks like I see the same issue with `xterm`, so this is an issue XWayland support.

**Comment by mmstick** [comment]
Happens with VS Code windows. Must move them out of the stack before closing them.

**Comment by Drakulix** [comment]
Fixed in https://github.com/pop-os/cosmic-comp/commit/8038034a62d97ae9ef094610019946aefa93d9ef
