### ISSUE TITLE
Key bindings sometimes stop working

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#17]
I'm not sure how exactly to figure out what's causing this, but after running cosmic-comp for a while, I sometimes am no longer able to switch workspaces. Super+num just types the number into the current window.

**Comment by Drakulix** [comment]
Maybe the Super key gets stuck somehow? Maybe by swapping focus while holding it or something like that? (Just an educated guess, I did not check the code.)

**Comment by ids1024** [comment]
Using cosmic-comp for several days now, I haven't been seeing this behavior for a while. So it appears to be resolved?

Closing.

**Comment by ids1024** [comment]
Re-opening, since I seem to occasionally see this.

**Comment by ids1024** [comment]
Huh, I see this currently, and wev shows `Mod2` as a locked modifier?
