### ISSUE TITLE
Default monitor configuration has monitors spaced apart; unable to move cursor between them

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#18]
Trying `cosmic-comp` with multiple monitors, I was unable to move my cursor to another display. In `wdisplays`, the monitors were positioned vertically with spaces between them. Adjusting to a layout that had them touching allows moving the cursor between monitors.

Not sure what the default layout comes from (and if it may be confused by a 1080p monitor and 2 1440p, if this issue doesn't always happen), but we'll have to think about the best default behavior here.

**Comment by Drakulix** [comment]
Default configurations should never be created with spaces, if cosmic-comp generates those, that is a bug and needs to be fixed.

**Comment by Drakulix** [comment]
Fixed in https://github.com/pop-os/cosmic-comp/pull/25
