### ISSUE TITLE
Maximize: Unmaximize a previously floating window with double click does not restore the windows previous size

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-comp#181]
Tested with Inkscape and Gedit

- Set window size
- Maximize by double clicking the header
- Unmaximize by double clicking the header

**Comment by Drakulix** [comment]
Fixed in https://github.com/pop-os/cosmic-comp/pull/194/commits/5b7efa3a8b213d9edcd18c78437af346ff226994
