### ISSUE TITLE
Recording screen is missing mouse cursor and can't select monitor

### ISSUE THREAD

**Issue by ryzendew** [pop-os/cosmic-comp#185]
when recording with OBS using screen share pipe wire you cannot select the monitor you want to record and the mouse is not recorded.

https://github.com/pop-os/cosmic-comp/assets/84041391/237282d2-078c-4d7d-beee-31187cb9c388

**Comment by Drakulix** [comment]
This is a know bug of [xdg-desktop-portal-cosmic](https://github.com/pop-os/xdg-desktop-portal-cosmic), which currently provides no UI to select any sources and always using shm-copies, which should perform better (so there is definitely some bug fixing in cosmic-comp to be done), but really should be using dmabuf for copying.

**Comment by ids1024** [comment]
Yeah, I still need to add proper support in xdg-desktop-portal-cosmic to negotiate dmabuf and modifiers for pipewire clients that support dmabufs.

**Comment by RyzenDew** [comment]
> Yeah, I still need to add proper support in xdg-desktop-portal-cosmic to negotiate dmabuf and modifiers for pipewire clients that support dmabufs.

good to know i can't wait to do weekly updates when it's worked out

**Comment by ids1024** [comment]
https://github.com/pop-os/xdg-desktop-portal-cosmic now has support for negotiating dmabuf capture with clients that support it. Though it may not work perfectly.

**Comment by RyzenDew** [comment]
Issue is not fixed i did testing today

**Comment by gabriele2000** [comment]
> Issue is not fixed i did testing today

Same here, using hybrid GPU mode on a laptop, iGPU Intel HD 630 and dGPU Nvidia GTX 1050TI

**Comment by RyzenDew** [comment]
This is still an issue sadly

**Comment by ids1024** [comment]
There's still more to do, but https://github.com/pop-os/xdg-desktop-portal-cosmic/pull/20 should improve some performance issues.

**Comment by gabriele2000** [comment]
> There's still more to do, but [pop-os/xdg-desktop-portal-cosmic#20](https://github.com/pop-os/xdg-desktop-portal-cosmic/pull/20) should improve some performance issues.

[COSMIC - Test new pipewire recording improvements.webm](https://github.com/pop-os/cosmic-comp/assets/12186181/08be257b-2369-4898-b435-3ed4fb965da2)
VERY NICE!
Finally the issue of "exponentially degradation" of performance is fixed, at least for me.

You did an awesome job!

**Comment by RyzenDew** [comment]
https://github.com/pop-os/cosmic-comp/assets/84041391/ca94ff03-0635-4084-8e43-d8f6dff6db8b
one last issue i can't select my display i want and my mouse is not shown in obs when recording but yes the performance issue is solved!

**Comment by gabriele2000** [comment]
Today I shared my screen (well, there wasn't really another option since the only option was "let the system choose") on Microsoft Teams during a call, and the other person saw everything perfectly, I had no performance issues and apart from one time when the image got stuck (I restarted the screen sharing and that fixed the issue) I had no issues.

**Comment by RyzenDew** [comment]
> Today I shared my screen (well, there wasn't really another option since the only option was "let the system choose") on Microsoft Teams during a call, and the other person saw everything perfectly, I had no performance issues and apart from one time when the image got stuck (I restarted the screen sharing and that fixed the issue) I had no issues.

that is another issue thanks for reminding me : OBS also gets stuck when recording sometimes!

**Comment by gabriele2000** [comment]
> that is another issue thanks for reminding me : OBS also gets stuck when recording sometimes!

Not only OBS, if you use Pipewire to record or stream it'll get stuck eventually.
Maybe there's even a timeframe that we could find... my bet is "5 minutes and the issue arises".

Programs that I've tried so far, all with the "pipewire gets stuck" issue:
- Firefox with Micro$oft Teamz
- Telegram Desktop while screensharing

**Comment by ids1024** [comment]
Interesting. I've mostly tested it over shorter time frames (though probably more than 5 minutes). Not sure what would cause that, but I can try running a screen capture client for longer, and see if I can reproduce it.

**Comment by ryzendew** [comment]
i still can't select other screens on obs

**Comment by ryzendew** [comment]
![screenshot-2024-04-30-23-06-44](https://github.com/pop-os/cosmic-comp/assets/84041391/90ad2e30-371d-48da-9113-99973cca2a41)
Update the mouse is now showing but buggy at best but monitors still can't be selected

**Comment by Drakulix** [comment]
Cursor issue is tracked here: https://github.com/Smithay/smithay/issues/1378

Missing monitor selection is an `xdg-desktop-portal-cosmic` issue (it is missing a selection dialog).

**Comment by ryzendew** [comment]
All fixed thanks
