### ISSUE TITLE
Do not suspend on laptop lid close when external monitors are connected

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#19]
It seems the needs to be handled by using the `Inhibit` method on `org.freedesktop.login1.Manager` as is done by gnome-settings-daemon: https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/blob/master/plugins/power/gsd-power-manager.c.

**Comment by Drakulix** [comment]
I thought this is handled by setting `HandleLidSwitchDocked` to `ignore` in [logind.conf](https://www.freedesktop.org/software/systemd/man/logind.conf.html). By forcing this behaviour through `Inhibit` there seems to be no way for the user to disable that, except for disable all Inhibit-calls using `LidSwitchIgnoreInhibited`.

**Comment by ids1024** [comment]
I think desktops like Gnome generally have their own configuration for these sorts of things rather than relying on logind's configuration file. As mentioned in that man page:

> A different application may disable logind's handling of system power and sleep keys and the lid switch by taking a low-level inhibitor lock ("handle-power-key", "handle-suspend-key", "handle-hibernate-key", "handle-lid-switch", "handle-reboot-key"). This is most commonly used by graphical desktop environments to take over suspend and hibernation handling, and to use their own configuration mechanisms. If a low-level inhibitor lock is taken, logind will not take any action when that key or switch is triggered and the Handle*= settings are irrelevant.

Though what gnome-settings-daemon is doing is a bit different since it seems to set and unset the inhibitor instead of just inhibiting and handling this itself. And I don't see a gsetting related to this, so I guess it's not configurable on Gnome?

Though in that case, I wonder why I saw it suspending with external monitors plugged in...

**Comment by Drakulix** [comment]
Ok, in that case is cosmic-comp the "correct" component to hold that inhibitor-lock? Or could this also be done e.g. by cosmic-session? I assume cosmic-comp could play a role here, because it is using logind to obtain privileges to take over devices, but does the inhibitor-lock depend on these privileges or could any process set that?

**Comment by XV-02** [comment]
We appear to have resolved this. Testing from current master build ( 849882a7db8b3d753a4f14410090c691f614e868 ) I seek my system correctly suspend without an external display, while it does not suspend when I have an external display attached.
