### ISSUE TITLE
Rendering issues after #186

### ISSUE THREAD

**Issue by PixelDoted** [pop-os/cosmic-comp#190]
after #186 was merged the primary display is frozen,  
alacritty and wdisplays will render once (then never again),
and closing all windows then opening a window seems to freeze the secondary display

I've tried resetting all configs,  
running cosmic-comp standalone (`make install-bare-session`),  
and running cosmic-comp in a window (which works. `target/release/cosmic-comp`)

Input works even when the both displays are frozen

**Comment by mmstick** [comment]
May be fixed by 184d7662d46fc2c76143b6673c59502c36866fc3

**Comment by Drakulix** [comment]
Only partially fixed, more work is underway.

(Also it is not advised to run latest master. Use the versions linked on github.com/pop-os/cosmic-epoch for a semi-stable experience.)
