### ISSUE TITLE
Can't present full-screen in LibreOffice Impress

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-comp#195]
LibreOffice Impress just presents in a window on the display where its main window is located, regardless of the settings being set to fullscreen and which display is selected to present on. (With some combinations of settings, this leads to only a presenter view opening and not actually presenting anywhere; with other settings, I can at least get a window for the presentation, but non presenter view in those cases.)

Checked this on master c32b8d3 and ws-refactor cf7980f (this issue is not caused by the ws-refactor change, as far as I can tell from testing.)

**Comment by Drakulix** [comment]
Fixed in https://github.com/pop-os/cosmic-comp/pull/194/commits/64143e75e70aef9c164c3821c63fe8a26786a148
