### ISSUE TITLE
kiosk / single-command mode to replace cage as compositor for cosmic-greeter

### ISSUE THREAD

**Issue by jokeyrhyme** [pop-os/cosmic-comp#213]
Howdie, thanks so much for sharing this project! <3

I noticed that cosmic-greeter currently uses `cage` as its compositor ( https://github.com/pop-os/cosmic-greeter/blob/8a9d83632e1c56fe82f211550d6cfd2768af92a2/cosmic-greeter.toml#L5 ) and wondered if eventually `cosmic-comp` would fill that role or if perhaps a different component would be responsible?

**Comment by Drakulix** [comment]
More an issue for `cosmic-greeter` or `cosmic-epoch`. Short answer: Not decided yet.
