### ISSUE TITLE
Layer Surfaces Remain after Application Exits

### ISSUE THREAD

**Issue by wash2** [pop-os/cosmic-comp#219]
I've noticed while working on changes to the panel and other applications which use a layer surface lately that if I kill the application, the layer surface remains. This can steal focus if the app library exits while it has a layer surface, which forces me to switch to TTY and kill the compositor.

## To Reproduce
I run `sleep 5 && killall cosmic-app-library` then activate the shortcut for the app library and wait for it to exit. After it exits, the layer surface is still visible and continues to hold onto focus.

**Comment by Drakulix** [comment]
Likely a weird nvidia bug, that got fixed in recent driver versions.. (please reopen, if this appears again)
