### ISSUE TITLE
Flood of `ConfigureNotify` events in X11 applications

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#232]
This can easily be seen by running `xev`.

`cosmic-comp` calls `X11Surface::configure` in a few places. It seems the one causing this is in `CosmicSurface::send_configure`, verified by commenting it out and no longer seeing unnecessary configure events. Though I haven't narrowed it down more than that.

**Comment by Drakulix** [comment]
Looking at, I am not even sure, why we do send this. I feel like `force_configure` is enough and should be used in places - like configure_request - where we need to be sure to acknowledge new state.

**Comment by Drakulix** [comment]
Addressed by https://github.com/pop-os/cosmic-comp/pull/233
