### ISSUE TITLE
compositor settings

### ISSUE THREAD

**Issue by daktras420** [pop-os/cosmic-comp#237]
how do we setup two displays of different resolutions to mirror mode?
how do we change screen resolutions?

**Comment by Drakulix** [comment]
You can use the tool `wdisplays` (recommended) to setup your displays or manually edit `.local/state/cosmic-comp/outputs.ron` (not recommended).

In the future more configuration (including screen configuration) will be available in `cosmic-settings`.

Mirror mode is not available at this time.
