### ISSUE TITLE
Cursor freeze when touching right or bottom screen edge while dragging a window

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-comp#240]
When the cursor touches the right or bottom screen edge while dragging a window, the cursor and window stop moving, regardless of input, until the mouse button is released.
The top and left screen edges behave normally.

This was tested on a single monitor setup.

**Comment by wiiznokes** [comment]
I have the same issue on 2 differents pc

**Comment by Drakulix** [comment]
I can definitely reproduce this and will look into it once time permits.
