### ISSUE TITLE
panic in cosmic-comp @ 6eb8b82 when launching flatpak apps with wayland socket permission

### ISSUE THREAD

**Issue by jokeyrhyme** [pop-os/cosmic-comp#247]
Howdie, thanks for sharing this project! I'm so excited! <3

I've just been preparing a PR to bump the git submodules over in cosmic-epoch, and I've noticed that I don't seem to be able to launch Firefox (in flatpak) or Chrome (in flatpak)

GNOME Clocks works, and so does alacritty, so it's not all apps

I haven't narrowed it down to whether or not it's flatpak, but I do have a stack trace:

```
Dec 16 16:46:15 HOSTNAME systemd[4874]: Started app-flatpak-org.mozilla.firefox-8278.scope.
Dec 16 16:46:15 HOSTNAME cosmic-comp[7530]: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value': src/backend/kms/socket.rs:53
                                               0: <backtrace::capture::Backtrace as core::default::Default>::default
                                               1: log_panics::Config::install_panic_hook::{{closure}}
                                               2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
                                                         at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
                                                  std::panicking::rust_panic_with_hook
                                                         at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
                                               3: std::panicking::begin_panic_handler::{{closure}}
                                                         at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:580:13
                                               4: std::sys_common::backtrace::__rust_end_short_backtrace
                                                         at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
                                               5: rust_begin_unwind
                                                         at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
                                               6: core::panicking::panic_fmt
                                                         at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
                                               7: core::panicking::panic
                                                         at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:117:5
                                               8: cosmic_comp::backend::kms::socket::<impl cosmic_comp::state::State>::create_socket::{{closure}}
                                               9: <wayland_server::global::GlobalData<I,U,D> as wayland_backend::sys::server::GlobalHandler<D>>::can_view
                                              10: <unknown>
                                              11: <unknown>
                                              12: <unknown>
                                              13: ffi_call
                                              14: <unknown>
                                              15: <unknown>
                                              16: wl_event_loop_dispatch
                                              17: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events
                                              18: cosmic_comp::main
                                              19: std::sys_common::backtrace::__rust_begin_short_backtrace
                                              20: std::rt::lang_start::{{closure}}
                                              21: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
                                                         at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
                                                  std::panicking::try::do_call
                                                         at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
                                                  std::panicking::try
                                                         at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
                                                  std::panic::catch_unwind
                                                         at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
                                                  std::rt::lang_start_internal::{{closure}}
                                                         at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
                                                  std::panicking::try::do_call
                                                         at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
                                                  std::panicking::try
                                                         at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
                                                  std::panic::catch_unwind
                                                         at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
                                                  std::rt::lang_start_internal
                                                         at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
                                              22: main
                                              23: <unknown>
                                              24: __libc_start_main
                                              25: _start
Dec 16 16:46:15 HOSTNAME cosmic-comp[7530]: Failed to clear plane plane::Handle(58) on crtc::Handle(79): DRM access error: Failed to commit on clear_plane on device `Some("/dev/dri/card1")` (Invalid argument (os error 22))
```

That's with this commit: https://github.com/pop-os/cosmic-comp/commit/6eb8b82440e3185462d217a3474a968d50122ceb

And I believe the panic is from the `unwrap()` on this line: https://github.com/pop-os/cosmic-comp/blob/6eb8b82440e3185462d217a3474a968d50122ceb/src/backend/kms/socket.rs#L53

I'm on a fairly recent system with an AMD CPU, AMD iGPU, and AMD dGPU, running Arch Linux

Anyhow, I'm mostly posting this just in case someone else runs into the same thing, and so that I have an issue I can point at from the submodules PR

I understand that COSMIC is pre-alpha, and this might very well be expected for now

**Comment by jokeyrhyme** [comment]
Okay, I tried out this cosmic-epoch commit again: https://github.com/pop-os/cosmic-epoch/commit/cd1027177289d90643950f7dfd68780f174891a7

That has a submodule reference to https://github.com/pop-os/cosmic-comp/commit/f6ea7fa81d1befa2c74af62a1037036cbfa49f15

Anyhow, that does launch, and can run Firefox in flatpak, helvum in flatpak, Minecraft in flatpak, GNOME Console, GNOME Clocks, etc without the panic

I'll try a few more cosmic-epoch commits in a sort of bisect and see if I can work it out

**Comment by jokeyrhyme** [comment]
I just tried https://github.com/pop-os/cosmic-epoch/commit/e67428f88aee9e7ab5d0fe7c63ab62063a4e35c1 which has a submodule reference to https://github.com/pop-os/cosmic-comp/commits/db3e372b8f81f174513b4a9f82a876d267d0145c

That's also completely fine here, hmmm....

**Comment by jokeyrhyme** [comment]
I tried https://github.com/pop-os/cosmic-epoch/commit/543abf1386fc1ba0d96bfb370d3358bf8b5e0436 which references https://github.com/pop-os/cosmic-comp/commit/809eeafa6d9760039934eedb3e7942bdc72384e3 and that's also completely fine

I'm starting to wonder if I imagined the panic somehow...

**Comment by jokeyrhyme** [comment]
I just tried https://github.com/pop-os/cosmic-epoch/commit/4fd53f72e455498b610c15ce47a596ba1faa135b which references https://github.com/pop-os/cosmic-comp/commit/b33c1dc9f77462e732fa452d5655f3b51ad4127a

I can once again reproduce the crash with Firefox in flatpak (same stack trace as in the original report)

Although, Element in flatpak and Discord in flatpak do work fine, so it's not a problem that is specific to flatpaks

**Comment by jokeyrhyme** [comment]
Okay, after playing around with this a bit, I can get Firefox in flatpak and Chrome in flatpak to work without crashing the entire compositor, but only if I block their wayland socket permissions in flatpak, e.g. `flatpak override --nosocket=wayland --user org.mozilla.firefox`

This does cause them to run in Xwayland mode which is a downside, but the upside is they don't cause cosmic-comp to crash

Separately, I tried cleaning up the nVidia vulkan drivers on my system (leftovers from an old experiment, I don't have an nVidia GPU in there at all now), and I also tried disabling the AMD iGPU, and neither of these had any effect

**Comment by Drakulix** [comment]
So far I haven't been able to replicate this, but that might just be, because my packages are not recent enough.

My theory is, that this is a subtle error in our security-context implementation, that is now triggered by the latest version of flatpak making use of that protocol.
Can you try this branch and see, if that fixes it? https://github.com/pop-os/cosmic-comp/pull/250

**Comment by jokeyrhyme** [comment]
@Drakulix yep, amazing

I can confirm that this patch resolves the issue

Firefox-in-flatpak loads just fine now when it had permission to access the wayland socket, with flatpak 1.15.6

**Comment by jokeyrhyme** [comment]
This was broken in epoch even prior to my chore PR

But I'll update my chore PR to carry this latest commit :)

**Comment by jokeyrhyme** [comment]
Fixed by https://github.com/pop-os/cosmic-comp/pull/250

And epoch PR updated to include this: https://github.com/pop-os/cosmic-epoch/pull/158
