### ISSUE TITLE
Fullscreen applications launch windowed. 

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-comp#252]
In COSMIC, I'm seeing application that should be launching full-screen instead launching in windows. In my case, I'm seeing this with Focuswriter. 

If I launch Focuswriter using the Launcher, there is a high incidence of Focuswriter launching in a window. This seems more prevalent on a 3rd gen i5 system I tested than on a 12th gen i7 system I also looked at. If I launch from the command line, the application seems to successfully launch in fullscreen every time. 

On a related note, other members of QA reported seeing issues with games not correctly launching fullscreen. I tested that using two separate games I have through Steam. The first was Dwarf Fortress, which launched successfully every time. The second was Stellaris, which failed every time to launch correctly. 

I'm uncertain what the best debug procedure is for this, so let me know if you would like me to try and create these issues in a specific way for diagnostic purposes.

**Comment by Drakulix** [comment]
I have created a pull request here, that does fix an issue with Xwayland apps being fullscreen on launch: https://github.com/pop-os/cosmic-comp/pull/265

This likely impacts a lot of games, though I don't have any of the listed ones to try.

Furthermore, I have been unable to reproduce the issue with FocusWriter on my system. The app is wayland-native, at least the flatpak version I am using.

Could you confirm, that focus writer is a wayland app on your system as well? Also are you using flatpak or packaged version? Do both versions trigger the issue?

**Comment by XV-02** [comment]
I'll check both. I generally use the packaged version where available, so I'll make sure to check the flatpak first.
