### ISSUE TITLE
Upper half of stack tabs not clickable when a non-libcosmic app is active

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-comp#272]
When a libcosmic app is the currently active one in a window stack, clicking on the upper half (or lower half) of any stack tab switches to that app.
However, when a non-libcosmic app is active (e.g. Firefox, Nautilus...), clicks on the upper halves of tabs don't register (including the tabs of libcosmic apps) and only the lower half works, so switching between apps in a window stack with a mouse requires careful aiming.

**Comment by Drakulix** [comment]
Should be addressed as part of https://github.com/pop-os/cosmic-comp/pull/273
