### ISSUE TITLE
architecture: should all systemd interaction be moved over to cosmic-session?

### ISSUE THREAD

**Issue by jokeyrhyme** [pop-os/cosmic-comp#275]
- `cosmic-comp` inserts DISPLAY and WAYLAND_DISPLAY environment variables into the user service manager (systemd) here: https://github.com/pop-os/cosmic-comp/blob/f75d89b4240fb25f6e43443efd18f95c8484a620/src/systemd.rs
- `cosmic-comp` also sends these values to `cosmic-session` here: https://github.com/pop-os/cosmic-comp/blob/f75d89b4240fb25f6e43443efd18f95c8484a620/src/session.rs#L75-L103
- once https://github.com/pop-os/cosmic-session/pull/31 is completed and merged ( :crossed_fingers: ), `cosmic-session` will insert the XDG_SESSION_TYPE environment variable into the user service manager (systemd) after receiving the DISPLAY and WAYLAND_DISPLAY values from `cosmic-comp`
- should all interaction with `systemd` in COSMIC be moved over into `cosmic-session` so that no other components have to be aware that `systemd` exists and is running?
- if so, is all `logind` interaction also the responsibility of `cosmic-session`? as this may mean `cosmic-comp` has to communicate user idleness/activity to `cosmic-session` so that `cosmic-session` is responsible for locking the session per https://github.com/pop-os/cosmic-comp/issues/166

**Comment by Drakulix** [comment]
> should all systemd interaction be moved over to cosmic-session?

No. cosmic-comp is a component, that can work on it's own or in other contexts/sessions.

For that reason it is useful, that cosmic-comp can notify systemd as well as inject these variables into the user session.

Additionally logind cannot be moved to cosmic-session without lots of refactoring, as it is used to open devices the compositors needs.

**Comment by jokeyrhyme** [comment]
Gotcha, thanks, makes sense :)
