### ISSUE TITLE
Closing Xwayland sticky windows causes cosmic-comp crash

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-comp#277]
When an Xwayland app (e.g. VLC, Wireshark...) is set as a sticky window, closing the app often causes cosmic-comp to crash and be restarted.
````
ERROR launch_pad: process ' COSMIC_SESSION_SOCK=12 cosmic-comp ' terminated with signal 6
 WARN cosmic_session::comp: cosmic-comp exited by signal
````

**Comment by Drakulix** [comment]
Thanks for reporting, I will try to reproduce.
Do you have a stack trace by chance? (Requires launching cosmic-comp with `RUST_BACKTRACE=1`.)

**Comment by git-f0x** [comment]
I'm not sure how to run an app inside cosmic-comp, since running it from a terminal just opens a window titled 'Smithay'.

Running cosmic-session from terminal in GNOME doesn't seem to render XWayland apps inside cosmic-session correctly and the issue isn't reproducible.

I captured the output in the comment by going to a tty, launching cosmic-session, reproducing the issue, then logging out from cosmic-session and taking a photo of the output in the tty.

**Comment by git-f0x** [comment]
Here's the output in a file, now that I've figured out how:
[comp.txt](https://github.com/pop-os/cosmic-comp/files/14449879/comp.txt)
This was when running `RUST_BACKTRACE=1 cosmic-comp` from a tty and launching Firefox with the mentioned environment variable and setting it as a sticky window, then closing it.

**Comment by Drakulix** [comment]
Sadly your logs still don't contain a proper backtrace.

Nevertheless I was able to reproduce a crash with Wireshark, which should be fixed by dcf1fce28aee0a7c14f2b27a1a32f81dd7f494f5. Can you still reproduce this issue with a build containing that commit?

**Comment by git-f0x** [comment]
Seems to be fixed!

Do you have any tips as to how to get a proper backtrace in the future?

**Comment by git-f0x** [comment]
I did capture both stdout and stderr, so I imagine it would be best to clone the repo, build debug, and then get a backtrace with that binary.
Anyways, thank you for the fix!
