### ISSUE TITLE
Mouse input for app components outside window borders doesn't register

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-comp#280]
If an application running through Xwayland has a drop-down menu long enough to go outside window borders, any menu items beyond the border aren't clickable.
In the image below, the last selectable item is **SMB**.
![Screenshot_2024-01-17_22-59-29](https://github.com/pop-os/cosmic-comp/assets/150025636/902cda7f-9f8d-4bde-92c9-6e56fb84707e)

In the case of a non-resizable window being added to a stack (manually), any tabs (or parts of tabs) outside the border (active hint) aren't clickable and all windows in the stack become non-resizable while that window is in the stack.
![Screenshot_2024-01-17_23-01-12](https://github.com/pop-os/cosmic-comp/assets/150025636/9bf2e98f-9358-4334-835c-72797ba22775)

When dragging a scroll bar with a mouse, if the cursor leaves the window borders while scrolling, the scrolling is stopped, and when the cursor returns, the scroll bar jumps to the ingress point. This also happens in a maximized window (e.g. Firefox) when the cursor touches the right screen edge while dragging the scroll bar.

P.S. Unrelated to this but in the case it wasn't noticed, left-clicking on the stack symbol in the upper-left corner of a floating **non-sticky** stack makes the stack disappear and the apps stay open in the background.

**Comment by git-f0x** [comment]
After some more testing, it seems the drop-down menu issue is exclusive to Xwayland apps, and after testing with that branch (running the built binary from a tty), the behavior remains the same.
The non-resizable window in a stack issue seems to persist, just that sometimes clicking on the tabs outside causes the entire stack to shrink and become unresizable.
Scrolling behavior is also the same. It would be nice if it behaved in the same way as COSMIC GNOME (when a scroll bar is being held, the scrolling follows the cursor regardless of its position on the screen).

**Comment by Drakulix** [comment]
> After some more testing, it seems the drop-down menu issue is exclusive to Xwayland apps, and after testing with that branch (running the built binary from a tty), the behavior remains the same.

That this is exclusive to Xwayland apps is a very useful hints. Thanks I will further look into all the issues you listed. I had just fixed some behaviour with popups overlapping on that PR, but probably missed parts special to Xwayland.

**Comment by git-f0x** [comment]
Yeah, I tested with Firefox (by pressing Alt to reveal menu options) and Inkscape, by shrinking the window, and all menu options were selectable.
Running Firefox with `MOZ_ENABLE_WAYLAND=0` makes the menu options outside the window unselectable.
Just in case it wasn't clear, the other issues (non-resizable window in stack, etc.) aren't exclusive to Xwayland.

**Comment by git-f0x** [comment]
Seems to be fixed!

**Comment by git-f0x** [comment]
Not sure if I should close this since the main part is fixed, but the others are present.

**Comment by git-f0x** [comment]
The scrolling now behaves wonderfully! Should I close this issue and open a separate one for the stack issues?

**Comment by Drakulix** [comment]
> The scrolling now behaves wonderfully! Should I close this issue and open a separate one for the stack issues?

Yes please, while I do have the remaining problems on my todo list, it is always confusing to find this issue again to look it up, due to the tile.

**Comment by git-f0x** [comment]
Yeah, sorry about that (the title is completely unrelated :sweat_smile:).
