### ISSUE TITLE
Keyboard layout set in `xkb-config` doesn't get loaded until I open and save `xkb-config` manually

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-comp#285]
I've been setting my keyboard layout to Dvorak in `.config/cosmic/com.system76.CosmicComp/v1/xkb-config` with the following line:
```
(rules:"",model:"",layout:"us",variant:"dvorak",options:Some("altwin:swap_alt_win,caps:ctrl_modifier,compose:ralt"))
```

Fairly recently, I noticed that my keyboard was reverting to Qwerty after reboots. I also discovered that opening `xkb-config` in `nano` and simply writing the file without making changes re-activated my hipster layout.

**Comment by leviport** [comment]
I forgot to add that I also recreated this issue on a fresh COSMIC DE install on a lab unit, and without all of the `options:` in the line above. I was suspicious that those might have been messing something up, but they do not appear to be a the cause.

**Comment by ids1024** [comment]
https://github.com/pop-os/cosmic-comp/pull/254 renamed the setting to `xkb_config` so it could be used with `CosmicConfigEntry`, which assumes that naming. But it seems it was renamed in one place but not the other, so it was loading `xkb_config` at startup and then watching for changes in `xkb-config`.

It would be good to have config work in a more statically typed way to prevent that sort of discrepancy, but anyway, https://github.com/pop-os/cosmic-comp/pull/286 should fix the inconsistency.
