### ISSUE TITLE
[lemp10] Right-click with touchpad doesn't work

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-comp#29]
Version: [d493b90](https://github.com/pop-os/cosmic-comp/commit/d493b9067c45e304649cf9cba07f0077f1253fee)

On lemp10 running with Wayland, two-finger click does not right-click within apps (e.g. Nautilus or Firefox). Right-click with a USB mouse does work.

Three-finger click for middle click also does not work; middle-clicking with a USB mouse works.

(I'm making an educated guess this is the correct repo for an input issue like this, feel free to transfer if not.)

**Comment by PolyMeilex** [comment]
Sounds like a lack of `libinput`'s [ClickMethod::Clickfinger](https://docs.rs/input/latest/input/enum.ClickMethod.html#)

I suppose setting it with [Device::config_click_set_method](https://docs.rs/input/latest/input/struct.Device.html#method.config_click_set_method) would do the job.

**Comment by Drakulix** [comment]
This is more a lack of a configuration-utility (so [cosmic-settings](https://github.com/pop-os/cosmic-settings), than an issue for cosmic-comp. Though cosmic-comp currently lacks a way to configure this at runtime (the configuration is currently only read once on launch).

There is already a config file at `{XDG_STATE_DIR}/cosmic-comp/inputs.ron` (on my system that is `~/.local/state/cosmic-comp/inputs.ron`, that get populated with default settings on the first run.

Here you should be able to find your touchpad and set `click_method` to `Some(Clickfinger)` to enable two-finger right click.
@jacobgkau Can you confirm that works for your system?

**Comment by jacobgkau** [comment]
I have `~/.local/state/cosmic-comp/inputs.ron` and there are two `click_method` lines (one for `PNP0C50::00 04F3:311D Touchpad` and one for `ETPS/2 Elantech Touchpad`). Both were set to `Some(ButtonAreas)` by default.

Changing them both to `Some(Clickfinger)` doesn't seem to work; I tried logging out and back in, then rebooting, and while my changes to the file were preserved, the touchpad still right-clicks with the bottom right and not with two-finger click.

**Comment by Drakulix** [comment]
Hmm, that is weird, it does work on my system..
Is there anything in your logs by chance? Otherwise I will have to add some more debug-printing for applying the input configuration.

**Comment by jacobgkau** [comment]
Here is journalctl after booting and trying to right-click a couple of times: [journalctl.txt](https://github.com/pop-os/cosmic-comp/files/9284730/journalctl.txt)

Also, here is my config file in case I did something wrong or there's something else I need to change: [inputs.ron.txt](https://github.com/pop-os/cosmic-comp/files/9284737/inputs.ron.txt)

**Comment by Drakulix** [comment]
Thanks, that was helpful, I cannot reproduce that locally with your settings.
