### ISSUE TITLE
Floating window jumps and flashes while resizing on an external display [pang12]

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-comp#297]
https://github.com/pop-os/cosmic-comp/assets/3430283/95bc19b0-a7a9-4058-acd7-e1f73435a1df

**Comment by leviport** [comment]
This is what I see on my Oryx, both on the internal display, and an external. But mine only does that if I resize by dragging the top or left edge. Dragging the bottom or right edges resizes as I would expect.

**Comment by WatchMkr** [comment]
You're right! We now see it happening on the pang12, your Oryx and my Darter. On my Darter it happens on the internal display but not an external display via DP.

**Comment by Drakulix** [comment]
Fixed by https://github.com/pop-os/cosmic-comp/commit/21483b8d41aeea3f4eac919201117eea0e00c8f0
