### ISSUE TITLE
Window snapping for floating windows

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-comp#298]
When tiling is disabled on a workspace (or if a window is just floated), we should be able to drag a window to the left edge of the screen to snap it to the left half of the screen, and drag it to the right edge to snap to the right half. It would also be nice to be able to snap to quarters by dragging into the edge near corners of the screen. Finally, dragging to the top edge of the screen should maximize the window. GNOME (including old COSMIC), Plasma, MATE, and Windows all support basic snapping like this.

Some of the other DEs that support this remember the window's size before they were snapped, and restore that size when moving the window out of the snapped position. Personally, that's not as important to me as the initial snapping is (aside from the case of maximizing, when un-maximizing should make the window smaller again).

Tagging @pop-os/ux in case there needs to be a discussion about if/how snapping should work. I have seen at least one user (in https://github.com/pop-os/cosmic-comp/issues/262) talking about how they sometimes have to fight the snapping gestures, so those people might appreciate a setting to disable it.

**Comment by ryanabx** [comment]
Should have been fixed, we can close this issue!

**Comment by jlaustill** [comment]
For those interested in **keyboard shortcuts** for window snapping (in addition to the mouse-based snapping that was implemented), there are now PRs that add this functionality:

- cosmic-settings-daemon: https://github.com/pop-os/cosmic-settings-daemon/pull/124
- cosmic-comp: https://github.com/pop-os/cosmic-comp/pull/2009

This adds a `TileWindow(TilingZone)` action with 8 zones: `Top`, `TopRight`, `Right`, `BottomRight`, `Bottom`, `BottomLeft`, `Left`, `TopLeft` - allowing users to configure keyboard shortcuts to snap floating windows to screen edges and corners.
