### ISSUE TITLE
Drop-down menus in GIMP offset

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-comp#311]
**Version:** d1aac38

In GIMP, the drop-down menus are displaying with a vertical offset from where they should start:

![screenshot-2024-02-14-22-30-35](https://github.com/pop-os/cosmic-comp/assets/7199422/43cb0809-a026-4d0b-bcbe-6136cc1cc9a4)

If I move my mouse cursor into that empty space between where I clicked and where the menu visually starts, menu items get highlighted as if I'm already hovering over it. (Input within the menu is offset from where my cursor actually is.)

Sort of related to https://github.com/pop-os/cosmic-comp/issues/143.

**Comment by Drakulix** [comment]
Can't seem to reproduce, neither with the current Pop!_OS packaged version, nor the flathub beta in either wayland or x11 mode. Is this still an issue with the latest commit?

**Comment by WatchMkr** [comment]
I'm able to reproduce this by opening an image in GIMP. The menu are in the correct place before the image is opened. The menu positions are correct after moving the window.

**Comment by Drakulix** [comment]
Fixed by 62afa4cf61b1230e346d3100b11b003ad409a3ed
