### ISSUE TITLE
Activate click on tap when using a touchpad

### ISSUE THREAD

**Issue by wiiznokes** [pop-os/cosmic-comp#312]
Is there a way to activate it ? I hope this will be the default in the future, this is a little frustrating when testing cosmic on a laptop.

**Comment by senntore** [comment]
I want to know as well. I know it will be default when the alpha is release but it would be nice we can have any workaround for it right now.

**Comment by senntore** [comment]
@Drakulix Thanks! It seems to work with that config.

**Comment by senntore** [comment]
Though while testing it a bit more, I found out this doesn't work with cosmic-greeter right now.

**Comment by Drakulix** [comment]
> Though while testing it a bit more, I found out this doesn't work with cosmic-greeter right now.

cosmic-greeter has it's own user account and doesn't load settings for one specific user.

So to override this you need to change `/var/lib/cosmic-greeter/.config/cosmic...`. (At least on Pop!_OS that should be the location of the user's home.)

**Comment by wiiznokes** [comment]
> You can edit .config/cosmic/com.system76.CosmicComp/v1/input-touchpad in the meantime.

unfortunately, this doesn't work on my machine.
