### ISSUE TITLE
Larger-than-screen initial window size on >100% scaling for applications

### ISSUE THREAD

**Issue by ryanabx** [pop-os/cosmic-comp#314]
This is what firefox looks like on launch:
![screenshot-2024-02-18-08-33-41](https://github.com/pop-os/cosmic-comp/assets/56272643/e4888b54-e5f3-4de0-aa8e-ced02c19c5f0)

This is what visual studio code looks like on launch:
![screenshot-2024-02-18-08-35-13](https://github.com/pop-os/cosmic-comp/assets/56272643/43bf6773-48ea-406f-82b5-d5408d8c1397)

This is while using 150% scaling on a 1920x1080p display that's around 13.5" size.

This is the same launch of visual studio code, but on 100% scale:
![screenshot-2024-02-18-08-37-52](https://github.com/pop-os/cosmic-comp/assets/56272643/0d56697c-bc7e-4987-8c46-15147129ce7d)

**Comment by Drakulix** [comment]
Should be fixed by https://github.com/pop-os/cosmic-comp/commit/a8846ed2b893579b86cb0073553537dade74a44c
