### ISSUE TITLE
Disabling and re-enabling monitor in wdisplays, it doesn't display anything again

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#33]
This happens with the internal monitor on Dev One, or on external monitors, but in that case disconnecting and reconnecting the monitor causes it to set the display mode again.

Unless it's a weird issue involving Amd graphics, or such, this should be easy to reproduce.

**Comment by Drakulix** [comment]
Should be fixed by https://github.com/pop-os/cosmic-comp/commit/9611dcd496c7c26606eda8258f31d9e925030db0 .

Some left over state caused the re-enabled surface to never queue a new render.

**Comment by ids1024** [comment]
Yep, seems to work well now.
