### ISSUE TITLE
Tiled GTK apps have incorrect mouse positioning

### ISSUE THREAD

**Issue by jackpot51** [pop-os/cosmic-comp#330]
Recently (perhaps related to either #328 or #319), GTK applications when tiled will offset the cursor up and to the left. I'm assuming some calculation is incorrect when tiled, because when floating clicks go to the right place.

**Comment by ids1024** [comment]
I was just bisecting this after noticing this in Firefox.

It seems https://github.com/pop-os/cosmic-comp/commit/70a0aa8da35f86c4340313eb8d2c8fb13886e6cf is responsible. I'm testing now with that reverted, and it seems to work fine.
