### ISSUE TITLE
Compositor crash xwayland sticky window

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-comp#336]
On a Slack huddle video call using the app with the mini-window outside of the app. Mini-window set to sticky. Crash occurred resizing the mini-window.

[cosmic-comp-crash-resize-slack-huddle-withvideo-sticky-window.log](https://github.com/pop-os/cosmic-comp/files/14515871/cosmic-comp-crash-resize-slack-huddle-withvideo-sticky-window.log)

**Comment by jackpot51** [comment]
Panic here: https://github.com/pop-os/cosmic-comp/blob/master/src/xwayland.rs#L324

**Comment by Drakulix** [comment]
Should be fixed by https://github.com/pop-os/cosmic-comp/commit/36b759ea18ba3283dd12b5e97e84c3e5db628748
