### ISSUE TITLE
Drag regions: drag window to top to maximize and left/right to snap to sides

### ISSUE THREAD

**Issue by ryanabx** [pop-os/cosmic-comp#340]
If a window is dragged to the top of the screen, it'd be nice to have it maximize.

If a window is dragged to the far left or right, it should snap to the left half or right half of the screen.

If it's not too hard to implement I could take a look at doing this. Some guidance on where to start would be nice though

**Comment by WatchMkr** [comment]
The keyboard version of this is implemented. In floating mode use Super + Shift and arrows to move a window to the top, bottom, corners, or sides. 

The tricky part with mouse is getting the right resistance before moving the window to the next display in multi-display setups. I think this needs design. We haven't defined target regions and pulling a window to the top should offer to half tile at top, then maximize, then potentially move to a display above so there needs to be hints for the user.
