### ISSUE TITLE
Question: XWayland and Nvidia explicit-sync

### ISSUE THREAD

**Issue by gabriele2000** [pop-os/cosmic-comp#343]
Explicit-sync is being worked on and it's closer and closer to being ready in Wayland.
Driver-side it's maybe coming in a year, knowing how slow Nvidia is with updates, all for fixing a single bug.

So, once the protocol is ready, will you guys provide this patch in Smithay or something?

**Comment by ryanabx** [comment]
https://github.com/Smithay/smithay/pull/1356

**Comment by gabriele2000** [comment]
> [Smithay/smithay#1356](https://github.com/Smithay/smithay/pull/1356)

"So far just exposes the protocol but doesn't do anything"
Does that mean that it won't make changes or am I too tired to understand this? ahaha

**Comment by WatchMkr** [comment]
The nvidia driver that can use this feature will be released soon. We're working to finish our PR with support. I'm closing this question to clean-up issues.
