### ISSUE TITLE
bug: Crash when opening multiple windows.

### ISSUE THREAD

**Issue by edfloreshz** [pop-os/cosmic-comp#353]
I was just goofing around and started opening lots of COSMIC Files windows and the compositor crashed.

Steps to reproduce:
1. Open COSMIC Files.
2. Spawn 50+ windows.

[Log](https://github.com/pop-os/cosmic-comp/files/14561970/log.txt)
```
Mar 11 08:55:14 pop-os cosmic-session[36683]: got environmental variables from cosmic-comp: [("WAYLAND_DISPLAY", "wayland-1"), ("DISPLAY", ":0")]
Mar 11 08:55:30 pop-os cosmic-session[36683]: process ' COSMIC_SESSION_SOCK=12 cosmic-comp ' failed with code 1
Mar 11 08:55:30 pop-os cosmic-session[36683]: cosmic-comp exited with error code 1
Mar 11 08:55:30 pop-os cosmic-session[36683]: sleeping for 7ms before restarting process cosmic-comp (restart 0)
Mar 11 08:55:30 pop-os cosmic-session[36683]: restarted process ' COSMIC_SESSION_SOCK=12 cosmic-comp ', now at 1 restarts
Mar 11 08:55:32 pop-os cosmic-session[36683]: starting process ' COSMIC_SESSION_SOCK=12 cosmic-comp '
```

**Comment by Drakulix** [comment]
No stack trace, so unclear what caused this.

Can reproduce, though only when using tiled layout and no stacks, eventually the window sized becomes smaller than <1px, which causes a crash.

**Comment by edfloreshz** [comment]
I'm using the windowed mode, I tried using `RUST_BACKTRACE=1 cosmic-session` and that log file is what I got, how can I get a log that would be useful to you?

**Comment by Drakulix** [comment]
> I'm using the windowed mode, I tried using `RUST_BACKTRACE=1 cosmic-session` and that log file is what I got, how can I get a log that would be useful to you?

You need to use a debug-build of cosmic-comp, so build from the repository to get proper backtraces.

**Comment by git-f0x** [comment]
Here's the output from a debug build of cosmic-comp with `RUST_BACKTRACE=1 cosmic-comp 2>&1 >comp.log`:
[comp.log](https://github.com/pop-os/cosmic-comp/files/14669599/comp.log)

**Comment by Drakulix** [comment]
Too many open files. Sounds like either a file descriptor leak in smithay or a very low global file limit.

**Comment by git-f0x** [comment]
Also may be of note, I ran this from a tty, and the program didn't end after the crash (the tty was displayed). I waited a bit and did Ctrl + C in the end.

**Comment by git-f0x** [comment]
I separated stdout and stderr, since there seems to be some additional info in stderr `RUST_BACKTRACE=full cosmic-comp >comp_out.log 2>comp_err.log`:
[comp_out.log](https://github.com/pop-os/cosmic-comp/files/14670365/comp_out.log)
[comp_err.log](https://github.com/pop-os/cosmic-comp/files/14670368/comp_err.log)

**Comment by git-f0x** [comment]
I can't seem to reproduce a crash by opening many nautilus windows. Everything just gets kind of laggy and then all nautilus windows disappear. If a stack trace of this would be helpful, let me know.

**Comment by git-f0x** [comment]
I think this is fixed. Tested by opening an ungodly amount of `cosmic-term` windows until both RAM and VRAM were full.

**Comment by edfloreshz** [comment]
Yup, I can confirm the same, I'm gonna close this issue.
