### ISSUE TITLE
Gap between multiple monitors configured with cosmic

### ISSUE THREAD

**Issue by wezm** [pop-os/cosmic-comp#357]
This seems similar to #18 

I built COSMIC from the cosmic-epoch repo via the AUR package. Specifically [cosmic-epoch 5f2fd33](https://github.com/pop-os/cosmic-epoch/commit/5f2fd3324b997142fa10c8170fd6b53feb5f2673), which has cosmic-comp [d1aac38](https://github.com/pop-os/cosmic-comp/tree/d1aac380fff5447a14fa1fc1023ea1078c0226a4). I'm aware this isn't the head of the repo but I skimmed the commits since this one and didn't see any that were immediately relevant.

I have two 24-inch 4K displays that I use with 2x (200%) scaling both connected to a single GPU via DisplayPort. The one on the right is rotated into a portrait orientation. I configured the displays in the cosmic settings to match the physical layout but was unable to get my cursor on to the the secondary (rotated) display.

Please excuse the screen photos, I tried cosmic-screenshot, grim, and gnome-screenshot and none of them would take a screenshot.

This is how I laid out the screens in the COSMIC settings (each display is set to 200% scaling):

![IMG_7283](https://github.com/pop-os/cosmic-comp/assets/21787/27a69ed7-6b7b-4084-809e-7b664069a969)

This is what `wdisplay` shows:

![IMG_7282](https://github.com/pop-os/cosmic-comp/assets/21787/c5b0bc22-2fa7-4ac6-b8f4-5ccf8e1a869a)

**Comment by Drakulix** [comment]
I think this is more a cosmic-settings issue, possibly also cosmic-randr, but in any case thanks for reporting.

cc @mmstick. Looking at the wdisplays screenshot, the two rectangles there should touch each other, but they are approximately one width of DP-1 apart, so likely cosmic-settings isn't taking the scaling into account, when updating the position.

**Comment by Drakulix** [comment]
> Please excuse the screen photos, I tried cosmic-screenshot, grim, and gnome-screenshot and none of them would take a screenshot.

Sounds like the xdg-desktop-portal-cosmic isn't running for some reason on your machine btw.

**Comment by wezm** [comment]
> Sounds like the xdg-desktop-portal-cosmic isn't running for some reason on your machine btw.

That sounds likely. I started the session from a console with `start-cosmic`.

**Comment by WatchMkr** [comment]
We're tracking display arrangement issues [here](https://github.com/pop-os/cosmic-settings/issues/296).
