### ISSUE TITLE
Panic when xkb configuration is wrong

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#36]
```
xkbcommon: ERROR: Couldn't find file "symbols/en" in include paths
xkbcommon: ERROR: 1 include paths searched:
xkbcommon: ERROR:       /usr/share/X11/xkb
xkbcommon: ERROR: 3 include paths could not be added:
xkbcommon: ERROR:       /home/ian/.config/xkb
xkbcommon: ERROR:       /home/ian/.xkb
xkbcommon: ERROR:       /etc/xkb
xkbcommon: ERROR: Abandoning symbols file "(unnamed)"
xkbcommon: ERROR: Failed to compile xkb_symbols
xkbcommon: ERROR: Failed to compile keymap
[...]
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/input/mod.rs:187:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This should probably be handled more gracefully, perhaps defaulting to something that should work (as long as the necessary xkb data files exist at all).

**Comment by Drakulix** [comment]
Where exactly does this crash happen?

On current master, the result of `add_keyboard` is simply [ignored](https://github.com/pop-os/cosmic-comp/blob/master_jammy/src/input/mod.rs#L127).
It is definitely very debatable, if that is a proper solution, but I fear this back trace might be a bit old?
