### ISSUE TITLE
Games use lowest Hz of 2 monitors

### ISSUE THREAD

**Issue by tobygethin** [pop-os/cosmic-comp#360]
I have 2 monitors, one that is 60hz and another that is 144hz when playing games like Counter Strike 2 or Halo Infinite the game only sees my 144hz monitor has 60hz and it feels like 60hz not 144hz.

When I unplug the 60hz monitor and log out and in again the games properly see that my monitor is 144hz.

**Comment by Drakulix** [comment]
Should be fixed with https://github.com/pop-os/cosmic-comp/commit/f1d8225ddbbace0ea3690fe3b489b9974a1dddeb.

Please note that some driver bugs might prevent you from reaching 144hz, when a nvidia gpu is enabled.

**Comment by tobygethin** [comment]
I've just tested it and looks like it wasn't fixed with https://github.com/pop-os/cosmic-comp/commit/f1d8225ddbbace0ea3690fe3b489b9974a1dddeb.

Still seeing 60hz in CS 2.

**Comment by tobygethin** [comment]
Just tested it again and it looks seems fine, I can see correct refresh rate in CS 2.
