### ISSUE TITLE
mouse can move but not clickable

### ISSUE THREAD

**Issue by sparkwj** [pop-os/cosmic-comp#362]
environment: macbook pro 5,5, pop os 22.04, xwayland with nouveau driver
using macbook built-in touchpad can move the mouse pointer, item can be highlight but not clickable / tap-able, keyboard is ok, i tried a config that mentioned in #312 by @Drakulix, but not work

**Comment by Drakulix** [comment]
Pretty sure, this needs `tab-to-click` to properly work. I'll make sure this will be the default in the future.

**Comment by WatchMkr** [comment]
tracked [here](https://github.com/pop-os/cosmic-settings/issues/254)
