### ISSUE TITLE
Short gray screen when moving to lower-numbered horizotal workspace

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-comp#363]
When moving to a lower-numbered workspace (e.g. 2 -> 1) with the keyboard or the workspaces applet, and **Workspaces Orientation** is set to horizontal, the animation displays a gray blank workspace instead of the workspace being switched to, during its duration.
Once the animation is finished, the workspace is displayed properly.

~~Also something that might not be intended:
Horizontal workspaces can be switched between with Super + Ctrl + ↑/↓ in addition to ←/→, while vertical workspaces can only be switched with ↑/↓.~~

**Comment by Drakulix** [comment]
> Horizontal workspaces can be switched between with Super + Ctrl + ↑/↓ in addition to ←/→, while vertical workspaces can only be switched with ↑/↓.

Do you have multiple monitors set up?

**Comment by git-f0x** [comment]
No, this is on a single monitor setup.

**Comment by ryanabx** [comment]
I have the same issue. One monitor as well.

**Comment by git-f0x** [comment]
Horizontal workspaces no longer switch with ↑/↓. Not sure if related to recent updates, or if I might have been using cosmic-greeter last time.

**Comment by ryanabx** [comment]
They should switch with left and right gestures/keys

**Comment by git-f0x** [comment]
Yes, but previously for me they switched with both. Which was a bug caused by something (maybe logging in with cosmic-greeter).

**Comment by flukejones** [comment]
It appears that when the blank happens it only refreshes on mouse cursor movement.

**Comment by git-f0x** [comment]
I don't need to move the cursor for the blank screen to switch to displaying properly on my end.

**Comment by ryanabx** [comment]
> It appears that when the blank happens it only refreshes on mouse cursor movement.

> I don't need to move the cursor for the blank screen to switch to displaying properly on my end.

I have the same behavior as fluke on my end, but it sometimes refreshes without needing to refresh the cursor. I wonder if it has to do with some kind of internal content refresh.

**Comment by git-f0x** [comment]
So on your ends, when going back with e.g. Super+left arrow, the gray screen stays there until the cursor is moved?

**Comment by ryanabx** [comment]
> So on your ends, when going back with e.g. Super+left arrow, the gray screen stays there until the cursor is moved?

I usually use the touchpad gestures, haven't tested with Super + left arrow. That might be the difference

**Comment by git-f0x** [comment]
Yeah, I don't have a trackpad to test with so it might be that.

**Comment by rikvanloenhout** [comment]
I'm having the same issue my laptop (no external monitors), it occurs with both keyboard shortcuts and touchpad gestures on my machine (built from source on the 8th of May). When using the keyboard shortcut, the workspace redraws around the time the animation is finished. When using a touchpad gesture, the workspace stays gray until the first mouse movement.

![screenshot-2024-05-09-08-19-44](https://github.com/pop-os/cosmic-comp/assets/17786457/27aa890d-7d24-4722-9448-f400400cfd8d)

**Comment by mohammedbilalns** [comment]
![sdf](https://github.com/pop-os/cosmic-comp/assets/70318383/64e363e0-dce0-419c-bd82-eb60a4bf55bb)
The same issue happens to me too. When switching to lower workspaces through touchpad gestures, a gray screen appears. It only disappears when I move the mouse or touchpad. When switching to lower workspaces through keyboard shortcuts, the same thing happens, but the gray screen only flashes and then returns to normal. Interestingly, when switching workspaces through touchpad gestures while screen recording, the gray screen doesn't stay; it fades away, just like with the keyboard shortcut (I think it takes some more time than the keyboard shortcut to disappear)

**Comment by Drakulix** [comment]
Fixed by https://github.com/pop-os/cosmic-comp/commit/06c12040f91aa8a6d56f171dd76de584bccdb0e3
