### ISSUE TITLE
Cursor can slow right down sometimes (laggy, slow framerate)

### ISSUE THREAD

**Issue by Quackdoc** [pop-os/cosmic-comp#367]
Sometimes the cursor can slow down, and im not too sure what is causing it. I believe it to usually be due to cpu usage but here are the times I have experienced a slow low framerate cursor

* High cpu usage; Compiling applications: Reliably repeatable
* Using firefox: Moderately repeatable, hard to make it occur on purpose
** Switching tabs can sometimes fix this, Playing a video can sometimes fix it. It's just very sporadic. Some tabs it can reliably happen on are;
** Discord: moderately high repeatability, Google, Github, Element: low repeatability
* Dissent (GTK4 discord app in go): Rare but I have had it occur at least 6 times
* MPV: very rare, only happened once that I remeber. 

As some additional notes, the mouse cursor is **usually** only laggy when hovering over the apps in question when it is app specific issues, however sometimes the apps in question need to be closed to fix the issues as slow cursor can persist when not hovering over the application

**Comment by ryanabx** [comment]
What is your hardware like?

**Comment by Ilandriel** [comment]
I have practically the same thing. Tested Epoch a few days ago.
I'm wondering if this is something to do with Nvidia.

Hardware:

CPU: i7 6700
GPU: Nvidia RTX 2060
RAM: 32 GB

**Comment by ids1024** [comment]
I know PRIME performance has been kind of slow for Nvidia+Intel with Turing cards like that. But Gnome Shell also seems to have that issue.

**Comment by Quackdoc** [comment]
Im currently using Intel Arc A380. I have an rx580 in the second gpu slot but all apps are running on the intel GPU. I can test the radeon gpu if it would help

**Comment by Shinyzenith** [comment]
I seem to be facing this issue too. I have a NVIDIA MX110 + Intel i5 integrated graphics. cosmic-comp seems to be running on my nvidia card as per nvtop. I'm currently on my other machine so I don't have the exact logs / version info.

I am willing to attempt to write a fix if the maintainers can kindly share some insight into possible fixes / things to look into.

**Comment by Shinyzenith** [comment]
I can confirm that db27fa483d0a56d4bb650235d4116d52b00f35de is the commit causing the issue. Reverting to 96518a9f292eda2d00aa9007e7142c99d9b69b4f seems to resolve the issue.

Another thing to note is that on db27fa483d0a56d4bb650235d4116d52b00f35de the entire monitors refresh rate seems to be not match the one of 96518a9f292eda2d00aa9007e7142c99d9b69b4f. In db27fa483d0a56d4bb650235d4116d52b00f35de it's ~30Hz where as 96518a9f292eda2d00aa9007e7142c99d9b69b4f operates at 60Hz.

**Comment by Drakulix** [comment]
> I can confirm that [db27fa4](https://github.com/pop-os/cosmic-comp/commit/db27fa483d0a56d4bb650235d4116d52b00f35de) is the commit causing the issue. Reverting to [96518a9](https://github.com/pop-os/cosmic-comp/commit/96518a9f292eda2d00aa9007e7142c99d9b69b4f) seems to resolve the issue.
> 
> Another thing to note is that on [db27fa4](https://github.com/pop-os/cosmic-comp/commit/db27fa483d0a56d4bb650235d4116d52b00f35de) the entire monitors refresh rate seems to be not match the one of [96518a9](https://github.com/pop-os/cosmic-comp/commit/96518a9f292eda2d00aa9007e7142c99d9b69b4f). In [db27fa4](https://github.com/pop-os/cosmic-comp/commit/db27fa483d0a56d4bb650235d4116d52b00f35de) it's ~30Hz where as [96518a9](https://github.com/pop-os/cosmic-comp/commit/96518a9f292eda2d00aa9007e7142c99d9b69b4f) operates at 60Hz.

Pushed a commit that should fix the half-vsync framerate issue in my testing: https://github.com/pop-os/cosmic-comp/commit/f1d8225ddbbace0ea3690fe3b489b9974a1dddeb

**Comment by Shinyzenith** [comment]
I see you disabled it all together but any clues as to why including screencopy time being added to the frame time estimation is causing this?

**Comment by Drakulix** [comment]
> I see you disabled it all together but any clues as to why including screencopy time being added to the frame time estimation is causing this?

That is not the issue, in fact the commit in question removed the screencopy time. The issue is, that our prediction is too inaccurate to account for multiple things currently:

- Multiple monitors. Since everything runs on one thread (bound to be changed eventually), the time would need to take the render time (and timing) of other outputs into account (which it doesn't do)
- Driver bugs. We are employing a bunch of very slow operations to work around some driver bugs, most notably introducing a `glFinish` on nvidia GPUs to reduce the typical flickering on wayland problem. That takes longer than our current expected render time, so we overshot and miss the current frame. Increasing the minimal render time would also fix this, but then the prediction also becomes quite useless.

So the solutions are many:
- More accurate time stamping (using gpu data)
- Predicting presentation time instead of relying on vsync callbacks
- Use a thread per output
- etc..

A fix for the glaring nvidia problem is also in the works, but in the meantime disabling the too inaccurate logic is the easiest solution.

**Comment by Quackdoc** [comment]
as of #f1d8225ddbbace0ea3690fe3b489b9974a1dddeb it seems like may issue may be solved? (I'm also running a different kernel, will test old kernel when I can).

Firefox hasn't been laggy, I can compile rust applications like cosmic-applets without my cursor becoming stuttery. I won't close the issue ticket yet until further testing is done, and perhaps @Ilandriel could also test the latest commits? 

But short of running [compositor killer](https://github.com/ascent12/compositor-killer) I can't get the cursor to lag at all, and well, everything struggles with compositor killer.

**Comment by Elias-Graf** [comment]
I'm on cosmic via the nix flake, and the mouse gets laggy quite a lot (but sometimes it's fine). I have observed, that the CPU usages spikes from `cosmic-comp` spikes to 9% from 0.3% when the lag is happening. As soon as I stop moving the mouse, it drops back to normal levels.
