### ISSUE TITLE
XWayland issues while changing workspace with a fullscreen game open and blank games

### ISSUE THREAD

**Issue by gabriele2000** [pop-os/cosmic-comp#383]
Just gonna copy-paste this from [here](https://github.com/pop-os/cosmic-comp/issues/316#issuecomment-2019822468) since it's a separate issue even if it's similar (not related to Cyberpunk 2077)

- Here's the log of journalctl 
[journalctl.log](https://github.com/pop-os/cosmic-comp/files/14754908/journalctl.log)

- First issue: The Crew 1 is just a black screen since yesterday's update to cosmic- packages [Video 1](https://youtu.be/A50kTFik9HA)

- Second issue: Switching workspaces or doing something remotely related to changing focus leads to the first issue [Video 2](https://youtu.be/0PReL5F2VG8)

Context on the first issue:
Proton's FSR patch, using FSHack, makes the game render at whatever resolution you want, then the game's DPI are scaled as if you were using the native resolution of your screen.

I use 720p that FSR will upscale at 1080p.
That leads to the game loading then quickly resizing the window or something like that, you can see a quickly changing window before the game renders (in the second video, in the first video the game just fails to render)

**Comment by Drakulix** [comment]
I wonder if this is somewhat related to https://github.com/pop-os/cosmic-comp/issues/231, given that we are dealing with focus here. Could you try setting `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0` and see if that changes the behaviour in any way?

**Comment by gabriele2000** [comment]
Upon further testing, I don't quite understand the culprit of it.
Some games mess with "stealing focus" or something like that.
There's a unity game that once unfocused it would enter an unrecoverable state, it becomes a blank screen, but it only happens while it's in fullscreen.

This kind of issues puzzles me, since I've been told that "exclusive fullscreen doesn't exist in wayland" and XWayland it an X11 session inside Wayland (that means that the parent session doesn't have fullscreen).

So... what?!

**Comment by Drakulix** [comment]
Should be fixed with https://github.com/pop-os/cosmic-comp/pull/603
