### ISSUE TITLE
Shortcut: Hold Super+Click and drag anywhere in a window to move the window

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-comp#384]

**Comment by 16hournaps** [comment]
This is such a core user experience feature that I am surprised to find it in Alpha 2. Think about it like this: how many times a person drags a window during a session? 100? 200? I think majority will not use shortcuts to compose windows around, instead hunting for window headers will be a pain. I dont know how hard it is tech-wise. 

Sorry for already writing "feedback" before even alpha 1, just wanted to throw it out there. 

I had 3 things that would stop me from trying alpha 1, but 2 of them (https://github.com/orgs/pop-os/projects/23/views/1?filterQuery=%2B&pane=issue&itemId=40645264, https://github.com/pop-os/cosmic-settings/issues/9) are getting fixed right now, so surprised to find this one here.

**Comment by Quackdoc** [comment]
Expanding on this, Right click to resize would also be greatly appreciated, I find it quite hard to line my mouse up correctly since I have shaky hands.

@16hournaps Looks like the PR mentioned could be tested
