### ISSUE TITLE
Alacritty / sctk-adwaita not getting pointer input in floating mode

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#385]
It seems this is a regression caused by https://github.com/pop-os/cosmic-comp/pull/380.

While tiled, clicking on the close button in Alacritty works correctly. But while floating, the pointer input seems to go to the main surface instead.

**Comment by git-f0x** [comment]
I've noticed that an area along the top and left edges (width around half of window header) in GTK apps isn't clickable while floating. The cursor also often doesn't switch back to its default icon when going past the right or bottom edges (stays using the resize indicator icon).
