### ISSUE TITLE
%100 CPU usage when swiping between workspaces

### ISSUE THREAD

**Issue by hojjatabdollahi** [pop-os/cosmic-comp#391]
If you do the 4 finger swipe to change the workspaces, but stop in the middle (so that you can see both workspaces) the CPU usage maximizes.

**Comment by Drakulix** [comment]
Most likely caused by the shell considering this state an on-going animation (which causes it to frequently schedule new frames, even when nothing new visually is happening).

**Comment by Drakulix** [comment]
Looks like this was it. Thanks for catching!

**Comment by hojjatabdollahi** [comment]
Thank you. It is indeed fixed.
