### ISSUE TITLE
xwayland apps not clickable

### ISSUE THREAD

**Issue by wiiznokes** [pop-os/cosmic-comp#397]
I noticed that after some time, vs code become not clickable, at least some part of the windows. This happen in both floating and tilling.
It's only the bottom left part that is not clickable.
Curiously, the bug seems to appears only when the window is on the left side of my screen.

**Comment by wiiznokes** [comment]
Maybe it only with nvidia driver, i don't have this issue on my laptop

**Comment by ryanabx** [comment]
Nope, I'm not running nvidia

**Comment by mmstick** [comment]
You have to unstack and restack XWayland windows when they do this.

**Comment by wiiznokes** [comment]
> You have to unstack and restack XWayland windows when they do this.

That don't fix it for me

**Comment by mmstick** [comment]
Here's a workaround for VS Code to enable Wayland support.

1. Copy VS Code's `code.desktop` file your your home folder

```
mkdir -p ~/.local/share/applications
cp /usr/share/applications/code.desktop ~/.local/share/applications/
```

2. Edit the `Exec` line to the following

```
Exec=/usr/share/code/code --enable-features=UseOzonePlatform --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto --unity-launch %F
```

3. Create an alias for code in your `~/.bashrc`

```
alias code='code --enable-features=UseOzonePlatform --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto'
```
