### ISSUE TITLE
enabling full-screen in Minecraft's settings (flatpak) makes it almost completely non-responsive

### ISSUE THREAD

**Issue by jokeyrhyme** [pop-os/cosmic-comp#398]
Howdie, thanks for sharing this project! <3

I've started mucking about with games to see what does and doesn't work, and it's impressive just how much does work at this stage without any problems

I did notice some weirdness with Minecraft

- Minecraft flatpak: https://flathub.org/en-GB/apps/com.mojang.Minecraft
- this version of `cosmic-comp` with tiling enabled: https://github.com/pop-os/cosmic-comp/commit/3da08ed22dd4ae7607b5c9fc0bed7bf80d7b48d7

steps to reproduce

1. start a world in Minecraft and play
2. Escape to settings menu, Video settings, enable full-screen
3. observe that game seems to minimise
4. try to click on game icon in the dock, and observe that the game flashes open and then minimises again
5. with some persistence (actually not sure what I did here) keep trying to restore focus to Minecraft
6. once Minecraft is open again and has focus, observe that mouse hover effects in the settings menu are slow to respond, and navigating around the settings menu is very slow / non-responsive
7. with some care, navigate settings menu and disable full-screen
8. observe that everything is back to normal and very playable and smooth

- [ ] try to reproduce this in another smithay-based compositor
- [x] try to reproduce this in a wlroots-based compositor: no weird behaviour under sway version 1.9 :heavy_check_mark:  
- [ ] try to reproduce this in GNOME

**Comment by Drakulix** [comment]
Sounds similar to https://github.com/pop-os/cosmic-comp/issues/231

**Comment by jokeyrhyme** [comment]
- [ ] check with tiling mode enabled

The other thread reminded me:

- [ ] check without tiling mode

**Comment by Vixea** [comment]
https://github.com/pop-os/cosmic-comp/issues/231#issuecomment-2039197921
I think I did that for you but if you wanna do it yourself more power to you

**Comment by Drakulix** [comment]
Should be fixed with https://github.com/pop-os/cosmic-comp/pull/603. Tested toggling fullscreen in minecraft 1.21 though mojang launcher from flathub without any problems.
