### ISSUE TITLE
[Bug] Duplicate cursor/window with multiple monitors scaled differently

### ISSUE THREAD

**Issue by nathansgithub** [pop-os/cosmic-comp#417]
Hopefully this is easily replicable. I have 2 monitors next to each other. I am on Pop!_OS using cosmic-session.

I went into COSMIC Settings and reduced the scale of the display on the left to 50%, and left the right monitor at 100%. 

After that, if the cursor crosses over the middle of the leftmost display, I see it duplicated on the rightmost display. Also, I see the side of the window on the right display if I drag it over the middle of the left display. I also can't click anything on the right display.

**Comment by Drakulix** [comment]
Seems like positioning with scaling (or at least negative scaling) is off. This might be a cosmic-settings issue, can you replicate the same problem with cosmic-randr?

Anyway thanks for the report, will look into this.

**Comment by wash2** [comment]
I've seen this happen when two displays overlap after changing the scaling. I assume their positions should be changed in cosmic settings so that happen

**Comment by nathansgithub** [comment]
@wash2 That does look like the issue. When I set the one display to 50%, it shows the displays overlapping, but it looks like expected once I drag it into place. And then when I set it back to 100%, the displays are completely disconnected.

**Comment by WatchMkr** [comment]
Tracking [here](https://github.com/pop-os/cosmic-settings/issues/296).
