### ISSUE TITLE
Parts of menus that are over a panel aren't selectable

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-comp#418]
This occurs regardless of panel configuration (other than autohide, since the panel goes away).
If this is more related to cosmic-comp, feel free to move this there.

**Comment by ids1024** [comment]
It would be good if `surface_under` (used for pointer/touch input) and `workspaces_elements` (used for rendering) could share logic for the z-order of all the elements in some way, so they don't have to duplicate that and it can't be inconsistent.

**Comment by vadimk1337** [comment]
"Essentially, this menu in Google Chrome shouldn't go beyond these boundaries at all. Here's a comparison with GNOME. Yes, they should be clickable, of course, but please also look into this bug

![image](https://github.com/user-attachments/assets/2354b045-2ed4-4a6b-b69d-81d83fb51505)
![Screenshot from 2024-09-05 00-23-48](https://github.com/user-attachments/assets/dd0ef2c6-8766-4925-8265-3fcf9bd15708)

**Comment by git-f0x** [comment]
Fixed by #918!
