### ISSUE TITLE
Moving window to another workspace makes it appear in both; closing freezes compositor

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#42]
I'm not sure what circumstances reproduce this, but I've seen it a couple times. (I think the previous time was a while ago.) Maybe related to workspaces moving between displays as a result of hotplug in some way?

**Comment by Drakulix** [comment]
I haven't seen this in a very long time, so without steps to reproduce, this will be quite difficult to debug, I fear.

**Comment by ids1024** [comment]
Yeah. We might be able to find a consistent way to reproduce this, but otherwise it's hard to debug.

**Comment by ids1024** [comment]
Haven't seen this in a while, so I'll assume it's fixed unless it comes up again.
