### ISSUE TITLE
[Feature Request] Implementation of input methods for languages such as Japanese

### ISSUE THREAD

**Issue by moi-cest-matthew** [pop-os/cosmic-comp#426]
While I can now use my European Spanish layout, I cannot select any input methods for languages that require text to be converted, meaning I cannot type in Japanese on COSMIC.

I suspect this is because of Cosmic not being based on any other desktop which already has input method support (none of which would be based on Rust anyways).

Do you have plans to implement COSMIC support for an existing input method, such as GTK-based IBus? If not, are there plans to implement one based on Rust?

**Comment by jacobgkau** [comment]
IMEs will be supported. Fcitix is a better fit for non-GNOME desktops than IBus. There's some discussion in the general cosmic-epoch repo here: https://github.com/pop-os/cosmic-epoch/issues/104

**Comment by Drakulix** [comment]
This is not really a cosmic-comp issue, as cosmic-comp already should have support for the necessary wayland protocols (mainly input-method and text-input). I know @ids1024 had some success running Fcitix in the past already, but the upstream state of these protocols sadly remains in a somewhat problematic state: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/39

That said, this might simply be a configuration issue. Possibly cosmic-session should autostart fcitix (or perhaps we just need xdg-autostart support for it) to make this easier. Closing in favour of the more general issue @jacobgkau already linked.
