### ISSUE TITLE
Shortcut: Hold Super+ Right Click to resize window

### ISSUE THREAD

**Issue by Quackdoc** [pop-os/cosmic-comp#429]
As an appendage to this https://github.com/pop-os/cosmic-comp/issues/384 It would be really nice right click would resize the window, and left click would move the window. It would also be great if the button combination for this could be configured.

**Comment by Drakulix** [comment]
I am not super familiar with this feature on other desktops. Which corner does this usually resize? bottom-right?

**Comment by Quackdoc** [comment]
It is most typically dependent on which quadrant is grabbed in.

**Comment by bartv42** [comment]
See also https://github.com/pop-os/cosmic-epoch/issues/363

**Comment by russelltg** [comment]
Definitely agree with this, use this regularly on sway/hyprland/kde.

**Comment by Drakulix** [comment]
This will be part of alpha 2, if you want to express support for feature requests, please simply use the thumbs-up-reaction.
