### ISSUE TITLE
Plugging in external monitor makes internal monitor go black, but still shows as enabled in wdisplays, has `wl_output`

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#43]
I believe with the way monitor configuration in handled in cosmic-comp, it is expected that the monitor is disabled when I plug in external monitors since I've configured it that way with `wdisplays` previously.

But it doesn't quite work correctly. `wdisplays` shows the output as enabled. It still has a `wl_output` global, and `dmabuf_export` produces an image that shows what was on the screen previously.

Disabling the output in `wdisplays` makes it no longer produce a `wl_output` global, as expected.

**Comment by Drakulix** [comment]
Should be fixed by https://github.com/pop-os/cosmic-comp/pull/46/commits/63a514f19315e2335bc95fa1d2f8e9164145b4c6.

I will keep the issue open until it is in master_jammy though
