### ISSUE TITLE
Bug/regression: focus hint not working anymore

### ISSUE THREAD

**Issue by wiiznokes** [pop-os/cosmic-comp#431]
I think it didn't worked yesterday either. The border of windows doesn't appear anymore

**Comment by git-f0x** [comment]
It works on my end. Are you sure that its size isn't set to 0 in Settings or that it isn't turned off in the tiling applet?

**Comment by wiiznokes** [comment]
It was turned off in the tilling applet indeed. There is no option in the settings app for this, that what confused me i guess
