### ISSUE TITLE
Hardware Cursor isn't visible in games (possible XWayland issue)

### ISSUE THREAD

**Issue by gabriele2000** [pop-os/cosmic-comp#434]
Since, I think, https://github.com/pop-os/cosmic-comp/pull/380 when playing games the cursor (if it's not a software one) doesn't get rendered anymore, making it extremely difficult to navigate menus (in most games it's impossible).

I think https://github.com/pop-os/cosmic-comp/pull/424 fixes this based on pure intuition, but I'm not sure.

I'm using a laptop, nvidia+intel GPU, graphics set in hybrid mode.

**Comment by git-f0x** [comment]
On my end, it is visible, but the cursor is visually stuck in place in fullscreen (and borderless window) games, but things can be interacted with with an invisible cursor.
Though I'm likely using software cursors, since the icon is changed (but it switches back and forth when scrolling).

**Comment by gabriele2000** [comment]
> On my end, it is visible, but the cursor is visually stuck in place in fullscreen (and borderless window) games, but things can be interacted with with an invisible cursor.

That's my whole point.
The cursor that you see is the "last frame" that is likely inside a buffer, or something like that.

The real cursor isn't rendered, most likely due to the new protocol that has been implemented inside cosmic-comp.

The thing about "using software cursor" isn't even something that you can decide in 90% of games, plus hardware cursor is simply superior in everything so it even makes sense.

**Comment by git-f0x** [comment]
While testing this, I discovered that the cursor can be temporarily fixed after launching a fullscreen game by pressing Super + M (which creates the letterboxing mentioned in a separate issue), but shortly afterwards the game freezes (similar to the cursor being stuck), though everything else works (e.g. the game moves diagonally when pressing Super, and allows for other things to be interacted with), and this message is emitted in the logs:
`[GL] GL_INVALID_VALUE in glTexSubImage2D(xoffset 0 + width 24 > 10)`
Not sure if it's helpful, but just in case.

**Comment by Drakulix** [comment]
https://github.com/pop-os/cosmic-comp/pull/603 should now also fix the invisible cursor (though most games still break after minimize).

**Comment by git-f0x** [comment]
Can confirm that it fixes the cursor!
Unrelated to the PR, other things on the same workspace as the game can't be interacted with (e.g. if opening workspaces with a fullscreen game running, clicking on a different app in the overview just switches to displaying a frozen (running in background) game fullscreen, that starts moving after some clicks). Though that's probably related to not being able to view other apps or the App Library over a fullscreen window.

**Comment by Drakulix** [comment]
https://github.com/pop-os/cosmic-comp/pull/603 got merged.
