### ISSUE TITLE
Cursor icon doesn't return to default after dragging text/link/image in Firefox

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#437]
Dragging test/images/etc from the body of a page in Firefox changes the cursor to one indicating a drag. But after the drag ends, the cursor remains stuck showing that image (but the window works normally).

This does not happen when dragging tabs, where the cursor returns to normal.

I'm not sure what Firefox might be doing that's unusual.

**Comment by ids1024** [comment]
This seems to also occur in Anvil. Making `allow_set_cursor` always return true doesn't change it.

So it's an issue somewhere in Smithay, but not based on whether or not `set_cursor` is allowed?

**Comment by WatchMkr** [comment]
I'm still seeing this bug on my laptop and desktop so reopening.

**Comment by WatchMkr** [comment]
Can't reproduce this any longer.
