### ISSUE TITLE
Helldivers 2 black screen and repeated maximizing

### ISSUE THREAD

**Issue by Dekomoro** [pop-os/cosmic-comp#442]
Doesn't seem to matter whether the game is ran in D3D11 or D3D12 modes.

**Comment by onlyreportingissues** [comment]
I think that's not a COSMIC exclusive problem: https://steamcommunity.com/app/553850/discussions/1/4302697675608874759/

**Comment by Dekomoro** [comment]
it happens more often on cosmic however, I've tested comparing it to plasma.

**Comment by Dekomoro** [comment]
I suspect this might be linked to https://github.com/pop-os/cosmic-comp/issues/460
