### ISSUE TITLE
Mouse cursor style defaults to adwaita when using non libcosmic apps

### ISSUE THREAD

**Issue by ryanabx** [pop-os/cosmic-comp#454]
I'm guessing this is not entirely a comp issue, but I didn't know where else to put this.

My guess is that apps will need to be aware of COSMIC's cursor theme, because it's the client's job to present the cursor.

I wonder what the reqs are to make this happen?

**Comment by Drakulix** [comment]
I think this might be something `cosmic-session` might be better equipped to handle. It could read the libcosmic cursor-scheme on load and update `gsettings` or environment variables accordingly before launching everything.

**Comment by ryanabx** [comment]
Turns out, the bug isn't fixed with the PR I made. GTK apps still have the adwaita cursors...

I do know that it's possible to fix this issue by modifying /usr/share/icons/default/index.theme to have a fallback theme to Cosmic instead of Adwaita. Don't know if that's what we want to modify though
