### ISSUE TITLE
[Games] Fullscreen & borderless fullscreen -> blackscreen & stuck cursor image | windowed mode works fine

### ISSUE THREAD

**Issue by onlyreportingissues** [pop-os/cosmic-comp#460]
Windowed mode is responsive, no blackscreen, cursor image moving fine also.

Fullscreen & borderless fullscreen cause some games to show a black screen or the screen is showing, but the visible cursor won't move.

Tested games:
- Gang Beasts (Unity)
- DEVOUR (Unity)
- Gunfire Reborn (Unity)
- Dinkum (Unity)

**Comment by Dekomoro** [comment]
Seems likely it has to do with loss of focus?

I have multiple games that exhibit this issue, but also others that only exhibit this when I move my cursor off the fullscreen game to another monitor. Games that refocus themselves to go fullscreen on launch typically exhibit this issue it appears.

**Comment by onlyreportingissues** [comment]
> Seems likely it has to do with loss of focus?
> 
> I have multiple games that exhibit this issue, but also others that only exhibit this when I move my cursor off the fullscreen game to another monitor. Games that refocus themselves to go fullscreen on launch typically exhibit this issue it appears.

Apparently Unity isn't using proper exclusive fullscreen for some reason: https://www.reddit.com/r/LastEpoch/comments/m7hpgw/has_anyone_figured_out_how_to_force_exclusive/ 

Added this command to a Unity game (without %command%): 
`-window-mode exclusive -screen-fullscreen`
And now the fullscreen window isn't misplaced (idk why it helps on Wayland though).

Also, the cursor seems only to get stuck when it's moving around before the game starts, as shown in this video:

[Video_2024-05-18_16-54-41.webm](https://github.com/pop-os/cosmic-comp/assets/103491514/a5c2c595-75ab-4918-9ac8-b8a20c7a2848)

**Comment by gabriele2000** [comment]
The cursor issue is bugging me a lot, but just know that it happens since cosmic-comp got updated to render the cursor using hardware-acceleration.

You can confirm it using games that only uses software-rendered cursors (like "Splinter Cell: Conviction")

**Comment by Drakulix** [comment]
https://github.com/pop-os/cosmic-comp/pull/603 should have fixed this.
