### ISSUE TITLE
OBS screen recording shows black box around cursor

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-comp#463]
When recording with OBS, a black box shows up around the cursor in both the preview and the recorded video file, even though no black box is present around the cursor on the physical screen.

![mpv-shot0080](https://github.com/pop-os/cosmic-comp/assets/7199422/1fab97c2-3c56-4b3d-82ba-bc96b373795f)

**Comment by jacobgkau** [comment]
This is on version 954aa6e.

I tried to compare the behavior with Jitsi Meet, but it doesn't show the cursor there at all when I share the screen.

**Comment by Drakulix** [comment]
Likely related (listing for keeping track):
- https://github.com/Smithay/smithay/issues/1378
- https://github.com/Smithay/smithay/pull/1381

**Comment by jacobgkau** [comment]
Just adding for triage purposes, I noticed the above-linked issues also affect screenshots of drop-down/pop-over menus:

![screenshot-2024-05-10-16-26-12](https://github.com/pop-os/cosmic-comp/assets/7199422/14a0f1b3-1ab3-4ef9-8222-8f97b0f0c26d)

(I'm assuming that's being caused by the same thing.)

**Comment by Drakulix** [comment]
(Note: That is really cool, because that means cosmic-comp is putting these windows onto overlay planes. Optimizations working, but breaking stuff. XD)

**Comment by Drakulix** [comment]
Fixed upstream and included in cosmic-comp since https://github.com/pop-os/cosmic-comp/commit/b4abc06ad8ea3b0ad6c5a29cbc5e69da8fd2184f

**Comment by wiiznokes** [comment]
I suppose this also close this issue ? https://github.com/pop-os/xdg-desktop-portal-cosmic/issues/38

**Comment by Drakulix** [comment]
> I suppose this also close this issue ? [pop-os/xdg-desktop-portal-cosmic#38](https://github.com/pop-os/xdg-desktop-portal-cosmic/issues/38)

Most likely. Please test though, if you can.

**Comment by wiiznokes** [comment]
Yes, it is
