### ISSUE TITLE
bug: xwayland apps not clickable.

### ISSUE THREAD

**Issue by edfloreshz** [pop-os/cosmic-comp#469]
It looks like xwayland applications, such as Electron apps, currently have clickability issues under COSMIC, which makes them unusable.

Restarting them with Wayland support provides a temporary escape hatch for apps that support this:

```bash
--enable-features=UseOzonePlatform --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto --unity-launch
```

But this should be fixed as many people rely on Electron apps for their daily workflow and are not wiling to modify .desktop files.

Related issues #397

**Comment by ryanabx** [comment]
Adding to this issue, I can't repro reliably, but given a long enough coding session, it's guaranteed to happen to visual studio code. In this state, keyboard input tends to work, but pointer input does not. The only way to fix it is to have a completely new toplevel (either by restarting the app, or in cases of apps with a system tray, closing the window and opening a new one from the system tray)

**Comment by edfloreshz** [comment]
In my case this has become a permanent issue where no xwayland app is clickable unless explicitly launched with the options stated above, so, if there's a need for testing or logs please let me know if I can be of assistance.

**Comment by ryanabx** [comment]
@edfloreshz can you use keyboard input if the app is focused?

**Comment by edfloreshz** [comment]
Nope
