### ISSUE TITLE
Bug: Dragging non-COSMIC apps out of maximized doesn't change titlebar width

### ISSUE THREAD

**Issue by nabrious0** [pop-os/cosmic-comp#470]
Maximizing a window that's not a COSMIC app but uses a COSMIC headerbar (if that's the correct way to describe it) then dragging it out causes the headerbar to keep it's maximized width instead of shrinking.

![image](https://github.com/pop-os/cosmic-comp/assets/162843960/fd86d708-f008-4860-826e-c696b8e51869)

**Comment by WatchMkr** [comment]
Perhaps related https://github.com/pop-os/cosmic-comp/issues/371

**Comment by Drakulix** [comment]
Fixed by https://github.com/pop-os/cosmic-comp/commit/4652a2329417f89c49cdfaf4ad9cd0c4d6ed1c5d
