### ISSUE TITLE
Apps that use cosmic-comp's headerbar are incosistent with the rest of apps

### ISSUE THREAD

**Issue by nabrious0** [pop-os/cosmic-comp#471]
**COSMIC apps have colored window controls (according to system accent color) and when hovering over one, your cursor turns into a pointer.**

![screenshot-2024-05-09-18-40-15](https://github.com/pop-os/cosmic-comp/assets/162843960/836265ac-5993-4fd4-af59-ba9e23dfa456)

**Apps like Discord (Vesktop) or any app that relies on COSMIC's titlebar doesn't follow this (non-colored window control buttons and cursor state does not change on hover)**

![screenshot-2024-05-09-18-41-16](https://github.com/pop-os/cosmic-comp/assets/162843960/e1dd2c80-0cf8-489a-8c23-75f406d33e67)

Also, when dragging a window, on COSMIC or GTK apps your cursor changes into the "Grab" variant, on these apps it does not.

**Comment by Drakulix** [comment]
Most likely cosmic-comp needs an update for it's libcosmic version again to match cosmic apps. Thanks for bringing this to my attention.

**Comment by WatchMkr** [comment]
Here's the header design for reference https://www.figma.com/file/SkAtS5qlVOGQC0n895AHzX/Design-System-(WIP)?node-id=12298-80459&mode=dev

(unfocused libcosmic apps don't currently match the design)

**Comment by Drakulix** [comment]
Partially fixed by https://github.com/pop-os/cosmic-comp/commit/3d58ec062da59add47ad5df705ef09fd680742e5.

Correctly applies libcosmic's stylings now, focused style includes colored icons though, even though the server-side decorations aren't supposed though. This is a libcosmic bug.

**Comment by Drakulix** [comment]
> as of may 26 2025 they are not respecting a custom cursor when one is set up via the workaround

which work around?

**Comment by RainyNyte** [comment]
Manually setting the new theme in /etc/environment and then manually setting the inheritance in the x-cursor-theme file to inherit from the custom theme first then adiwata (the default) second

**Comment by RainyNyte** [comment]
> as of may 26 2025 they are not respecting a custom cursor when one is set up via the workaround

specifically vesktop reverts to the default cursor theme entirely except when hovering the headerbar
