### ISSUE TITLE
Some application windows sometimes don't appear upon launch unless something changes on the screen

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-comp#476]
This one has been difficult to pin down, but I think I finally have steps to recreate it semi-reliably. I'm not certain that it's a compositor bug, so feel free to transfer this issue if it fits better somewhere else. I've seen it happen with other applications, so I'm pretty certain it's not just a cosmic-term  bug.

Steps to reproduce:
- Turn off dock in settings, leaving only the panel active
- Navigate to a fresh workspace with nothing on it
- Launch cosmic-term with the default Super + T shortcut, but quickly release both Super and T
Now, cosmic-term often doesn't appear until I either press a key or move my mouse, at which time cosmic-term appears normally.

As mentioned in the first step, having the dock active makes the bug vanish, and cosmic-term always appears as expected. Also, having an OBS screen capture scene set up makes the bug vanish as well. Since attempting to record the bug makes the bug go away, I'll see if I can get a clear video of it happening with my phone and upload it in this thread.

**Comment by leviport** [comment]
Here's the video:
https://github.com/pop-os/cosmic-comp/assets/13512097/60e87219-8136-40b2-86dc-827d278e7fcb

**Comment by git-f0x** [comment]
I've occasionally encountered a similar issue in different situations (e.g. sometimes when toggling tiling, the layout doesn't show properly until the cursor is moved).
I'd guess the reason for why it works with the dock is that the App Tray is on it. When launching the terminal, the App Tray changes, so it would probably also work with just the panel, if the App Tray was on it.

**Comment by ids1024** [comment]
I've noticed something like this this when testing cosmic-comp outside of cosmic-session (so no panel, etc). I use the launcher to open an application like Firefox, but it doesn't appear until I move the cursor.

**Comment by Drakulix** [comment]
Probably some event is not triggering a re-draw, when it should. Might be difficult to pin down exactly. Does firefox always reproduce this?

**Comment by leviport** [comment]
I noticed the window may also appear when the clock on my panel updates and changes time, so there is at least one case where user input isn't necessary to show the window.

**Comment by ids1024** [comment]
>  Does firefox always reproduce this?

I find it pretty consistently reproducible when starting cosmic-comp on it's own, opening the launcher with a keybinding, and starting firefox. Without moving the cursor.

**Comment by git-f0x** [comment]
I can reproduce it 100% of the time in all apps (that can be launched with a shortcut) if I remove any changing panel components (e.g. App Tray), and there are no other open apps (since the windows switching focus probably triggers a re-draw). Letting go of the Super more slowly when launching an app makes it display after releasing Super.

**Comment by kodo777** [comment]
I can also confirm that this is still happening with all apps.

**Comment by ids1024** [comment]
Debugging this a bit, it seems the problem is at https://github.com/pop-os/cosmic-comp/blob/036ca84829689843f86b50ea30d873b41a73b052/src/wayland/handlers/compositor.rs#L147.

When the window is first opened, `visible_output_for_surface` seems to return `None` here, so a render isn't scheduled. Changing to a loop over `shell.outputs()` fixes this.

Just moving that down a bit in the function to after windows are mapped doesn't seem to fix it...

**Comment by Drakulix** [comment]
> Just moving that down a bit in the function to after windows are mapped doesn't seem to fix it...

That is likely because we return early, if we map a new window: https://github.com/pop-os/cosmic-comp/blob/036ca84829689843f86b50ea30d873b41a73b052/src/wayland/handlers/compositor.rs#L175

Same applies to `map_layer` below.
