### ISSUE TITLE
Compostor segfaults on shm screencopy if file isn't large enough

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#48]
This can be reproduced by modifying https://github.com/pop-os/cosmic-protocols/blob/main/examples/screenshot-screencopy.rs to remove the `set_len` call.

Interestingly attaching too small a buffer to a window also crashes the compositor, but it isn't a segfault; it's a SIGBUS that is caught. So maybe a somewhat different issue? But related: https://github.com/Smithay/smithay/issues/834

(I noticed this again since I was running `screenshot-screencopy` to take a screenshot, wondering why the compositor crashed, then seeing this was the version I had modified to crash the compositor :laughing:.)

**Comment by Drakulix** [comment]
The SIGBUS is expected and should be caught by the shm-handler in smithay. If it is not, that is also a smithay bug.

**Comment by ids1024** [comment]
https://github.com/Smithay/smithay/pull/1475 fixes the segfault, but then it panics in the `.unwrap()` in `submit_buffer`.

A bit awkward since it isn't easy to convert the error here to a `<R as Renderer>::Error`. Or to change the error type to `anyhow` or such.
