### ISSUE TITLE
[Game] Hunt Showdown gets ignored by the compositor (CryEngine V / ProtonGE)

### ISSUE THREAD

**Issue by onlyreportingissues** [pop-os/cosmic-comp#489]
When starting the game, it won't show anywhere (but the sound is playing). There is no window appearing, no app in the app tray is showing up and the workspace overview won't show any window of the game either.

There is a specific gamma issue this game has on Linux, maybe it will cause the same behaviour on COSMIC with other games that share this issue also: https://github.com/doitsujin/dxvk/issues/3291

Related to the linked issue above:

> The gamma slider doesn't work.
> 
> Apparently it's a CRYENGINE thing: https://docs.cryengine.com/display/CRYAUTOGEN/CONSOLEPREFIXR#AnchorRGAMMA
> 
> The gamma is changed at hardware-level only, not software-level. The option is called "r_gamma" in the game.cfg file.

**Comment by gabriele2000** [comment]
Related to https://github.com/pop-os/cosmic-comp/issues/316

Also, "Call of Duty: Ghosts" is one of those "invisible" games.

**Comment by flukejones** [comment]
We can add Wreckfest to this list. Unsure exactly when it started to occur.

My own current system details are:
- Fedora 40
- Nvidia 555.x driver (beta, manual install)
- 6.9.1-200.fc40.x86_64 (kernel)

These all seem to be Xwayland issues?

**Comment by onlyreportingissues** [comment]
> When starting the game, it won't show anywhere (but the sound is playing). There is no window appearing, no app in the app tray is showing up and the workspace overview won't show any window of the game either.
> 
> There is a specific gamma issue this game has on Linux, maybe it will cause the same behaviour on COSMIC with other games that share this issue also: [doitsujin/dxvk#3291](https://github.com/doitsujin/dxvk/issues/3291)
> 
> Related to the linked issue above:
> 
> > The gamma slider doesn't work.
> > Apparently it's a CRYENGINE thing: https://docs.cryengine.com/display/CRYAUTOGEN/CONSOLEPREFIXR#AnchorRGAMMA
> > The gamma is changed at hardware-level only, not software-level. The option is called "r_gamma" in the game.cfg file.

Had to change the resolution on the game.cfg file manually, now Hunt Showdown works in bordered window mode.

**Comment by Drakulix** [comment]
I have neither of these games for testing, can you retest now that https://github.com/pop-os/cosmic-comp/pull/603 is merged, which should have fixed a bunch of issues?

**Comment by flukejones** [comment]
I can confirm that Wreckfest appears to be running well. Mostly? On iGPU output for external it is very very good but on dGPU output for external it seems to have an occasional lag. Almost imperceptible unless you were experiencing smooth and high fps to start with.

**Comment by Drakulix** [comment]
> I can confirm that Wreckfest appears to be running well. Mostly? On iGPU output for external it is very very good but on dGPU output for external it seems to have an occasional lag. Almost imperceptible unless you were experiencing smooth and high fps to start with.

Great, that closes the original issue. There is certainly more optimizations to do for hybrid setups, we will continue to optimize those.
