### ISSUE TITLE
VRR doesn't work

### ISSUE THREAD

**Issue by onlyreportingissues** [pop-os/cosmic-comp#490]
Tested it with the AppImage of this tool in COSMIC and GNOME 46 (to compare & check if it's working): https://github.com/Nixola/VRRTest/releases

VRR can be enabled in GNOME 46 with the command: gsettings set org.gnome.mutter experimental-features "['variable-refresh-rate']"

It will be available in the display settings when clicking on Hz after logging in again. In GNOME it started lagging below 48 Hz on my monitor, above it it run like butter. In COSMIC it stutters also when it is above 48 Hz.

**Comment by onlyreportingissues** [comment]
Apparently there are many issues with VRR and hardware cursor. Maybe this combination also causes many of the other gaming related issues found here?

**Comment by Drakulix** [comment]
VRR is currently not supported, even if exposed by some applications (wdisplays, cosmic-randr).

While cosmic-comp can toggle the required kernel apis, we haven't done any verification of this feature actually working yet, which also includes adding a bunch of workarounds for buggy gpu drivers or multiple vendors.

**Comment by onlyreportingissues** [comment]
> VRR is currently not supported, even if exposed by some applications (wdisplays, cosmic-randr).
> 
> While cosmic-comp can toggle the required kernel apis, we haven't done any verification of this feature actually working yet, which also includes adding a bunch of workarounds for buggy gpu drivers or multiple vendors.

This might be of use when dealing with the RDNA 2 power management problem at some point: https://github.com/Umio-Yasuno/amdgpu-profile-switcher

**Comment by Umio-Yasuno** [comment]
> @onlyreportingissues system76-power already manages amdgpu power profiles

I think `system76-power` doesn't support `pp_power_profile_mode` switching.  
Also, `power_profile` and `power_method` are only supported by radeon driver, not AMDGPU drivers.  

https://github.com/pop-os/system76-power/blob/a546efaf2cba8bd58fd39e14c389c23ef2e91ba9/src/kernel_parameters.rs#L120-L124

Document: https://www.kernel.org/doc/html/latest/gpu/amdgpu/thermal.html#pp-power-profile-mode

**Comment by onlyreportingissues** [comment]
Works now, tested it with Lords of the Fallen. Without VRR the game immediately starts to stutter when FPS drops, but now despite of fluctuating FPS it's smooth as butter.
