### ISSUE TITLE
[REGRESSION][BISECTED]Lockup on some applications drag and drop

### ISSUE THREAD

**Issue by Quackdoc** [pop-os/cosmic-comp#492]
On some applications when doing a drag and drop cosmic-comp will lock up requiring putting the keyboard into XLATE mode to swap tty and kill the compositor (or use SSH). Currently the easiest repro case I have is the ripdrag application, though in gnome filepicker invoked by `zenity --file-selection` and dragging a folder to the favourites will also produce the lockup.

Cosmic-files does not seem to have this issue. 

I plan on bisecting when I find the time, currently on commit dfb3bea

EDIT: the commit dfb3bea was the one that caused an issue

**Comment by atagen** [comment]
any luck tracking this one down? also seeing this on file related drag n drops.

**Comment by Quackdoc** [comment]
Interestingly enough it was that specific commit that caused the issue, not currently able to test current version due to https://github.com/pop-os/cosmic-comp/issues/543

**Comment by Quackdoc** [comment]
I was able to replicate this using chromium too

**Comment by Drakulix** [comment]
Which version of cosmic-comp was this tested on? Recently two deadlocks in wayland-server's rust backend were fixed and updated in cosmic-comp very recently: https://github.com/pop-os/cosmic-comp/commit/989ee95858077aeb0f3e75e44bfeaf607c57f5c3

I can't reproduce this with either nautilus, cosmic-files, chromium or firefox on current master.

**Comment by Quackdoc** [comment]
I tested a commit before that, can confirm that fixed the issue :D
