### ISSUE TITLE
Shortcuts stop working

### ISSUE THREAD

**Issue by wash2** [pop-os/cosmic-comp#50]
Sometimes the configured shortcuts will stop working. For example, I will try [ Super ] + [ 1 ] to switch to the first workspace, but then instead a "1" key-input will be sent to the currently focused application instead. I assume it is because of something involving the modifiers state. Once this start happens during a session, I have to restart cosmic-comp for the shortcuts to work again.

**Comment by XV-02** [comment]
I'm not seeing this when using Cosmic at current, and I'm not seeing additional reporting. I'm closing this issue due to dormancy.
