### ISSUE TITLE
Popups in bottom anchored panel are repositioned off screen

### ISSUE THREAD

**Issue by wash2** [pop-os/cosmic-comp#51]
I have set the popups in all cosmic-panel applets to allow repositioning by cosmic-comp. Side anchored panel popups and top anchored panel popups all seem to be positioned correctly when necessary, but the bottom panel popup, are re-positioned to appear off screen below the panel, even when they don't seem to have needed re-positioning in the first place.

**Comment by XV-02** [comment]
@wash2 I'm not entirely sure what you mean by this. As far as I can tell, menus spawned by interacting with panel applets are being positioned correctly regardless of where on the panel they are (centre, left, or right) and regardless of the position of the panel itself (top, left, bottom, right) and regardless of other factors like whether the applet is near the border of multiple displays. 

Can you confirm if this is still an issue or not?

**Comment by wash2** [comment]
Oh this should be closed
