### ISSUE TITLE
DPMS for turning off the screen after a specific duration

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-comp#517]
1. Users can override the duration in [Settings](https://www.figma.com/design/142SZP1yG2d34SUdDvkaYV/COSMIC-Settings---Developer-Handoff?node-id=9753-92877&t=mg91F3EU4Fe2PbYR-0).
2. Default to turning the monitor off in 15 minutes (energy star compliance).
3. Turning off the monitor should also lock the session is it's not already locked

**Comment by jokeyrhyme** [comment]
Related: https://github.com/pop-os/cosmic-epoch/issues/172

**Comment by ryanabx** [comment]
Is this complete now that cosmic-idle is a thing?
