### ISSUE TITLE
XWayland + ultrawide external display: some windows become insensitive to mouse

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-comp#524]
On lemp13, I was able to recreate a reported issue from a user on Mattermost. When I connect a 5120x1440 ultrawide via USB-C, certain apps stop reacting to mouse clicks. The one I saw most frequently act this way is OnlyOffice. I could still move the window around with mouse drags, but I couldn't click anything in the app's window itself. I could still arrow around with the keyboard, and Super + Q closed the window, so I don't think the application itself was locked up.

I used both what's currently released as of today, as well as adding `popdev:master` and updating, and the  bug persisted with both.

Interestingly, I have not seen this happen at all with my oryp9, and I use this ultrawide display daily with it. I don't use OnlyOffice, but I'm sure I'd have come across this by now if my install was affected. I'm not sure if that's an artifact of this COSMIC DE install being quite old comparatively, or that the oryp9 has an Nvidia GPU.

Here is the output of `apt policy cosmic*`: [versions.txt](https://github.com/pop-os/cosmic-comp/files/15506096/versions.txt)

**Comment by Drakulix** [comment]
Pretty sure this was fixed with https://github.com/pop-os/cosmic-comp/pull/575
