### ISSUE TITLE
Floating windows flicker when opened over maximized windows

### ISSUE THREAD

**Issue by ryanabx** [pop-os/cosmic-comp#526]
My hunch is this commit caused it, as it caused a few other regressions with floating windows: https://github.com/pop-os/cosmic-comp/commit/a3df48fe176e3fdabcc3eb8d54e21fc9aa2fe3d5

To reproduce:

Maximize window A
Drag window B to tile to the left
Drag window C to tile to the right

Result:

Only B or C can be shown at a time, never both

This oddly does not occur UNLESS there is a maximized window behind windows B and C

Screenshots (since screen capture is broken in a recent update)

![screenshot-2024-05-31-05-56-22](https://github.com/pop-os/cosmic-comp/assets/56272643/a1b9424f-f099-49e1-bb84-c9d3d51aa460)
![screenshot-2024-05-31-05-56-33](https://github.com/pop-os/cosmic-comp/assets/56272643/09b21b3a-5575-4236-931f-2bdb0d6de2c3)

**Comment by git-f0x** [comment]
From my testing, tiling the windows isn't necessary. Only one window can be visible over a maximized window in all cases (2 windows can be visible while dragging one of them, but that's probably related to an already reported issue).

**Comment by ryanabx** [comment]
> From my testing, tiling the windows isn't necessary.

It's just an easy way to reproduce

**Comment by jacobgkau** [comment]
This is still happening on 9cd553e.

It seems to have gotten worse with recent updates; I just applied updates & rebooted, and now, even a single floating window over a maximized window flickers.

**Comment by Drakulix** [comment]
Fixed by da9af7ad23ea91d850ab81c47deefecd40c1f972
