### ISSUE TITLE
flickering

### ISSUE THREAD

**Issue by rrahl0** [pop-os/cosmic-comp#527]
When I am in floating mode, and I have 2 maximized windows in the background, and a terminal in the front, the screen starts to flicker (only the maximized windows are flickering)

**Comment by wash2** [comment]
https://github.com/pop-os/cosmic-comp/commit/13e67f3dc2bd14d80de0d200671be70f9fbdc761 should fix this issue

**Comment by rrahl0** [comment]
still happening. I am on commit #697ec9e

**Comment by jacobgkau** [comment]
This is a duplicate of https://github.com/pop-os/cosmic-comp/issues/526, but it is still happening on current master (9cd553e).

I'm closing as a duplicate to track it in the other issue.
