### ISSUE TITLE
Can't build on Arch Linux(leaking restricted types)

### ISSUE THREAD

**Issue by jrapf32** [pop-os/cosmic-comp#532]
When rust builds libcosmic for cosmic-comp it complains about leaking restricted types in 
`    pub(crate) horizontal_direction: Direction, `
`    pub(crate) vertical_direction: Direction, `
`   pub(crate) menu_states: Vec<MenuState>,`   
line 34 - 36 libcosmic/src/widget/menu/menu_inner.rs.
"*rustc 1.72.1*"

**Comment by dkharlan** [comment]
I'm seeing this on Pop 22.04 as well when trying to build `697ec9e`, also with Rust 1.72.1.

**Comment by jrapf32** [comment]
> I'm seeing this on Pop 22.04 as well when trying to build `697ec9e`, also with Rust 1.72.1.
> 
> (edit) Ah this looks like a dupe of #543

#543 is a dupe of this.

**Comment by jrapf32** [comment]
This issue has been fixed by recent commits.
