### ISSUE TITLE
Super+Click dragging temporarily leaves the cursor in the pressed state in GTK apps

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-comp#544]
After holding Super+Click and dragging a GTK window, releasing Super+Click and then moving the cursor behaves as if the click is still being held.
E.g. in Nautilus, the selection rectangle is created and follows the cursor when Super+Click is released. In Firefox, if on a site with selectable text, the text selection appears and follows the cursor after the buttons are released.
Fixed when clicking again.

**Comment by jasonrhansen** [comment]
This is also a problem for some non-GTK apps like Alacritty and WezTerm, but not COSMIC apps like COSMIC Terminal or COSMIC Files.

**Comment by git-f0x** [comment]
Fixed by #750.
