### ISSUE TITLE
SSD doesn't respect window control settings

### ISSUE THREAD

**Issue by tobyrg** [pop-os/cosmic-comp#549]
Apps that use server side decorations does not respect windows controls settings.

![image](https://github.com/pop-os/cosmic-comp/assets/153357251/415ff04c-f8bf-438a-a9dc-3a0488b9ce1a)

Element 
![image](https://github.com/pop-os/cosmic-comp/assets/153357251/59417b47-389c-448d-b7f6-2b0c0977c2fb)

**Comment by git-f0x** [comment]
This can probably be closed, since it seems to work now.
