### ISSUE TITLE
Cosmic-comp event thread crash when scrolling in VS Code's explorer panel

### ISSUE THREAD

**Issue by pyroraptor07** [pop-os/cosmic-comp#552]
This is a recent issue as of the last few weeks (roughly).

Steps to reproduce:
- Install the latest version of COSMIC from the PopOS official repositories
- Install the latest version of VS Code through Microsoft's repositories
- Log in to a new COSMIC desktop session
- Open VS Code
- Scroll using the mouse inside the Explorer panel

Result:
- VS Code window suddenly disappears except for the window decorations
- The lingering window decorations will not go away even if you manually kill the VS code process (you have to log out to get rid of it)
- The following error message appears in journalctl: `cosmic-comp[15930]: Event thread exiting due to connection error Connection reset by peer (os error 104)`

Logs and system information (including installed COSMIC packages) are attached.

![vscode_cosmic-comp_crash](https://github.com/pop-os/cosmic-comp/assets/5386339/2f6c4d84-daf1-4c2d-8f41-6263f3044b3c)

[system-info.txt](https://github.com/user-attachments/files/15798039/system-info.txt)
[vscode_cosmic-comp_crash_logs.txt](https://github.com/user-attachments/files/15798040/vscode_cosmic-comp_crash_logs.txt)

**Comment by pyroraptor07** [comment]
I apologize if this is already a known issue, I didn't see one when I checked.

**Comment by mspellecacy** [comment]
Thought I'd kick the tires on Cosmic today and I'm running in to this exact issue- Only it happens in Brave and [JetBrains] RustRover.

My journal also gets spammed with:

```
Jun 12 13:11:37 sake-pop cosmic-comp[113636]: Failed to update Xwm stacking order.
Jun 12 13:11:37 sake-pop cosmic-comp[113636]: Failed to update Xwm stacking order.
Jun 12 13:11:37 sake-pop cosmic-comp[113636]: Failed to update Xwm stacking order.
Jun 12 13:11:37 sake-pop cosmic-comp[113636]: Failed to update Xwm stacking order.
```

**Comment by mmstick** [comment]
I use VS Code every day. Haven't seen this. Do you have XWayland 24.1 and popdev:master added to the system?

**Comment by mspellecacy** [comment]
@mmstick 
I did have Xwayland 24.1, I did not have popdev:master. Added, updated, upgraded, and now Cosmic doesn't instantly crash when I scroll in Brave. 

Not sure where I missed the step for adding popdev:master.
Thanks!

**Comment by pyroraptor07** [comment]
@mmstick Adding popdev:master appears to have fixed this for me as well. Thanks!
