### ISSUE TITLE
issues with wl-clipboard, tiling and neovim

### ISSUE THREAD

**Issue by fl42v** [pop-os/cosmic-comp#555]
# description

wl-copy and wl-paste seem to open a window when used which makes using nvim with `set clipboard=unnamedplus` with tiling enabled a somewhat unpleasant experience since wl-clipboard's window resizes the terminal with nvim which makes the cursor jump around the document. 

weirdly enough, using `wl-clipboard-rs` results in the following error: `Error: A required Wayland protocol (zwlr_data_control_manager_v1 version 1) is not supported by the compositor` despite `wlr_data_control` being at least referenced in the sources. So, I suspect the regular wl-cliboard is unable to interface via that protocol as well, and creates the window as a workaround of sorts.

# reproducing

turn on tiling for the current workspace, enter `echo whatever | wl-copy` in the terminal, notice its window being briefly resized to half a screen, then go back to normal.

# misc

tested on the latest unstable nixos (cosmic-comp revision: fb88f389c38f6d3981341317af157576127e1cfe, installed via [this flake](https://github.com/lilyinstarlight/nixos-cosmic/blob/215494f3fbf55cc11dfc3fb8c2e3f936b7883f97/pkgs/cosmic-comp/package.nix)) and pop_os 22.04 after `sudo apt update && sudo apt upgrade`. Also, `wl-copy`/`wl-paste` don't behave this way on other window managers (tested on `qtile -b wayland`, `hyprland`).

a potential workaround would be to not tile the created window (like dialog windows).

**Comment by Drakulix** [comment]
https://github.com/pop-os/cosmic-comp/issues/99#issuecomment-1494018566
