### ISSUE TITLE
cosmic-comp crashes when you turn on a single display

### ISSUE THREAD

**Issue by thomas-zimmerman** [pop-os/cosmic-comp#558]
I turn off my monitor at night. Music playing in the background continues (and session lives) until I turn the monitor back on.

**Comment by addy419** [comment]
@thomas-zimmerman I have been facing the same issue.

**Comment by Quackdoc** [comment]
what commit hash are you running? I was running into that issue a while ago but it solved itself after updating, as a temporary work around I was disabling the display first, then turning off the display, turn on display, then enabled it using cosmic-randr

**Comment by WatchMkr** [comment]
Duplicate of https://github.com/pop-os/cosmic-comp/issues/57
