### ISSUE TITLE
[Feature] Support for wlr-screencopy-unstable

### ISSUE THREAD

**Issue by tobyrg** [pop-os/cosmic-comp#560]
Using Waycheck I can see there is zcosmic_screencopy_manager, is this related? I like to use grim for some scripts which needs the protocol.

**Comment by Drakulix** [comment]
We won't support `wlr-screencopy-unstable`, but are instead working on upstream protocols (`ext-screencopy`), which are meant to replace `wlr-screencopy`: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/124

`cosmic-screencopy` is related to that, as that basically is an unfinished namespaced version of `ext-screencopy`. But both are not 100% compatible with `wlr-screencopy`, so clients like grim will need to adjust to `ext-screencopy` once that is properly done and released. Until then these clients won't work without patches.

**Comment by bbigras** [comment]
Is ext-screencopy already supported? I would like to use wluma with cosmic (see mentionned wluma issue).

**Comment by ids1024** [comment]
The protocol was renamed to `ext-image-copy-capture-v1` before being accepted by `wayland-protocols`. But  yes, it is supported by cosmic-comp.

**Comment by eevmanu** [comment]
in case anyone wants to confirm if their cosmic-comp installation supports [ext-image-copy-capture-v1](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/fff667c829b067500a5a3bf84e7bae1bb293d3aa/staging/ext-image-copy-capture/ext-image-copy-capture-v1.xml) - [wayland.app](https://wayland.app/protocols/ext-image-copy-capture-v1)

check `cosmic-comp` version

```sh
$ apt show cosmic-comp 2>&1 | grep -i version
Version: 0.1~1760619582~24.04~bead74f
```

check [`wayland-utils`](https://gitlab.freedesktop.org/wayland/wayland-utils) cli tool

```sh
$ apt show wayland-utils 2>&1 | grep -i version
Version: 1.2.0-1build1
```

install `wayland-utils`

```sh
$ sudo apt install wayland-utils
```

check is installed correctly

```sh
$ apt search wayland-utils 2>&1 | grep -i installed
wayland-utils/noble,now 1.2.0-1build1 amd64 [installed]
```

filter output to find the protocol using `wayland-info` cli

```sh
$ wayland-info | grep -i ext | grep -i image | grep -i copy | grep -i capture
interface: 'ext_image_copy_capture_manager_v1',          version:  1, name: 16
```

---

you can see the findings of it in this repo by [github search - `repo:pop-os/cosmic-comp ext_image_copy_capture_manager_v1` - filter by `code`](https://github.com/search?q=repo%3Apop-os%2Fcosmic-comp%20ext_image_copy_capture_manager_v1&type=code)
