### ISSUE TITLE
[Feature Request] Focus follows mouse for tiling mode

### ISSUE THREAD

**Issue by sa7dse** [pop-os/cosmic-comp#564]
This should be an option that users can enable and disable to suit their workflow.

(I hope i created this in the correct project)

**Comment by Drakulix** [comment]
New focus options, specifically:
- No focus follow
- Focus follows mouse when changing outputs (current behaviour)
- Focus follows mouse

are already planned post alpha 1. :)

**Comment by digitalethics** [comment]
I found the Xfce settings for the focus model quite intuitive and add a screenshot here for reference: 
![focus model_xfce](https://github.com/pop-os/cosmic-comp/assets/57445091/cd68f972-dea1-459f-8f13-6ad36bc7adcf)

**Comment by skewballfox** [comment]
Open to PRs for this?

**Comment by Drakulix** [comment]
> Open to PRs for this?

Sure, though for the exact semantics, I would suggest pinging @pop-os/ux.
From what I remember we had agreed to support additional modes as layed out in https://github.com/pop-os/cosmic-comp/issues/564#issuecomment-2180392519, but not talked about a much more comprehensive customization story as shown for Xfce in https://github.com/pop-os/cosmic-comp/issues/564#issuecomment-2186678725.

What would certainly be welcome, is being able to configure all of this through cosmic-config files for cosmic-comp and not yet exposing them in cosmic-settings until we have finalized designs. And that might even include customizable delays, though we might never expose them in our configuration UI.

**Comment by skewballfox** [comment]
> Sure, though for the exact semantics, I would suggest pinging @pop-os/ux.

dumb question, how do I do that? I tried searching chat.pop-os.org for a channel or user name ux, and for a repo under pop-os. no luck with either

**Comment by Drakulix** [comment]
So after discussing this internally, we have come to a different conclusion at how this should work:

- Moving mouse to an empty display doesn't switch focus away from the previously focused window (different from current behaviour).
- Moving mouse to another display with a window moves the focus along to that window.
- Moving mouse to another window on the same display doesn't move the focus over from the previously focused window.
- Launcher and App library should still open where the mouse cursor is currently, even if there is a focused window on another display. 

To facilitate this, we will need a bit of refactoring, as to what previously was the `active_output` of a seat. Parts of the code assume that output will contain a focused element. But with this change conceptionally the "focused output" and the "active output" (the one with the cursor one) will now be to different things.

For configuration options, we will add two toggles:
- Toggle 1
  - Focus follows cursor (disabled): Clicking, launching, or moving to a window with shortcuts/launcher focuses the window.
  - Focus follows cursor (enabled): Clicking, launching, moving to a window with shortcuts/launcher, **and** moving the cursor into a new window focuses the window.
- Toggle 2
  - Cursor follows focus (disabled): The compositor will not warp the cursor on focus events.
  - Cursor follows focus (enabled):  The cursor moves to the top left of the a window focused by launching or moving to the window with shortcuts/launcher (anything triggering a focus change, that isn't moving the cursor)

**Comment by digitalethics** [comment]
>  Focus follows cursor (enabled): Clicking, launching, moving to a window with shortcuts/launcher, **and** moving the cursor into a new window focuses the window.

Would there still be any option to focus a window by just moving the mouse cursor over it without clicking as is the case in Xfce? @Drakulix

**Comment by skewballfox** [comment]
@Drakulix to clarify, all the behaviors listed in the first section are the new defaults? i.e. when both toggles are false(or yet to be implemented) these will be how cosmic-comp behaves.

Mainly asking because bullet point 3 seems to contradict the behavior laid out with Focus follows cursor.

**Comment by Drakulix** [comment]
> > Focus follows cursor (enabled): Clicking, launching, moving to a window with shortcuts/launcher, **and** moving the cursor into a new window focuses the window.
> 
> Would there still be any option to focus a window by just moving the mouse cursor over it without clicking as is the case in Xfce? @Drakulix

Yes, that is the first toggle.

**Comment by Drakulix** [comment]
> @Drakulix to clarify, all the behaviors listed in the first section are the new defaults? i.e. when both toggles are false(or yet to be implemented) these will be how cosmic-comp behaves.
> 
> Mainly asking because bullet point 3 seems to contradict the behavior laid out with Focus follows cursor.

Both toggles to false will be the default and should largely correspond to cosmic-comps current behavior. Exceptions to this are of course moving the mouse onto another empty display doesn't take focus away and currently some shortcuts to warp the cursor, like switching the output via keyboard. So we might need to refine toggle 2 slightly to represent that.

**Comment by pabloavi** [comment]
>       * Focus follows cursor (enabled): Clicking, launching, moving to a window with shortcuts/launcher, **and** moving the cursor into a new window focuses the window.

@Drakulix Would it be possible to change the focus when the cursor **moves** and not only when it moves **into** a new window? In GNOME, the only option is the known 'sloppy focus' (focus changes if cursor moves **into** a window), but most window managers can do the following: if the cursor is inside a window but does not move, focus does not change, if it moves inside the unfocused window, focus changes to that window.

**Comment by theduke** [comment]
I'm seconding the request for "focus follows mouse" as an option.

This is how I've been using sway for a long time, and it is by far the most intuitive way to work if you use a mix of mouse and keyboard interaction.
