### ISSUE TITLE
RFE suggestion: (option to) show active window hint only if more than one window

### ISSUE THREAD

**Issue by juhp** [pop-os/cosmic-comp#566]
I feel this could be a nice UX improvement: only show the active hint window border box when more than one window is being displayed in a workspace.  WDYT?

**Comment by Kartonrealista** [comment]
This doesn't make sense with multi monitor setups, as you can make your cursor go to another monitor, making your window on the first screen go out of focus.
You can also make a window go out of focus if you click on the panel, so it's not always active by purely being on-screen.

**Comment by wiiznokes** [comment]
I think your setup of one window by workspace could be changed by using a scratch pad. I plan to make one for cosmic eventually

**Comment by juhp** [comment]
What is a scratch pad?

**Comment by juhp** [comment]
Okay I think you mean like like a pop-up terminal or other tool
