### ISSUE TITLE
Question: How to set touchscreen up with multiple displays.

### ISSUE THREAD

**Issue by Quackdoc** [pop-os/cosmic-comp#567]
I have a monitor with a touchscreen and am wondering how I set which monitor the touchscreen is bound to, currently the touchscreen doesn't work, the touchscreen registers as `ILITEK ILITEK-TP` and `ILITEK ILITEK-TP Mouse` in libinput.

I did see `map_to_output` in the code but im not sure how to manually set that.

EDIT: this also seems relevant for `sunshine` game streaming (though that has other bugs) it reports `Touch passthrough` and `Pen passthrough` for pen and multitouch

**Comment by Drakulix** [comment]
I think you can configure what output a touchscreen maps to via cosmic-comp's input configuration. Ping @ids1024

**Comment by drwankingstein** [comment]
I would like to know this too, I tried using something like `(name:"Touch passthrough",map_to_output:"DP-1")` to `~/.config/cosmic/com.system76.CosmicComp/v1/input_devices` but this didn't work, I'm not sure what I'm supposed to put here

**Comment by Drakulix** [comment]
Ping @ids1024, who implemented this feature and can probably tell you more.

**Comment by drwankingstein** [comment]
@ids1024 any info on how to go from here?

**Comment by Quackdoc** [comment]
looked through for a bit, turns out that state:enabled was mandatory and I missed that, for anyone comming across this before a setting is wired up in config, here is an example

```
{
 "ILITEK ILITEK-TP": (
    state: Enabled,
    map_to_output: Some("HDMI-A-2")
    )
}
```
