### ISSUE TITLE
ToplevelInfo protocol, doesn't give the same app id every time

### ISSUE THREAD

**Issue by wiiznokes** [pop-os/cosmic-comp#571]
So i have no clue how this thing works, but i noticed while working on desktop entries stuff ([ex](https://github.com/pop-os/launcher/blob/master/plugins/src/cosmic_toplevel/toplevel_handler.rs)), that youtube music web app on brave don't have the same runtime app id on my PC and laptop.

This is the .desktop file:

```
cat .local/share/applications/com.brave.Browser.flextop.brave-cinhimbnkkaeohfgghhklpknlkffjgod-Default.desktop
#!/usr/bin/env xdg-open

[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=YouTube Music
Exec=flatpak 'run' '--command=brave' 'com.brave.Browser' '--profile-directory=Default' '--app-id=cinhimbnkkaeohfgghhklpknlkffjgod'
Icon=brave-cinhimbnkkaeohfgghhklpknlkffjgod-Default
StartupWMClass=crx_cinhimbnkkaeohfgghhklpknlkffjgod
X-Flatpak-Part-Of=com.brave.Browser
TryExec=/var/lib/flatpak/exports/bin/com.brave.Browser
```

On my laptop (intel, no dedicated GPU), the runtime appid will be sometings similar to `crx_cinhimbnkkaeohfgghhklpknlkffjgod`, which make it easy to match the desktop entry.

On my PC (AMD with 3060ti), the runtime appid will be sometings similar to `com.brave.Browser` (i could get the exact appid if it is useful), so the icon will be the Brave one.

Kde and Gnome show the right icon on my PC, so i really think there is something wrong in COSMIC.

**Comment by Drakulix** [comment]
Given this is a chromium-app, it might be, that the application is running via Xwayland on one of our systems, while it is using wayland on the other?

**Comment by wiiznokes** [comment]
Indeed, after setting wayland in `brave://flags/`, it start showing the right icon in Cosmic. But Kde and Gnome shows the right icon even if brave is running as x11  client.

**Comment by Drakulix** [comment]
Then gnome/kde are probably using something else than the x11 WM Class for matching the icon. :woman_shrugging:

**Comment by wiiznokes** [comment]
Probably the window name then, if the comp have no control over this. So i guess we can close this issue.
