### ISSUE TITLE
KDE Connect remote input doesn't work

### ISSUE THREAD

**Issue by Kartonrealista** [pop-os/cosmic-comp#572]
The remote mouse and keyboard functions of KDE Connect don't work on cosmic-comp. Tested this on mutter on the same system (Pop on Wayland selected on the login screen) and it worked perfectly.

**Comment by Quackdoc** [comment]
duplicate of https://github.com/pop-os/xdg-desktop-portal-cosmic/issues/23

**Comment by Kartonrealista** [comment]
Closed since it's a duplicate.
