### ISSUE TITLE
Cursor stuck after logging in with gdm

### ISSUE THREAD

**Issue by leb-kuchen** [pop-os/cosmic-comp#576]
![screenshot-2024-06-26-13-19-27](https://github.com/pop-os/cosmic-comp/assets/102472435/72b9be03-6770-4755-a717-8f4aa967fcbb)

GTX 960 and i5-4460

**Comment by Drakulix** [comment]
Which version of cosmic-comp is this? Also can you post the output of drm_info in this case please?

**Comment by leb-kuchen** [comment]
I think it is a duplicate of #440

**Comment by leb-kuchen** [comment]
Anyway, I can't  reproduce it with the newest version on master after switching back to gdm.

**Comment by Drakulix** [comment]
Yes, this should've been fixed by the latest kms updates, we now always clear the cursor plane correctly even on nouveau. Forgot to mention this.
