### ISSUE TITLE
Feature Request: Blank / Turn Off screens on idle

### ISSUE THREAD

**Issue by snaggen** [pop-os/cosmic-comp#580]
To avoid damaging screens, it would be very nice to have the screens being blanked and turned off after a period of inactivity. This probably need some seetings in the Cosmic Settings app also, so this must probably be coordinated with multiple projects. 

For bonus extra fun, it woud be nice with screensavers... and from what I understand is jwz still fiddling around with his xscreensavers... just saying ;)

Pinging @jackpot51 and @mmstick  for possible coordination.

**Comment by Kartonrealista** [comment]
#517
Jamie doesn't seem all that jazzed about the current way of doing screensavers on Wayland, that being through ext-session-lock, so I wouldn't get my hopes up.

**Comment by snaggen** [comment]
Ah... didn't see that issue. I will close this then.

**Comment by jokeyrhyme** [comment]
Related: https://github.com/pop-os/cosmic-epoch/issues/172
