### ISSUE TITLE
Can't drag a window out of a stack & tab close button issue

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-comp#585]
I think this is a regression. Windows can't be pulled (mouse dragged) from stacks via their tab. And the first app that's stacked can't be closed with the close button.

**Comment by Drakulix** [comment]
Drag out part of the issue is fixed with f02520c194624d2bcd31c7d37e442754dbbd59a1.
Close button issue is still being looked at.

**Comment by Drakulix** [comment]
Fixed with https://github.com/pop-os/cosmic-comp/commit/e61a76d39ce2e9902c81b7955830fad982f797f9
