### ISSUE TITLE
Firefox + cosmic-comp 125% scaling = 80% cpu use

### ISSUE THREAD

**Issue by flukejones** [pop-os/cosmic-comp#587]
Per title. I think this happened in the last few days so maybe with the KMS rework?

At 100% scaling it's fine and cpu use is way down at 0-1.5% as usual. I had an issue with cosmic-applets related to scaling also which was fixed with a `cargo update`, I'm guessing libcosmic update helped. I'll try that here.

**Comment by flukejones** [comment]
I think I've narrowed it down at least:

1. Autotiling disabled
2. Open FF
3. Maximised FF runs fine
4. Floating window seems fine
5. Tile to the left - comp CPU use jumps to 100% (no autotile, just floating mode, with manual tile)

**Comment by Drakulix** [comment]
Can't reproduce unfortunately :/

Which cosmic-comp commit are you running?

**Comment by flukejones** [comment]
I can't reproduce anymore for a few days now. Must have been fixed in your last lot of work :grinning:
