### ISSUE TITLE
Question: Can we use the upstream smithay? 

### ISSUE THREAD

**Issue by songww** [pop-os/cosmic-comp#59]
I tried it and didn't find any problem. But I'm new to this and I don't know how to do a full test.

Thanks. This project is amazing!

**Comment by Drakulix** [comment]
We pin the commit, so that new changes to smithay won't cause cosmic-comp to break. The commit is frequently updated to the latest master release (or even some wip-branch) to keep up with the changes though. So we are effectively using upstream!
