### ISSUE TITLE
cosmic-comp freeze when cosmic-workspaces, cosmic-launcher or cosmic-panel is killed

### ISSUE THREAD

**Issue by wiiznokes** [pop-os/cosmic-comp#593]
I know it worked some time ago. I could try to bisect if you guys are not sure why this happens

**Comment by Drakulix** [comment]
Upstream bug at wayland-rs. Will take some time to bubble up.

**Comment by Drakulix** [comment]
https://github.com/Smithay/wayland-rs/issues/741

**Comment by Drakulix** [comment]
Fixed with https://github.com/pop-os/cosmic-comp/commit/b3b9eadfcad7dd7c0696f46199d99d433ec13125
