### ISSUE TITLE
Strange focus behavior on tiled workspaces

### ISSUE THREAD

**Issue by man0lis** [pop-os/cosmic-comp#595]
While testing cosmic, I ran into a focus quirk that interferes with a keyboard before mouse workflow.
It is quite easy to create a situation, where no window on a tiled workspace is focused and focus can not be regained without using the mouse.

Steps to reproduce:
* switch to an empty workspace with tiled behavior
* open cosmic-terminal (Super+t)
* enable stacking (Super+s)
* open another cosmic-terminal (Super+t)
* disable stacking (Super+s)

Now the focus frame goes around both terminals. One would expect to be able to focus one of them using the Focus-in action (Super+i) but this does not work. Even stranger, if you switch to another workspace and back, no window at all is focused and the only way to get focus is by clicking on one of the terminals. When closing one of the terminals focus is lost again and a click is needed to get it back.

**Comment by Drakulix** [comment]
This should've been fixed with the last couple of commits. (Specifically https://github.com/pop-os/cosmic-comp/compare/2d0f1cbf2be311b91096b2f2332cd7bafabbfde3..b9a323c9ff001f81dfafffb3f40b4122660da27c)

Please comment if any quirks remain.
