### ISSUE TITLE
Window loses focus while being dragged

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-comp#596]
If I have two windows open and I begin dragging one of them, the window being dragged loses focus, and (probably the bigger deal) the other one gets focus. E.g. if I begin dragging one window and start typing while I'm dragging, a different window (presumably the second-most-recent focused one) gets the input.

Dragging a window is an explicit interaction, so I don't see why a window in the process of being dragged with the mouse shouldn't just retain focus while that's happening.

Reported on 2d0f1cb.

**Comment by git-f0x** [comment]
Might be a duplicate of #453, but it's possibly better described here.

**Comment by Drakulix** [comment]
Fixed by https://github.com/pop-os/cosmic-comp/commit/d4926c3a9e66a2b699fbe626b2609ed5d373cce4
