### ISSUE TITLE
Games with xwayland break in fullscreen when direct scanout is triggered

### ISSUE THREAD

**Issue by Dekomoro** [pop-os/cosmic-comp#601]
Wine Games repeatedly minimize and maximize, get a black screen when the mouse cursor leaves the window, or start with a blackscreen when in fullscreen

Native titles will repeatedly maximize and minimize, freeze, or both depending on cursor focus.
This is exhibited in both wine, and native titles made with FNA but not ones made with the source engine or godot

Native titles made with source 2 will stay minimized , if you try to open it from the application dock it will minimize itself automatically, unless you open it from the dock on the other monitor. However this may be another issue entirely as source 2 games exhibit this issue when using the Wayland back end(requires removing the SDL_VIDEO_DRIVER=x11 variable from cs2.sh)

Games that either work with native wayland or don't trigger direct scan-out do not exhibit this issue.

For wine it is at least not likely an issue with dxvk as pre-source 2 games that use it for Vulkan don't exhibit this issue

**Comment by Dekomoro** [comment]
Forgot to mention but in fna's case the console spews out the error `RGBA8 swapchain unsupported, falling back to BGRA8 with swizzle`. Unsure if it's relevant at all however.

**Comment by Dekomoro** [comment]
When minimized I also get this error `Failed to acquire swapchain image, not presenting`

**Comment by Drakulix** [comment]
> Wine Games repeatedly minimize and maximize, get a black screen when the mouse cursor leaves the window, or start with a blackscreen when in fullscreen

The minimize issue isn't related to direct scanout, I wouldn't be so sure about the black screen as well.



> Forgot to mention but in fna's case the console spews out the error `RGBA8 swapchain unsupported, falling back to BGRA8 with swizzle`. Unsure if it's relevant at all however.

That is interesting, but shouldn't really concern the compositor. It might affect the gpu's ability to do direct scanout though. Could you post the outputs of `eglinfo` and `drm_info` on your system?

> When minimized I also get this error Failed to acquire swapchain image, not presenting

Expected, minimized windows are throttled.

**Comment by Dekomoro** [comment]
Yeah.
drm_info: https://gist.github.com/Dekomoro/da97aeac6f0e450837cfbcb2a958ac97
eglinfo: https://gist.github.com/Dekomoro/7c494e5ced5ac1f3701b01a61ca9921a

I get the same results on Arch, POP_OS with cosmic master branch, and using the fedora copr if that matters

**Comment by Drakulix** [comment]
Please retest with https://github.com/pop-os/cosmic-comp/pull/603 merged.

**Comment by Dekomoro** [comment]
> Please retest with #603 merged.

Everything is fixed including tf2 except for an edge case where moving the mouse onto a second monitor breaks it. Luckily the game works with setting `SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0`. vast improvements and you can probably safely close this.
