### ISSUE TITLE
Significant CPU Usage on cosmic-comp when tiling

### ISSUE THREAD

**Issue by nothingto** [pop-os/cosmic-comp#607]
When you are in tiling mode and start the process of tiling, if you open htop or any other systems monitor, you can notice significant CPU usage when starting to move tiles/windows around. You can reproduce this more easily by holding on to the keybinds (Super + Shift) even after moving a tile. 

The CPU usage that i'm seeing is around 100-200% CPU usage (anywhere from 1-2 cores worth of CPU activity) or when averaged out amongst cores, around 5% of my CPU to do simple tiling. This seems to be CPU bound currently. Maybe this is expected and GPU acceleration for tiling has not been implemented yet? Can anyone fill me in and also whether this is reproduced by anyone else?

I say this is high because coming from GNOME, moving windows around seem to at max take 5-10% of CPU on htop and about 0.50% CPU on the gnome-compositor on systems monitor which seems significantly different.

**Comment by rstat1** [comment]
I also see high CPU usage in tiling mode. System is currently idling with 3 windows up, one on each of 3 screens, and I'm seeing 25-30% CPU. As soon as tiling is turned off completely cosmic-comp immediately drops to basically nothing at idle.

I'm running COSMIC on Fedora 39 on an 11th Gen Intel based laptop with only an iGPU if any of that matters.

**Comment by Drakulix** [comment]
> You can reproduce this more easily by holding on to the keybinds (Super + Shift) even after moving a tile.

Please try with https://github.com/pop-os/cosmic-comp/commit/c506d94ac883a779bca23518b021727669ca42d6, that should reduce cpu usage significantly during these kind of scenarios.

**Comment by nicahokie** [comment]
I also saw significant cpu usage on several processes not just cosmic-comp not just when tiling but even when idle.  It started a few weeks ago around the same time that more cosmic applets and wall papers were added to the binary packaged distribution version of the pre-release comic desktop published on the distro repositories.
I was able to reproduce the issue on two laptops.
However if I build cosmic desktop from scratch from source it does not have this cpu usage problem.

**Comment by Drakulix** [comment]
> I also saw significant cpu usage on several processes not just cosmic-comp not just when tiling but even when idle. It started a few weeks ago around the same time that more cosmic applets and wall papers were added to the binary packaged distribution version of the pre-release comic desktop published on the distro repositories. I was able to reproduce the issue on two laptops. However if I build cosmic desktop from scratch from source it does not have this cpu usage problem.

That sounds like a distribution problem then, potentially caused by outdated packages. Which distros were hit by this in your experience?

**Comment by nicahokie** [comment]
Thanks for your response.  I am on pop os 22.04 unofficially in-place upgraded to 24.04
However lots of cosmic packages distro updated yesterday and the cpu usage problem did not come back so we can assume it is already fixed.
