### ISSUE TITLE
Dead lock when right clicking in vscode

### ISSUE THREAD

**Issue by wiiznokes** [pop-os/cosmic-comp#610]
I can't reproduce reliably. I launched vscode with this flags:

`code --enable-features=UseOzonePlatform --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto`.

The context menu does not appears, and cosmic-comp is freezing.

**Comment by espositofulvio** [comment]
I'm not sure if it's the same but I experienced a few random freezes on my laptop while using an external monitor using an HDMI cable. The plug socket on the laptop was a bit loose and since I've slotted the plug in better the issue seems to have gone.

**Comment by Drakulix** [comment]
> The context menu does not appears, and cosmic-comp is freezing.

Which OS / cosmic-comp version / vscode version are you on? Never seen this bug and I am using VSCode with the wayland backend daily.

**Comment by wiiznokes** [comment]
Just to clarify, the context menu does appears, i was wrong.

I'm using Fedora 40, vscode version `1.91.1`. The cosmic-comp commit is `b1778da`, from the `20240712`. I'm using nvidia proprietary driver version `555.58.02`

**Comment by Drakulix** [comment]
Potentially the same issue as https://github.com/pop-os/cosmic-epoch/issues/429 ?

**Comment by wiiznokes** [comment]
> Potentially the same issue as [pop-os/cosmic-epoch#429](https://github.com/pop-os/cosmic-epoch/issues/429) ?

Possibly, because i was able to also reproduce. Also, i think i found a way to reproduce this issue:

Right click to make the context menu appears while moving the mouse fast in the context menu zone.

**Comment by Drakulix** [comment]
Could you check if https://github.com/pop-os/cosmic-comp/commit/989ee95858077aeb0f3e75e44bfeaf607c57f5c3 also fixes this issue?

**Comment by wiiznokes** [comment]
It is fixed
