### ISSUE TITLE
Some keybinds are not passed through to application even if unbound

### ISSUE THREAD

**Issue by Quackdoc** [pop-os/cosmic-comp#612]
Some keybindings like Super + F are not being sent to applications even if they are unbound in cosmic-settings. This breaks applications like gamescope which require the below bindings

For testing, if you open a video in MPV via console and use an unbound key, it will report the keys that have been pressed.

```
    Super + F : Toggle fullscreen
    Super + N : Toggle nearest neighbour filtering
    Super + U : Toggle FSR upscaling
    Super + Y : Toggle NIS upscaling
    Super + I : Increase FSR sharpness by 1
    Super + O : Decrease FSR sharpness by 1
    Super + S : Take screenshot (currently goes to /tmp/gamescope_$DATE.png)
    Super + G : Toggle keyboard grab
```

EDIT: on the flip side of the coin sometimes pressing the super key, dismissing the popup, then typing can trigger super + key, which can be equally as annoying sometimes. I think I saw a similar issue for this but forget if one does actually exist

**Comment by Drakulix** [comment]
Do you have the Super key bound? This sounds like it could potentially be an issue, where modifier-only bindings eat the keys.

**Comment by Quackdoc** [comment]
I went ahead and unbound super from opening the launcher, and I'm experiencing the same behavior. but I can elaborate on the second part

I press `Super+F` and nothing happens, I press `Super` and then any key after that acts as if it is a `Super + Key` press. Pressing any Super + Key combo at the same time stops this behavior. Simply pressing super does not.

**Comment by Drakulix** [comment]
Should be fixed by https://github.com/pop-os/cosmic-comp/commit/0a97147e45c4e893ab354bea78b30eaac1e4e633
