### ISSUE TITLE
With tiling disabled, new windows still launch tiled

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-comp#63]
**Version:** ec64759 (`master_jammy`)

**Issue:** After opening up some windows and disabling tiling, opening up a new window launches it tiled behind the existing windows (taking up the entire workspace and not able to be resized, as nothing else is tiled with it.)

**Steps to recreate:**
- Log into a session.
- Open a Terminal window with Super-T.
- Turn off tiling with Super-Y.
- Using the Launcher (Super + /), open a Calculator.
    - Observe that the Calculator opens up behind the Terminal.
- Attempt to resize the calculator window.
- Press Super-Y two more times.
    - The first press results in the Terminal window tiling with the Calculator window.
    - The second press untiles both windows, and Calculator is now resizable/movable.

**Expected behavior:** When tiling has been disabled with Super-Y, new windows should launch floating.

**Comment by Drakulix** [comment]
Should be fixed by https://github.com/pop-os/cosmic-comp/commit/5a8840b12e1319d3d1b3e9f430e8ec48c5c08423

**Comment by jacobgkau** [comment]
Confirmed, no longer happening on latest `mater_jammy` (4ed3ace, one after 5a8840b.)
