### ISSUE TITLE
Either depend on "xwayland" or gracefully handle it missing

### ISSUE THREAD

**Issue by jackpot51** [pop-os/cosmic-comp#64]
Without the xwayland package installed, cosmic-comp does not start.

**Comment by Drakulix** [comment]
This was an upstream issue, resolved with https://github.com/Smithay/smithay/pull/871/commits/9c3f790ad42430bb9204de3a7ca82955591c0bad and https://github.com/pop-os/cosmic-comp/commit/21db472f8bdd39bc28410e22f2f93a8ee3d1d043 in cosmic-comp
