### ISSUE TITLE
Super key to activate the launcher often requires two presses

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-comp#640]

**Comment by Drakulix** [comment]
This most likely regressed in either:
- https://github.com/pop-os/cosmic-comp/commit/4b2082f72a1902914e8cd09820456f2ce851cc33
- or https://github.com/pop-os/cosmic-comp/commit/0a97147e45c4e893ab354bea78b30eaac1e4e633

Both are important fixes for Xwayland though, so we need to take care to not break those again.
