### ISSUE TITLE
Ghost display on nvidia desktop GPUs

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-comp#641]

**Comment by Drakulix** [comment]
This is `simpledrm` picking up the nvidia-gpu before the nvidia module is loaded.

To fix this we need to either enable nvidia's experimental fbdev-support (which had a lot of issues prior to 550) or add a downstream kernel patch, like e.g. arch linux did: https://github.com/archlinux/linux/commit/7bfc7b32d0e0b486d3e66d843ca2f3fe514860a9

**Comment by ids1024** [comment]
Enabling the fbdev support could be good, but I don't know how that is in the current driver. I know it seemed a bit problematic when I tried it in the first driver that added it. It may be improved but is still "experimental" after all.

That kernel patch looks reasonable and straightforward, and including a patch Arch has generally seems alright.

**Comment by Drakulix** [comment]
> I guess it might also be possible for cosmic-comp to detect this situation in some way and ignore the simpledrm device node?

Maybe? There could be legitimate simpledrm devices though on an nvidia system. I am not sure how annoying it would be to figure out if they refer to the same device.

**Comment by ids1024** [comment]
The Arch patch seems to just be defining a `static` boolean that is set whenever `nvidia-drm.modeset` is set, that will prevent any `simpledrm` device from being created? If so then that would have the same issue.

It should be simple to filter out the simpledrm node. Though I see parameters like `/sys/module/nvidia_drm/parameters/modeset` aren't world-readable, unlike `/proc/cmdline`.

**Comment by XV-02** [comment]
For reference, the current fix effort:
https://github.com/pop-os/linux/pull/332

**Comment by mmstick** [comment]
Fixed by https://github.com/pop-os/linux/pull/332 and accompanying iso and distinst changes
