### ISSUE TITLE
Server Side Decoration headerbar doesn't get window control icons from theme

### ISSUE THREAD

**Issue by TheESN** [pop-os/cosmic-comp#651]
![изображение](https://github.com/user-attachments/assets/f07344f4-43c3-4d82-a8b1-31b2015d3078)

**Comment by leb-kuchen** [comment]
https://github.com/pop-os/libcosmic/commit/1e5828e01cfaffe99f1c3505083b1f590363a33e
Loading window controls from the icon theme was added recently.
cosmic-store and cosmic-settings have not updated to this commit, but applying it works. However cosmic-comp does not apply the theme even on the latest commit.

**Comment by Drakulix** [comment]
Fixed by https://github.com/pop-os/cosmic-comp/commit/fdde46febd4934cacbf6966a0cfeb50be78ce855
