### ISSUE TITLE
Icon theme in Server Side Decorations reset to Default theme after maximizing the window

### ISSUE THREAD

**Issue by TheESN** [pop-os/cosmic-comp#671]
Before maximize
![изображение](https://github.com/user-attachments/assets/192e7650-5989-4e5c-bc01-002c3b28d4f2)

After maximize
![изображение](https://github.com/user-attachments/assets/3d720ee9-f7f6-4f6f-90a9-f67a0a142d75)

**Comment by Drakulix** [comment]
Fixed in https://github.com/pop-os/cosmic-comp/commit/24462f728bddcd9be917d917d9ff0ecc4dbcc082
