### ISSUE TITLE
Server Side Decoration keep rounded corners after maximizing window

### ISSUE THREAD

**Issue by TheESN** [pop-os/cosmic-comp#672]
![изображение](https://github.com/user-attachments/assets/58b7f1d6-427a-4049-8302-bbb8bec56f8d)

Example how it should look:
![изображение](https://github.com/user-attachments/assets/b2a47c1d-5fb7-4ac3-840c-125e4c9d2e26)

**Comment by Drakulix** [comment]
Fixed in https://github.com/pop-os/cosmic-comp/commit/5aaac707f8ee7b8f62041bfac5450549c37d9451
