### ISSUE TITLE
[Bug] - Crashing and weird behavior when swapping and moving multiple focused windows

### ISSUE THREAD

**Issue by peterkrull** [pop-os/cosmic-comp#695]
Doing `Super + U` (I believe this is 'Focus window out') to focus multiple windows, swapping them to another empty workspace will cause the compositor to crash, with journalctl reporting:

``` shell
Aug 08 12:58:46 fedora cosmic-comp[1419855]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NodeIdNoLongerValid': src/shell/layout/tiling/mod.rs:750
```

And swapping with an existing application can lead to weird behavior where some windows seem to be hidden behind others.

In addition, simply moving multiple focused windows to another workspace with `Super + Shift + {num}` will not move all the windows, but just one of them.

**Comment by Drakulix** [comment]
Thanks for the detailed descriptions, very helpful to reproduce these.

> And swapping with an existing application can lead to weird behavior where some windows seem to be hidden behind others.

Do you have a consistent set of actions causing this?

**Comment by peterkrull** [comment]
Sure,

- In workspace 1, open one terminal instance
- In workspace 2, open two terminal instances
- In workspace 2, do `Super + U` to highlight both terminals
- Use `Super + X` to swap, and swap with the terminal in workspace 1

This will cause all three instances to exist on the same workspace, but they overlap each other. Closing one will lead the compositor to crash, with the report:

```bash
Aug 08 14:06:47 fedora cosmic-comp[1437078]: thread 'main' panicked at 'assertion failed: group.is_group()': src/shell/layout/tiling/mod.rs:1429
```

**Comment by Drakulix** [comment]
Swapping with an empty workspace should be fixed by: https://github.com/pop-os/cosmic-comp/commit/1f8915f80210635cacc4b8d222f54b0b8c26c85f
Weird behaviour on swapping across workspaces should be fixed by: https://github.com/pop-os/cosmic-comp/commit/e5a7dfbdb0320dcca6aa7d60778e7a5781739c99

Moving groups to different outputs/workspaces with Super+Shift+Arrows/Number needs some more adjustments.

**Comment by Drakulix** [comment]
Moving groups should now also be fixed.
