### ISSUE TITLE
`wl-paste` and `wl-copy` cause a tiling animation to happen as if they created a new window even though they don't

### ISSUE THREAD

**Issue by sgued** [pop-os/cosmic-comp#700]
With `wl-paste` there  is a full animation:

https://github.com/user-attachments/assets/1ab407e3-adf5-4159-9a97-caa34f77253a

With `wl-copy` there is a very fast flicker:

https://github.com/user-attachments/assets/87577c83-c0dd-4aa2-ba43-eabb6b74f834

**Comment by hojjatabdollahi** [comment]
You can add `COSMIC_DATA_CONTROL_ENABLED=1` to your environment (I do it because I really need my neovim setup to work normally). But this is a security feature and adding that would circumvent it.

**Comment by Balssh** [comment]
Is this how it's supposed to be enabled?
```
❯ command cat .config/environment.d/environment.conf
COSMIC_DATA_CONTROL_ENABLED=1
```

**Comment by hojjatabdollahi** [comment]
@Balssh I don't think cosmic-comp would/should read user space environmental variables. You need to add it to /etc/environment.d

**Comment by wiiznokes** [comment]
> Is this how it's supposed to be enabled?

you can create a file `/etc/profile.d/cosmic_data_control.sh` with `COSMIC_DATA_CONTROL_ENABLED=1` in it.
