### ISSUE TITLE
Quickly repeating 4-finger swipe when at first or last workspace also repeats animation

### ISSUE THREAD

**Issue by peterkrull** [pop-os/cosmic-comp#725]
Example: If I am at the 2nd workspace and i swipe towards the 1st workspace multiple times in quick succession, the animation will sort of cancel, snap me back to the 2nd workspace and redo the animation. This can be done repeatedly.

In the first half of the view I am only swiping left-to-right. In the second half I swipe in the opposite direction.

https://github.com/user-attachments/assets/e8bfb4a2-1508-4894-8758-fb2bf990ee7a

I have stumbled upon this when quickly swiping a few times left-to-right to get to my first workspace.

**Comment by BrunoWallner** [comment]
This also happens on the vertical layout and with the keyboard when pressing `Super` + `Arrow`. 
But using the keyboard it only occurs on the first and not last workspace.

https://github.com/user-attachments/assets/6846fe3a-8684-4738-aaaf-00ebfbfe860d

**Comment by jacobgkau** [comment]
@peterkrull https://github.com/pop-os/cosmic-comp/pull/761 only fixed this for the first workspace, and it looks like it's still happening for the last workspace, correct?

**Comment by peterkrull** [comment]
Ah you are right, I missed that!

**Comment by WatchMkr** [comment]
Worskpaces also don't cycle back to the first or last workspace with gestures. Cycling through workspaces was recently added with a shortcuts refactor.

**Comment by jacobgkau** [comment]
This was rendered obsolete when wrapping/cycling was implemented (without an option to disable it), but it seems the underlying cause is still present, as the bug's manifesting after disabling wrapping with https://github.com/pop-os/cosmic-comp/pull/2215.
