### ISSUE TITLE
neovim kickstart - flickering, un-maximize window

### ISSUE THREAD

**Issue by PavelSlepushkin** [pop-os/cosmic-comp#730]
Steps to reproduce:
1. Install neovim kickstart https://github.com/nvim-lua/kickstart.nvim
2.  Start terminal (Cosmic term or alacritty), maximize it (Super+M), open any file in neovim -kickstart (neovim <filename.txt>
3. yank a line (yy)

Bug/unexpected behavior - terminal window go into "unmaximized" state
for unmaximized window - there's flickering during yank, but it's not so obvious

Does NOT reproducible in clean neovim (neovim --clean), probably some autofuction in nvim-kickstart, but  kickstart works in other compositors without issues.

**Comment by PavelSlepushkin** [comment]
Refreshed to latest build - of cosmic-comp  - 0.1.0~^20240814gitbad8837-1.fc40 - and seems the problem was fixed, closing this

**Comment by donniebreve** [comment]
It seems like this is back.

Steps:
1. run `neovim` with only one configuration option: `vim.opt.clipboard = "unnamedplus"`
2. use any action that yanks to the clipboard (e.g. `cl`, `x`, `dd`, `yy`)
3. the window highlight/focus flickers

``` text
cosmic-comp-git 1.0.0.beta.1.1.r0.gf339e21-1
neovim 0.11.4-1
```
