### ISSUE TITLE
high CPU use with stacked windows

### ISSUE THREAD

**Issue by squalou** [pop-os/cosmic-comp#746]
Hi,

I wanted to relate this specific use case which instantly leads to pretty high cpu use of cosmic-comp

I open 4 vscodium instances in a workspace, and stack them.
To be precise : workspace is set to tiling mode, then I use Super+u to select all the opened windows, and then Super+s to stack them.
(I really like this BTW, was already using it a lot with gnome extension)

In this situation, having 'top' (or htop or whatever) opened shows process CPU climbing +15%  to +25% on my hardware, and staying on average pretty high, +10% on average I'd say, more said workspace is displayed, less but still measurable when another workspace is displayed.
Disabling stacking reduces it again.

**Comment by Drakulix** [comment]
Likely a duplicate of https://github.com/pop-os/cosmic-comp/issues/703

**Comment by squalou** [comment]
Indeed ! 
closing this one as it's just a poorer illustration of the issue.
