### ISSUE TITLE
Window size gets reset if you move the window

### ISSUE THREAD

**Issue by hojjatabdollahi** [pop-os/cosmic-comp#78]
To reproduce:

- Turn off tiling mode
- Open a window
- resize it
- Grab the window and move it

It will be resized back to what it was when you release the mouse.

**Comment by XV-02** [comment]
I'm closing this, as I no longer see the described behaviour on the current master builds of Cosmic DE after testing with native Cosmic applications as well as with GTK and Qt apps, both as debs and as flatpaks.
