### ISSUE TITLE
[Bug]: COSMIC fails to render ANY text

### ISSUE THREAD

**Issue by Elias-Graf** [pop-os/cosmic-comp#803]
![image](https://github.com/user-attachments/assets/de7e7fe0-4959-4761-a777-c969c24457db)

This happened after upgrading to the latest versions provided by this flake: https://github.com/lilyinstarlight/nixos-cosmic.

If you tell me how to get the version of `cosmic-comp`, I'll post it, but there doesn't seem to be a `cosmic-comp --version` or `-v`.

**Comment by Elias-Graf** [comment]
This is happening on my laptop running intel, and on my desktop running nvidia graphics if that is of any help: 
![image](https://github.com/user-attachments/assets/8620eb61-409e-4cf1-a725-5eb874bf7311)

**Comment by Drakulix** [comment]
This is a libcosmic bug, as shown by your terminal, text rendering isn't a responsibility of cosmic-comp.

**Comment by Elias-Graf** [comment]
Well the terminal (alacritty) has its own renderer, no? Anyway, I see what you mean and will move the issue, btw could be related to this, if the library is relying on a font being present: https://github.com/pop-os/cosmic-term/issues/323.
