### ISSUE TITLE
Regression - moving windows with Super + arrows shortcut broken across multiple monitors.

### ISSUE THREAD

**Issue by Kartonrealista** [pop-os/cosmic-comp#826]
For some reason this is broken as of now, you can't change focus across monitors with this shortcut anymore. It worked correctly before. Also, despite "Cursor follow focus" and "Focus follow cursor" toggles being disabled, the cursor goes to the other screen, even though focus does not go to the window on the other screen.

**Comment by Drakulix** [comment]
Should be fixed by https://github.com/pop-os/cosmic-comp/commit/5006eae60b4768fe7a678ee59497c1ca0994a246

**Comment by Kartonrealista** [comment]
It is
