### ISSUE TITLE
Resizing with super + right click opens the context menu in apps with them

### ISSUE THREAD

**Issue by BrodieRobertson** [pop-os/cosmic-comp#831]
If you do super + right click resizing, applications that have context menus or other actions on right click will still perform that action.

**Comment by git-f0x** [comment]
What version of cosmic-comp do you have? (though since you have focus follows cursor it should be new enough)
It should have been fixed by #750.

**Comment by BrodieRobertson** [comment]
Unless I've done something dumb it's built off the latest commit

**Comment by git-f0x** [comment]
Can reproduce on latest (in non-libcosmic apps). Might be a regression.

**Comment by BrodieRobertson** [comment]
Different toolkits and apps handle context menus slightly differently so the effect is kind of varied, in Firefox you can resize freely but just have a floating context menu, in KDEnlive the instant the context menu appeared the resize would break.

**Comment by Quackdoc** [comment]
this is a regression, ill be bisecting it at a later date, I believe 971c28d was a good commit

**Comment by Quackdoc** [comment]
Bisected to 7da0bc430a1c35f133ff24552c1c9903c65d3457

**Comment by Drakulix** [comment]
Should be fixed by https://github.com/pop-os/cosmic-comp/commit/b85b8fc7eb80a7629a199eaa859fef3a603b23f0

**Comment by git-f0x** [comment]
Can confirm that it's fixed on my end.

**Comment by BrodieRobertson** [comment]
It appears fixed for me as well
