### ISSUE TITLE
Context menus in certain GTK3 applications don't appear

### ISSUE THREAD

**Issue by BrodieRobertson** [pop-os/cosmic-comp#835]
In certain GTK3 applications like PCManFM GTK3 the context menu does not work, this doesn't happen all GTK3 apps, the new version of GIMP, or in Thunar seem to work fine, so it's unclear why this is happening. I've only ever seen this behavior on COSMIC, desktops like KDE Plasma do not have this issue

**Comment by WatchMkr** [comment]
Is this still an issue? They seem to be working okay now.
![image](https://github.com/user-attachments/assets/d1abb4f3-350c-4d60-8cf0-4a01b6ed4610)

**Comment by BrodieRobertson** [comment]
It appears to be working now
