### ISSUE TITLE
[Regression] Can no longer use keyboard to make application on another monitor focused

### ISSUE THREAD

**Issue by Quackdoc** [pop-os/cosmic-comp#841]
I haven't had the chance to bisect it, yet, but I think it was due to the cursor handling change, I can no longer use keyboard shortcut "super + arrow" to focus a window on a different monitor. regardless of  "Focus follows cursor" and "Cursor follows focus" settings

despite this my cursor actually does get sent to the second monitor when cursor follows focus is enabled.

also now if I have "cursor follows focus enabled",  if have an xwayland application open, press "super + right" until I have selected the right most window, press it again, my cursor seems to disappear and I need to refocus a window for it to come back

**Comment by Drakulix** [comment]
Should be fixed by https://github.com/pop-os/cosmic-comp/commit/5006eae60b4768fe7a678ee59497c1ca0994a246

**Comment by Quackdoc** [comment]
confirmed to be fixed
