### ISSUE TITLE
[Feature Request] Set solid color as background rather than an image

### ISSUE THREAD

**Issue by garrettjwilke** [pop-os/cosmic-comp#848]
It would be nice to have the option to set a solid color as a background rather than an image file as the background wallpaper.

this might also serve as a solution/bug fix to this issue:
https://github.com/pop-os/cosmic-comp/issues/638

if there is no wallpaper set, the system seems to run slower. so perhaps if the system cannot find the image, it can fallback to a default solid color.

**Comment by mmstick** [comment]
You can set a color or gradient on the Wallpaper settings page in cosmic-settings by selecting `Colors` the category dropdown.

**Comment by garrettjwilke** [comment]
ahh...thanks
