### ISSUE TITLE
"Authentication failed" when going to unlock the screen.

### ISSUE THREAD

**Issue by nevdelap** [pop-os/cosmic-comp#851]
I was on what is installed from the Arch repos and didn't have this issue, but updated to what's installed by `cosmic-session-git` from the AUR so that I can use focus follows mouse.

When the screen is locked I'll come back to it sometime later and it will say "Authentication failed" and be unresponsive, and I've ssh'ed in to log myself out, and I log back in.

It would be helpful if there is something I can kill in SSH to unlock the screen but I didn't find it (not that I've tried too hard since typing on a terminal on my phone is more tiresome than re-setting up my applications across workspaces).

I'll add a photo the next time it happens.

Please let me know what package implements the screen lock and I'll provide a version.

**Comment by l-const** [comment]
Hello @nevdelap , probably duplicate of https://github.com/pop-os/cosmic-greeter/issues/126 , `cosmic-greeter` is the package.

**Comment by nevdelap** [comment]
Thanks. @l-const. :+1:
