### ISSUE TITLE
shell/floating: Window maximization not handled correctly

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#86]
Maximizing a window adds that window to `Workspace.fullscreen`, which is a mapping between outputs and `CosmicSurface`s. This allows at most 1 window to be maximized per output per workspace. When the window is maximized it doesn't have decorations, and the panel doesn't seem to show. Other windows are not able to appear over it, and opening a new window on the same output unmaximizes the window.

This is generally not consistent with how maximizing should work. Typically in a floating WM it should be possible to have any number of windows maximized, they should still be decorated at least with a headerbar, the window shouldn't cover the panel. I believe maximization normally doesn't impact z-order or anything like that and just defines the size and position of the window.

**Comment by jacobgkau** [comment]
This is causing the Launcher to not show over the maximized window, in addition to the panel.

**Comment by XV-02** [comment]
Closing this, as I am no longer seeing the described behaviours. I can have multiple full screened windows in the same workspace, and can switch between them with the launcher. The launcher displays correctly, as do the panel and the dock. There are a few other quirks, but I feel they will be better served by a new issue which better focuses on those specific problems.
