### ISSUE TITLE
[Feature request] Global hotkeys Wayland implementation

### ISSUE THREAD

**Issue by hfc2x** [pop-os/cosmic-comp#878]
This is something that would be useful because there are some applications (such as screenshot tools, or screen recorders) that require the ability to set global shortcuts. These applications rely on the ability of X11 to set global hotkeys, but they have been updated to work with Wayland compositors that allow the ability to capture inputs and send them to background apps. Currently, Kwin is the only Wayland compositor that [supports global hotkeys](https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/blob/master/src/globalshortcuts.cpp?ref_type=heads).

Adding this feature to cosmic-comp would allow the use of applications such as [Flameshot](https://github.com/flameshot-org/flameshot) and [gpu-screen-recorder](https://git.dec05eba.com/gpu-screen-recorder/about/) without any complicated workarounds.

**Comment by alphabitserial** [comment]
Other use cases include voice conferencing (push-to-talk/push-to-mute) and dropdown terminals (e.g. Guake)

**Comment by Quackdoc** [comment]
Isn't global shortcuts a portals thing?

**Comment by hfc2x** [comment]
Yes, but each Wayland compositor needs to allow that individually.

**Comment by hfc2x** [comment]
I think #897 is exactly it. Knowing it's planned for alpha 4, I'm closing this then.
