### ISSUE TITLE
(Question) Do you plan to implement the Frog Protocols?

### ISSUE THREAD

**Issue by hardBSDk** [pop-os/cosmic-comp#881]
They aim to review and merge new protocols faster than Wayland Protocols.

https://www.phoronix.com/news/Mesa-frog-fifo-v1-MR

**Comment by Drakulix** [comment]
We are aware. We will see how the situation evolves. There is no sense in implementing something that has no clients yet (regarding frog-fifo, frog-color-management is a different beast, but HDR support is still far off).
