### ISSUE TITLE
Issues with `Global` workspaces mode

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#93]
I guess this hasn't been tested much, so it seems to have some issues.

* Input area of layer shell surfaces on additional monitor seems to be relative to first monitor, while window is rendered on correct monitor.
* There's something funny with window maximization and multiple monitors. I see part of the window on another output.
* New windows always appear on first monitor. They should probably appear on the one with the cursor.

**Comment by Drakulix** [comment]
Addressed in #194
