### ISSUE TITLE
[Bug] Floating window always on top of tiled windows

### ISSUE THREAD

**Issue by bobcat141** [pop-os/cosmic-comp#933]
**cosmic-comp version:** `0.1~1728985546~24.04~b8c429f`

When a workspace has tiling enabled and one of the windows is put on floating mode, even when focusing on a tiled window, the floating window will remain on top.

[2024-10-21 00-33-41.webm](https://github.com/user-attachments/assets/240618e8-8c6b-4d67-9bbe-2a9ea3df915a)

**Comment by Drakulix** [comment]
That is by design. Floating windows are on a layer above tiled windows.
