### ISSUE TITLE
Can't dismiss context menu on desktop by clicking on an empty space

### ISSUE THREAD

**Issue by hojjatabdollahi** [pop-os/cosmic-comp#941]
Not sure if that was an issue before today's render_input_order merge.

But if I right click on the desktop the context menu opens, but clicking on an empty space somewhere else on the desktop doesn't dismiss it.
I have to right click somewhere else for the previous context menu to close.

This works correctly inside cosmic-files, which probably means it's a cosmic-comp issue and specifically with the render_input_order. Probably. :) 

```
cosmic-comp: 0.1~1729619027~24.04~0092dac
cosmic-files: 0.1.0~1729611271~24.04~2871309
```

**Comment by l-const** [comment]
No, this is the case for a while now with cosmic-files and applet, see similar issues: https://github.com/pop-os/cosmic-files/issues/493

**Comment by hojjatabdollahi** [comment]
I hadn't noticed it before. Thank you.
