### ISSUE TITLE
Input: High frametimes when moving mouse

### ISSUE THREAD

**Issue by Vixea** [pop-os/cosmic-comp#95]
When moving the cursor slows down compositor to the point were it takes awhile to just move the cursor from one end of the display to the middle point. 

Edit:
This get more and more interesting built again this time with all-features and fastdebug, running a crude profile using sysprof(as I don't really know how to use puffin in comp yet) it seems most of the time is spent in rustybuzz's map Mapbuilder::compile() function which doesn't seem to be used in either comp or smithay. :shrug: And when also moving a window it doesn't have the issue or is less effected. :/

I would love to help out in this case could you point me to how you would debug comp's functions with puffin?

(Reporting just in case you haven't seen this issue as there are moments were it works just fine)

**Comment by Drakulix** [comment]
Yes, I have seen this bug, but I haven't had the time to properly profile and debug it yet.

> rustybuzz's map Mapbuilder::compile() function

That is likely related to the usage of `iced` in cosmic-comp to render window titles. (See here https://github.com/pop-os/cosmic-comp/blob/master_jammy/src/utils/iced.rs)

While building the title takes quite some time, that should be aggressively cached, so not the issue we are seeing here or if it is, that would be quite surprising.

> And when also moving a window it doesn't have the issue or is less effected. :/

Interesting observation!

> I would love to help out in this case could you point me to how you would debug comp's functions with puffin?

The feature hasn't been used a whole lot, but in theory you should be able to compile cosmic-comp with the "debug" feature enabled and when running it (assuming you are using the [default config](https://github.com/pop-os/cosmic-comp/blob/master_jammy/config.ron#L4)) hit "Super"+"Escape" to enable the debug view, were a puffin window should be visible.

Note that puffin requires functions to be explicitly annotated (example [here](https://github.com/pop-os/cosmic-comp/blob/master_jammy/src/backend/render/mod.rs#L175-L176)) and that hasn't been done very thoroughly in cosmic-comp yet. So you might need to add a few on your own.
Also note that cosmic-comps aggressive damage tracking will completely stop rendering, when nothing happens on the screen. That also means puffin's "frame" function will not be called, causing very high reported frame times, when actually the amount of time spent rendering is fine. So only trust actual rendering time as shown in the detail view of a frame.

I will also take a look at this issue.

**Comment by Drakulix** [comment]
I think I have fixed it, can you try the branch [fix/mouse_responsiveness](https://github.com/pop-os/cosmic-comp/tree/fix/mouse_responsiveness) please?

I still need to test a few interactions with this commit before pushing it to  master, but it appears high input-polling rates + low render times could cause a frame to be re-scheduled indefinitely. Resulting in the stutter mess you were seeing.
Once a few windows bring the average frame-time up just a bit (or by moving a window to do that artificially) the problem disappeared, because the main loop was more busy. Nevertheless this commit should also be an improvement in these scenarios.
