### ISSUE TITLE
Bottom part of windows that use SSDs isn't clickable

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-comp#951]
Elements (buttons, etc) within an area along the bottom of Xwayland windows (roughly 1 cm wide) can't be clicked. This started happening recently, so might be caused by #918.
This doesn't seem to affect fullscreen Xwayland windows.

**Comment by Drakulix** [comment]
I don't think this is specifically an Xwayland problem, but a problem of applications with server-side decorations. And yes #918 is likely the cause.

**Comment by git-f0x** [comment]
Ah, most of the apps with SSDs on my end are Xwayland apps, so I might have not tested it well. Can confirm that it seems SSD related, since I can reproduce it on `cosmic-files-applet` windows (settings and show details).

**Comment by git-f0x** [comment]
Fixed!
