### ISSUE TITLE
Disabling Dock causes hard freeze when maximizing window.

### ISSUE THREAD

**Issue by elevenhsoft** [pop-os/cosmic-comp#957]
Hey,

Not sure when it happened first time. Just noticed it yesterday, when my PC was freezing when window went in Maximized state.
Today I found the issue. When you disable dock, so panel is on top, and dock is off. This causes this issue. With panel and dock enabled. Everything works as expected.

The real problem is, when PC is freeze we can't even go into tty. It's just like hard freeze, so only hard reboot works.

**Comment by elevenhsoft** [comment]
Since it might be not a common problem, I'm using dual GPU, RX 6650xt on host machine and GTX 760 passing through to VM via vfio. However I know before it worked, not sure when but it worked. Also enabling dock fixes this issue, so I assume it's maybe related to compositor. For the displaying my VM I'm using looking-glass (which have few issues i will report :sweat_smile: )

It's really hard to debug this since we don't have access to anything after this "lock" so I don't know what can I do to provide more info.

**Comment by ids1024** [comment]
Maybe the same issue as https://github.com/pop-os/cosmic-comp/issues/887, if this is on Linux 6.11? In which case it appears to be a bug in amdgpu that upstream is aware of.

Starting cosmic-comp with the env var `COSMIC_DISABLE_DIRECT_SCANOUT=1` will disable direct scanout, and should prevent this.

**Comment by elevenhsoft** [comment]
Yes! It's `Linux pop-os 6.11.5-x64v3-xanmod1 #0~20241022.g01af8d9 SMP PREEMPT_DYNAMIC Tue Oct 22 18:19:28 UTC x86_64 x86_64 x86_64 GNU/Linux`

I will test `COSMIC_DISABLE_DIRECT_SCANOUT=1` and report back. Thanks!

**Comment by elevenhsoft** [comment]
> I wonder what are the side effects of this variable.

I think, if you don't game, there are not many side effects. Direct scanout reduce latency and gives you some performance improvements for fullscreen apps. It's something like disabling compositor on Xorg.

Since it's fixed for me and not really related to Cosmic I'm gonna close this issue.

**Comment by Drakulix** [comment]
It will be an important optimization in the future and I would rather not disable overlay planes by default, but rather here about all the configurations, that don't yet work quite right. 6.11 has this very unfortunate issue causing a bunch of people to turn on this flag, please remember to remove it once the upstream issue is resolved.
