### ISSUE TITLE
[FEATURE REQUEST] - Alt bar design for non-iced applications

### ISSUE THREAD

**Issue by ratnik2** [pop-os/cosmic-comp#967]
I'm not a very technical person when it comes to Linux and desktop environments. But I just wanted to say this cause I haven't seen anyone else say this.

_By the way, I have absolutely no idea if this is possible..._

Would it be possible to merge the alt bar with the application's header bar? And is it possible to make this happen to all non-iced applications like OBS, Libreoffice, Signal etc.?

For example:
![file](https://github.com/user-attachments/assets/8e13716a-a0af-4a4c-8ad8-527d429611ed)

I made a design as to how it could look better (change is on the header bar for VSCodium)
![new](https://github.com/user-attachments/assets/3069de40-e0b3-4401-90ab-fb6ab6aa3e70)

Under this design, VSCodium (as an example)  looks more native and matches very well with COSMIC files, COSMIC terminal and the accent color.

Also I don't know if this is the correct place to post this feature request, someone can send me the link to the correct repo if i am wrong. Thanks!

**Comment by Drakulix** [comment]
No it is not as long as we don't have any generic infrastructure for externalized menus on linux (which is not a thing COSMIC can solve on it's own, since that needs support from these apps).
