### ISSUE TITLE
[feature] change Alt-Tab window order

### ISSUE THREAD

**Issue by NChechulin** [pop-os/cosmic-comp#988]
Version: `0.1~1731406902~24.04~91bc1c0`

Currently, pressing Alt-tab once does not change anything, since the first selected window is the one in focus. Therefore, in order to switch to the previous window, one has to `Alt+tab+tab`, which is inconvenient and not how it is implemented in other systems.

The suggestion is to automatically preselect the second window in the list, not the first (= currently focused) one.

P.S. I am not entirely sure that I posted the issue in the correct repo. If I'm wrong, I will reopen it in the correct repository.
P.P.S Not sure whether it's a feature request or a bug fix request.

**Comment by git-f0x** [comment]
This is a known issue. It's being tracked here: pop-os/cosmic-launcher#135.
